### PR TITLE
Use Vault client's scheme for auto discovery

### LINKED ISSUE #2044: Can't discover Vault when it is TLS and Consul is not
I run a plaintext Consul with a TLS Vault.  Trying to run 
`vault init -auto -check`
fails:
`Error checking initialization status of discovered node: "http://address:port". Err: Get http://address:port/v1/sys/init: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`

The reason is [here](https://github.com/hashicorp/vault/blob/master/command/init.go#L85) - the command uses the scheme of the Consul client as the scheme of the Vault service, which doesn't make much sense (to me).

My suggestion would be to publish the Vault scheme to Consul in the service definition tags.  Then we'd have it back in the catalog output.

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #2044

### CODE REVIEW

File: api/client.go [hunk 1]
```diff
@@ -287,6 +287,11 @@ func (c *Client) SetAddress(addr string) error {
 	return nil
 }
 
+// Address returns the URL address of the Vault client
```
Comment (jefferai) [inline api/client.go]: I'd say "set on the Vault client" because otherwise it sounds like the client is listening on some address :-)
