### PR TITLE
Make the plugin catalog endpoint roundtrip so we can use terraform to manage them.

### LINKED ISSUE #3776: Plugin Catalog doesn't round trip, therefore doesn't work with terraform.
If I put some plugin JSON into the catalog, then read it back out, the JSON has been modified:
- The vault plugin dir has been prepended to the path.
- The sha256 has been base64 encoded
- Args have been broken out from command into a list.
- `"builtin": false` is added.

Eg:
```
$ cat plugin.json 
{
  "command": "google-auth-vault-plugin --ca-cert=/etc/vault/ca.pem --client-cert=/etc/vault/cert.pem --client-key=/etc/vault/key.pem",
  "name": "google-auth-vault-plugin",
  "sha256": "989845e5a0171d9e1b1c6d9ca13393dd031fd9068c200c52ec723737ed450d4d"
}
$ vault write sys/plugins/catalog/google-auth-vault-plugin @plugin.json
Success! Data written to: sys/plugins/catalog/google-auth-vault-plugin
$  vault read -format=json sys/plugins/catalog/google-auth-vault-plugin 
{
	"request_id": "d83dcd72-48a6-0c37-f9f8-13128d62e086",
	"lease_id": "",
	"lease_duration": 0,
	"renewable": false,
	"data": {
		"args": [
			"--ca-cert=/etc/vault/ca.pem",
			"--client-cert=/etc/vault/cert.pem",
			"--client-key=/etc/vault/key.pem"
		],
		"builtin": false,
		"command": "/etc/vault-plugins/google-auth-vault-plugin",
		"name": "google-auth-vault-plugin",
		"sha256": "mJhF5aAXHZ4bHG2coTOT3QMf2QaMIAxS7HI3N+1FDU0="
	},
	"warnings": null
}
```

The makes it super hard to manage plugins with terraform, as it needs to read back the JSON and compare it to see if it needs updating:

```
* vault_generic_secret.google_plugin_sha: error writing to Vault: Error making API request.

URL: PUT https://vault.uswest-cluster.aws.grapeshot.co.uk:8200/v1/sys/plugins/catalog/google-auth-vault-plugin
Code: 500. Errors:

* 1 error occurred:

* error while validating the command path: lstat /etc/vault-plugins/etc: no such file or directory
```

Suggestions:
- We don't leak the vault plugin dir when we read back
- We don't base64 encode the sha in the result
- We optionally accept arguments as an args list.

Thoughts?  I'm going to start a PR for this.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #3776 

You can now do:

```
$ cat plugin.json 
{
  "args": [
    "--ca-cert=/etc/vault/ca.pem",
    "--client-cert=/etc/vault/cert.pem",
    "--client-key=/etc/vault/key.pem"
  ],
  "command": "google-auth-vault-plugin",
  "name": "google-auth-vault-plugin",
  "sha256": "989845e5a0171d9e1b1c6d9ca13393dd031fd9068c200c52ec723737ed450d4d"
}
$ vault  write sys/plugins/catalog/google-auth-vault-plugin @plugin.json
Success! Data written to: sys/plugins/catalog/google-auth-vault-plugin
$ vault read --format json sys/plugins/catalog/google-auth-vault-plugin
{
	"request_id": "d61b86d4-f5c6-7334-3848-be4c8730f0b1",
	"lease_id": "",
	"lease_duration": 0,
	"renewable": false,
	"data": {
		"args": [
			"--ca-cert=/etc/vault/ca.pem",
			"--client-cert=/etc/vault/cert.pem",
			"--client-key=/etc/vault/key.pem"
		],
		"command": "google-auth-vault-plugin",
		"name": "google-auth-vault-plugin",
		"sha256": "989845e5a0171d9e1b1c6d9ca13393dd031fd9068c200c52ec723737ed450d4d"
	},
	"warnings": null
}
```

Which should be enough to allow terraform to manage plugins.

### CODE REVIEW

**Comment by tomwilkie** [comment]
Failures seem LDAP related?

**Comment by jefferai** [comment]
Yep, seems like the LDAP test server is down.

File: vault/logical_system.go [hunk 1]
```diff
@@ -1098,12 +1102,17 @@ func (b *SystemBackend) handlePluginCatalogUpdate(ctx context.Context, req *logi
 		return logical.ErrorResponse("missing command value"), nil
 	}
 
+	args := d.Get("args").([]string)
+	// For backwards compatibility, also accept args as part of command.
+	parts := strings.Split(command, " ")
+	args = append(parts[1:], args...)
```
Comment (jefferai) [inline vault/logical_system.go]: Please do a length check before this line to make sure the command actually has more than one value...otherwise it'll panic.

Comment (tomwilkie) [reply vault/logical_system.go]: Length >0 is assumed by the check for the empty string above (as with the previous iteration of the code).  But I'll add it anyway :-)

File: vault/logical_system.go [hunk 2]
```diff
@@ -1098,12 +1102,20 @@ func (b *SystemBackend) handlePluginCatalogUpdate(ctx context.Context, req *logi
 		return logical.ErrorResponse("missing command value"), nil
 	}
 
+	args := d.Get("args").([]string)
+	// For backwards compatibility, also accept args as part of command.
+	parts := strings.Split(command, " ")
+	if len(parts) <= 0 {
+		return logical.ErrorResponse("missing command value"), nil
+	}
+	args = append(parts[1:], args...)
```
Comment (jefferai) [inline vault/logical_system.go]: If they specify both `args` and put args in the command they'll end up with doubled args here. I think a better check would be to ensure that `len(parts) == 1` and if `args` is set and the length of `parts` is not 1, throw an error asking them to pick one or the other.

File: vault/plugin_catalog_test.go [hunk 3]
```diff
@@ -50,8 +50,8 @@ func TestPluginCatalog_CRUD(t *testing.T) {
 	}
 	defer file.Close()
 
-	command := fmt.Sprintf("%s --test", filepath.Base(file.Name()))
-	err = core.pluginCatalog.Set("mysql-database-plugin", command, []byte{'1'})
+	command := fmt.Sprintf("%s", filepath.Base(file.Name()))
+	err = core.pluginCatalog.Set("mysql-database-plugin", command, []string{"--test"}, []byte{'1'})
```
Comment (jefferai) [inline vault/plugin_catalog_test.go]: Please also an a check to verify correct behavior if both args and command-with-args are given (after fixing above)

**Comment by jefferai** [comment]
Looks good after the requested changes are made.

File: vault/plugin_catalog_test.go (hunk 3 above)
Comment (tomwilkie) [reply vault/plugin_catalog_test.go]: I've added the test to logical_system_test.go, as the logic to ensure only command or args is specified is in logical_system.go - hope thats okay!

**Comment by tomwilkie** [comment]
@jefferai sorry for the delay, have addressed your comments.  Thanks!

**Comment by jefferai** [comment]
Thanks!
