### PR TITLE
Enforce alphanumeric requirement in RandomAlphaNumeric

### LINKED ISSUE #2991: [database/postgres] redshift compatibility
the database/postgres backend works perfectly with redshift, except for one requirement, that the password must contain at least one upper character.

The following will fail with invalid password, as `{{password}}` is all lower-case

```
CREATE USER "{{name}}" PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}"
```

The following will work, but the password outputted by `vault read` does (for obvious reasons) not include the `A`. 

```
CREATE USER "{{name}}" PASSWORD 'A{{password}}' VALID UNTIL '{{expiration}}';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}"
```

Having the `{{password}}` output part of the password in uppercase (just character) would make it compatible.

Not sure what the best approach to fixing this would be.

If i can get some advice on how to best approach this, i can (probably) come up with a PR fixing it

### PR DESCRIPTION
**Pull request by calvn**
Fixes #2991

### CODE REVIEW

File: plugins/helper/database/credsutil/credsutil_test.go [hunk 1]
```diff
@@ -1,30 +1,32 @@
...
-		t.Fatal("Unexpected error: %s", err)
+		t.Fatalf("Unexpected error: %s", err)
 	}
-	if len(s) != 10 {
-		t.Fatal("Unexpected length of string, expected 10, got string: %s", s)
+	if len(s) != 20 {
+		t.Fatalf("Unexpected length of string, expected 20, got string: %s", s)
+	}
+
+	if len(s) == 0 {
```
Comment (briankassouf) [inline plugins/helper/database/credsutil/credsutil_test.go]: This isn't testing anything since the above branch ensures `len(s) == 20`

File: plugins/helper/database/credsutil/credsutil.go [hunk 2]
```diff
@@ -16,24 +18,35 @@ type CredentialsProducer interface {
...
+	reqStr    = `A1a`
+	minStrLen = 10
+)
+
+// RandomAlphaNumeric returns a random string of characters [A-Za-z0-9]
 // of the provided length.
-func RandomAlphaNumericOfLen(len int) ([]byte, error) {
-	retBytes := make([]byte, len)
-	size := 0
+func RandomAlphaNumeric(length int) (string, error) {
```
Comment (briankassouf) [inline plugins/helper/database/credsutil/credsutil.go]: Could you add a comment specifying the prepended string takes up 3 characters of space?

**Comment by josegonzalez** [comment]
@calvn I can send you a pizza pie once this is integrated/released in vault. Let me know where to ship it :)
