### PR TITLE
Fix hasMountPath for segment wildcard mounts; introduce priority order

### LINKED ISSUE #6525: Preflight check fails with ACL wildcard in path for `kv get` command
**Describe the bug**
When using the new ACL wildcard paths like `secret/data/foo/+/baz`, the preflight check will fail, at least in the CLI using `vault kv get`, even though the `vault read` command succeeds

**To Reproduce**

1. Run vault dev server with the KV v2 secrets engine enabled at `secret/`
2. Run `vault kv put secret/foo/bar/baz value=data`
3. Run 
```
vault policy write policy -<<EOF
path "secret/data/foo/+/baz" {
  capabilities = ["read"]
}
EOF
```
4. Create a token with that policy: `vault token create -orphan -policy=policy`
5. Using that token, run the following commands and receive the following results:
```
$ vault kv get secret/foo/bar/baz
Error making API request.

URL: GET http://localhost:8200/v1/sys/internal/ui/mounts/secret/foo/bar/baz
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "secret/foo/bar/baz/"

$ vault read secret/data/foo/bar/baz
Key         Value
---         -----
data        map[value:data]
metadata    map[deletion_time: destroyed:false version:1 created_time:2019-04-03T13:59:28.5410372Z]
```

**Expected behavior**
The preflight check should succeed.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.0
* Vault CLI Version (retrieve with `vault version`): 1.1.0
* Server Operating System/Architecture: Debian Stretch

### PR DESCRIPTION
**Pull request by jefferai**
This fixes `hasMountPath` when operating on segment wildcards, fixing the kv preflight check. As a part of this, I also introduce a longest-prefix priority ordering for cases where you have path segment wildcards in multiple paths. This will need some explanation in docs but for now it's well-commented.

Fixes #6525

### CODE REVIEW

File: vault/acl.go [hunk 1]
```diff
@@ -569,6 +511,219 @@ CHECK:
...
+	// We use these to find the most-specific matching path. In the case of
+	// multiple matches, we use this priority order, which tries to most
+	// closely match longest-prefix:
+	//
+	// * First wildcard position (prefer foo/bar/+/baz over foo/+/bar/baz)
+	// * Number of wildcard segments (prefer foo/bar/+/baz over foo/+/+/baz)
+	// * Total path segments (prefer foo/bar/+/baz/why over foo/bar/+/ba*)
+	// * Whether it's a prefix (prefer foo/+/bar over foo/+/ba*)
+	// * Length check (prefer foo/+/bar/ba* over foo/+/bar/b*)
+	// * Lexigraphical ordering (preferring less, arbitrarily)
```
Comment (vishalnayak) [inline vault/acl.go]:
```suggestion
	// * Lexicographical ordering (preferring less, arbitrarily)
```

File: vault/acl.go [hunk 2]
```diff
@@ -569,6 +511,219 @@ CHECK:
...
+	//
+	// That final case (lexigraphical) should never really come up. It's more
```
Comment (vishalnayak) [inline vault/acl.go]:
```suggestion
	// That final case (lexicographical) should never really come up. It's more
```

File: vault/acl.go [hunk 3]
```diff
@@ -569,6 +511,219 @@ CHECK:
...
+						continue
+					default:
+						// Same number of path segments. Next switch on prefix.
+						if isPrefix != currIsPrefix {
+							if isPrefix {
+								// This is a prefix but what we found earlier
+								// isn't; use that
+								continue
+							}
+							// Carry on checking
```
Comment (kalafut) [inline vault/acl.go]: Should the checks currently in the `else` block be run here?

File: vault/acl.go [hunk 4]
```diff
@@ -569,6 +511,219 @@ CHECK:
...
+						} else {
+							// At this point do a length check; failing that do
+							// a lexigraphical ordering. I actually can't
```
Comment (vishalnayak) [inline vault/acl.go]:
```suggestion
							// a lexicographical ordering. I actually can't
```

File: vault/acl.go [hunk 5]
```diff
@@ -569,6 +511,219 @@ CHECK:
...
+							// figure out when we'd get to the lexigraphical
```
Comment (vishalnayak) [inline vault/acl.go]:
```suggestion
							// figure out when we'd get to the lexicographical
```

**Comment by ncabatoff** [comment]
BTW, for those who've been looking at this PR, I've pushed #6535 to (I hope) simplify it.
