### PR TITLE
Run preSeal if postUnseal fails.

### LINKED ISSUE #733: failed to mount entry &vault.MountEntry{Path:"secret/"
This issue #648 is happening to me (0.3.0).  Does this issue have a known solution?  I would really rather not clear all the vault data and restart.  I am using Consul as a backend and getting the below message over and over.  I swapped out 3 aws instances with Consul and Vault on them with 3 new ones...then shut the old ones down and I believe this started happening when a Vault instance on one of the new servers tried to take leadership.  Consul reacted fine to all of this.

Error = failed to mount entry &vault.MountEntry{Path:"secret/", Type:"generic", Description:"generic secret storage", UUID:"b0ebbea3-c775-8cd4-2cf7-c16f91b5e7f9", Config:vault.MountConfig{DefaultLeaseTTL:0, MaxLeaseTTL:0}, Options:map[string]string{}, Tainted:false}: cannot mount under existing mount 'secret/'

### PR DESCRIPTION
**Pull request by jefferai**
This also ensures that every error path out of postUnseal returns an
error.

Fixes #733

### CODE REVIEW

File: vault/core.go [hunk 1]
```diff
@@ -1426,28 +1432,28 @@ func (c *Core) preSeal() error {
 		c.metricsCh = nil
 	}
 	if err := c.teardownAudits(); err != nil {
-		return err
+		retErr = errwrap.Wrapf("[ERR] error tearing down audits: {{err}}", err)
```
Comment (mitchellh) [inline vault/core.go]: these should probably have a `return` after them (and below, right?)

Comment (mitchellh) [inline vault/core.go]: and actually, if you want to run all of them, we maybe should use hashicorp/go-multierror  to accumulate errors.

**Comment by mitchellh** [comment]
I'd love to hear @armon's feedback on this too. I remember when we did Vault 0.1 we talked about how horrible the failure scenarios around pre/post failing are. The main thing is: does `preUnseal` properly undo everything? Is it idempotent? etc. 

We need to make sure we don't get the Vault into an unrecoverable state flapping back and froth here.

File: vault/core.go (hunk 1 above)
Comment (jefferai) [inline vault/core.go]: That my be a better approach. I'll look into that instead of `errwrap`.

**Comment by jefferai** [comment]
I had a discussion with @armon about this on Friday. I checked into `preSeal` and it does appear to be idempotent, and even better, due to a bug (fixed in this PR) we were already running it twice every time we lost leadership  :-/

File: vault/core.go (hunk 1 above)
Comment (mitchellh) [inline vault/core.go]: They actually co-exist, you should use both

**Comment by mitchellh** [comment]
Great then! Just fix the err stuff and we should be good.

**Comment by mitchellh** [comment]
LGTM
