### PR TITLE
Backport of VAULT-28255: Fix namespaced redirects into release/1.17.x

### LINKED ISSUE #27551: Subscribe to events notifications does not work on secondary nodes
**Describe the bug**
Subscribe to events notifications does not work on secondary nodes.
**To Reproduce**
1. Create a cluster with at least 3 nodes
2. Create a namespace
3. Under the namespace, create a mount point
4. Try to subscribe to events for the created mount point under the namespace by sending a request to a secondary node
5. Note the error: https://<cluster_address>v1/<namespace>/sys/events/subscribe/kv-v2/%2A?json=true isn't a valid URI: scheme isn't ws or wss

**Expected behavior**
Subscribe should work.
**Environment:**
* Vault Server Version 1.16.3
* Vault CLI Version: Not used, REST API used instead

Vault server configuration file(s):

```
The test cluster is a 3 node enterprise cluster.
```

**Additional context**
-

### PR DESCRIPTION
**Pull request by hc-github-team-secure-vault-core**
## Backport

This PR is auto-generated from #27660 to be assessed for backporting due to the inclusion of the label backport/1.17.x.

The below text is copied from the body of the original PR.

---

### Description
Fix redirects when a namespace is included in the namespace header, or for events when it's included in the path.
Fixes #27551. 

### TODO only if you're a HashiCorp employee
- [x] **Labels:** If this PR is the CE portion of an ENT change, and that ENT change is
  getting backported to N-2, use the new style `backport/ent/x.x.x+ent` labels
  instead of the old style `backport/x.x.x` labels.
- [x] **Labels:** If this PR is a CE only change, it can only be backported to N, so use
  the normal `backport/x.x.x` label (there should be only 1).
- [x] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
  of a public function, even if that change is in a CE file, _double check_ that
  applying the patch for this PR to the ENT repo and running tests doesn't
  break any tests. Sometimes ENT only tests rely on public functions in CE
  files.
- [x] **Jira:** If this change has an associated Jira, it's referenced either
  in the PR description, commit message, or branch name.
- [ ] **RFC:** If this change has an associated RFC, please link it in the description.
- [x] **ENT PR:** If this change has an associated ENT PR, please link it in the
  description. Also, make sure the changelog is in this PR, _not_ in your ENT PR.

---

<details>
<summary> Overview of commits </summary>

  - 9e299c2896f3978938a94a3863f986a22b80bd3d 

</details>

### CODE REVIEW

File: http/handler.go [hunk 1]
```diff
@@ -961,9 +959,25 @@ func forwardRequest(core *vault.Core, w http.ResponseWriter, r *http.Request) {
...
+	if !redirect && !core.PerfStandby() {
+		for _, websocketPath := range websocketRawPaths {
+			if strings.Contains(path, websocketPath) {
+				redirect = true
+				break
+			}
+		}
+	}
+	if redirect {
+		core.Logger().Trace("cannot forward request (path included in always redirect paths), falling back to redirection to standby")
```
Comment (miagilepner) [inline http/handler.go:979]: The conflict came from this log line, which isn't present on 1.17. However, since it's a trace log I figured it's worth it to include it.

**Review by mpalmi — APPROVED** [review]
