### PR TITLE
Correct Default for MaximumPageSize

### LINKED ISSUE #20416: Regression 1.13.2: "no LDAP groups found in groupDN"
This is a regression after upgrading 1.13.1 to 1.13.2.

We have LDAP authentication configured against AD, using this groupfilter:

"(&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}}))

Login still works, but we get an error in the Web UI:

"no LDAP groups found in groupDN [...] only policies from locally-defined groups available".  The token then won't get any LDAP-related policies attached.

Downgrading to 1.13.1 fixes the issue.

### PR DESCRIPTION
**Pull request by ltcarbonell**
This pull request addresses a problem that was introduced in a previous pull request (#19032). The earlier PR added a new configuration option called max_page_size to the LDAP secret engine. This option allows users to adjust the size of the paged search results. By default, it is set to 2147483647 (math.MaxInt32), but it can also be set to -1 to use non-paged searching.

The issue occurs when upgrading Vault to 1.13.2, 1.12.6, or 1.11.10, that has an existing LDAP Auth configuration. This would result in the `max_page_size` being set to 0 instead of the intended default of 2147483647.

Resolves #20416

### CODE REVIEW

File: sdk/helper/ldaputil/client.go [hunk 1]
```diff
@@ -553,7 +553,7 @@ func (c *Client) GetLdapGroups(cfg *ConfigEntry, conn Connection, userDN string,
 	if cfg.UseTokenGroups {
 		entries, err = c.performLdapTokenGroupsSearch(cfg, conn, userDN)
 	} else {
-		if paging, ok := conn.(PagingConnection); ok && cfg.MaximumPageSize >= 0 {
+		if paging, ok := conn.(PagingConnection); ok && *cfg.MaximumPageSize >= 0 {
```
Comment (austingebauer) [inline sdk/helper/ldaputil/client.go:556]: The reports in https://github.com/hashicorp/vault/issues/20416 make me wonder if enabling paging by default is the right choice. Many are encountering issues and disabling it by setting the value to -1. Prior to `MaximumPageSize` existing, paging was not used. IIUC, paging is now enabled by default for users who are upgrading. I wonder if that behavior change will continue to catch users off guard.

Alternatively, the default could be -1 which would preserve expected behavior for users who are upgrading. The paging behavior could be opt-in. Let me know if I'm not understanding this correctly 🙂

Comment (ltcarbonell) [reply sdk/helper/ldaputil/client.go:556]: That makes sense to me.  I am okay with that solution.

Comment (maxb) [reply sdk/helper/ldaputil/client.go:561]: Hang on a minute, is that really true?

Didn't this entire saga start, because a user had a case where their server refused the use of paging, and wanted it made optional?

Having paging on by default is absolutely a good user-friendly common-case behaviour, because if you turn off paging, you spontaneously run into problems when the size of the LDAP queries that Vault needs to perform, exceeds the LDAP server's size limits.

Comment (maxb) [reply sdk/helper/ldaputil/client.go:561]: Oh, and as far as I can see, everyone's picking -1 because it's an easy obvious constant - unlike the numeric value corresponding to math.MaxInt32. The people selecting -1 are unwittingly configuring a less-than-ideal setting.

**Comment by maxb** [comment]
After the comments I made earlier today, I spent some more time investigating. I uncovered some interesting information.

First, it's kind of weird this option is named `max_page_size`. IMO it would have been more logical to just call it `page_size`. It is not actually treated as a maximum, it is simply the page size we ask the LDAP server to provide us with.

Next, sending a page size of zero is **always wrong**, as this is a special value that instructs the server to terminate an in-progress paging result set, and if sent with an initial query, will prevent the server returning any results (hence the regression that was reported).

Since a page size of zero is invalid, I propose that this PR should not change the Go type used for `MaximumPageSize` from `int` to `*int`, as the simple zero value is available to use as an unspecified value.

Additionally, requesting a page size of 2147483647 never makes any sense, because that's what we send as our size limit - and RFC 2696 that defines the paging control explicitly says a page size equal or greater to the size limit is to be ignored by servers.

Taking all this into account, I agree with the proposal to change the default behaviour to "no paging", because the only useful use of paging, is one set to cooperate with the server defined limits. In a default Active Directory installation, the maximum page size the server will permit is 1000, so Active Directory users will probably want to set `max_page_size=1000`.

File: sdk/helper/ldaputil/client.go [hunk 2]
```diff
@@ -388,6 +388,11 @@ func (c *Client) performLdapFilterGroupsSearchPaging(cfg *ConfigEntry, conn Pagi
 		return make([]*ldap.Entry, 0), nil
 	}
 
+	if *cfg.MaximumPageSize < 0 {
+		c.Logger.Warn("maximumpagesize is negative, will not query server")
+		return make([]*ldap.Entry, 0), nil
+	}
+
```
Comment (maxb) [inline sdk/helper/ldaputil/client.go:395]: I suggest not adding this code, as it is effectively unreachable - this function is only invoked when this condition is false.

File: sdk/helper/ldaputil/client.go [hunk 3]
```diff
@@ -553,7 +558,7 @@ func (c *Client) GetLdapGroups(cfg *ConfigEntry, conn Connection, userDN string,
 	if cfg.UseTokenGroups {
 		entries, err = c.performLdapTokenGroupsSearch(cfg, conn, userDN)
 	} else {
-		if paging, ok := conn.(PagingConnection); ok && cfg.MaximumPageSize >= 0 {
+		if paging, ok := conn.(PagingConnection); ok && *cfg.MaximumPageSize >= 0 {
```
Comment (maxb) [inline sdk/helper/ldaputil/client.go:561]: I propose that if the page size is set to 0, a non-paged search should be done, as 0 is an invalid value to use as a page size.

```suggestion
		if paging, ok := conn.(PagingConnection); ok && *cfg.MaximumPageSize > 0 {
```

Comment (maxb) [inline sdk/helper/ldaputil/client.go:561]: I propose that if the page size is set to 0, a non-paged search should be done, as 0 is an invalid value to use as a page size.

```suggestion
		if paging, ok := conn.(PagingConnection); ok && *cfg.MaximumPageSize > 0 {
```

File: sdk/helper/ldaputil/config.go [hunk 4]
```diff
@@ -256,7 +255,7 @@ Default: ({{.UserAttr}}={{.Username}})`,
 		"max_page_size": {
 			Type:        framework.TypeInt,
 			Description: "The maximum number of results to return for a single paged query. If not set, the server default will be used for paged searches. A requested max_page_size of 0 is interpreted as no limit by LDAP servers. If set to a negative value, search requests will not be paged.",
```
Comment (maxb) [inline sdk/helper/ldaputil/config.go:257]: This description could use a re-work.

> If not set, the server default will be used for paged searches.

No longer true, if the user does not set this, searches will be done without paging.

> A requested max_page_size of 0 is interpreted as no limit by LDAP servers.

Not true. A size of 0 is invalid and causes the LDAP server to return no results.

File: sdk/helper/ldaputil/config.go [hunk 5]
```diff
@@ -464,7 +464,7 @@ type ConfigEntry struct {
 	RequestTimeout           int    `json:"request_timeout"`
 	ConnectionTimeout        int    `json:"connection_timeout"`
 	DerefAliases             string `json:"dereference_aliases"`
-	MaximumPageSize          int    `json:"max_page_size"`
+	MaximumPageSize          *int   `json:"max_page_size"`
```
Comment (maxb) [inline sdk/helper/ldaputil/config.go:467]: I propose this should stay as an `int`, as the zero value is not valid configuration, so there is no need to discriminate between "set to 0" and "not set".

File: website/content/api-docs/auth/ldap.mdx [hunk 6]
```diff
@@ -97,7 +97,7 @@ This endpoint configures the LDAP auth method.
 - `dereference_aliases` `(string: never)` - When aliases should be dereferenced
   on search operations. Accepted values are 'never', 'finding', 'searching',
   'always'. Defaults to 'never'.
-- `max_page_size` `(int: math.MaxInt32)` - If set to a value greater than 0, the LDAP
+- `max_page_size` `(int: -1)` - If set to a value greater than 0, the LDAP
   backend will use the LDAP server's paged search control to request pages of
   up to the given size. This can be used to avoid hitting the LDAP server's
   maximum result size limit. A value of 0 will be interpreted by the LDAP
```
Comment (maxb) [inline website/content/api-docs/auth/ldap.mdx:103]: > A value of 0 will be interpreted by the LDAP server as unlimited.

Not true. A size of 0 is invalid and causes the LDAP server to return no results.

**Comment by CodeGlitcher** [comment]
We run into the same issue.
any value besides 0 works.

Any change this could be added to the release notes as a known issue.
Would have saved me some searching.

File: sdk/helper/ldaputil/config.go (hunk 4 above)
Comment (jasonodonnell) [reply sdk/helper/ldaputil/config.go:257]: Go LDAP doc suggests otherwise: https://github.com/go-ldap/ldap/blob/v2.5.1/search.go#L305

File: website/content/api-docs/auth/ldap.mdx (hunk 6 above)
Comment (jasonodonnell) [reply website/content/api-docs/auth/ldap.mdx:103]: https://github.com/go-ldap/ldap/blob/v2.5.1/search.go#L305

File: sdk/helper/ldaputil/config.go (hunk 5 above)
Comment (jasonodonnell) [reply sdk/helper/ldaputil/config.go:467]: Agreed.

File: sdk/helper/ldaputil/client.go (hunk 3 above)
Comment (maxb) [reply sdk/helper/ldaputil/client.go:561]: That comment in go-ldap looks incorrect to me. I tested it, too, pointing Vault at OpenLDAP and monitoring the LDAP traffic with Wireshark - 0 resulted in the defective behaviour that many people have reported in #20416, not what that comment claims.

File: sdk/helper/ldaputil/config.go (hunk 4 above)
Comment (maxb) [reply sdk/helper/ldaputil/config.go:257]: (See response above)

File: website/content/api-docs/auth/ldap.mdx (hunk 6 above)
Comment (maxb) [reply website/content/api-docs/auth/ldap.mdx:103]: (See response above)

File: sdk/helper/ldaputil/client.go (hunk 3 above)
Comment (jasonodonnell) [reply sdk/helper/ldaputil/client.go:561]: Thanks @maxb! My concern here is different flavors of LDAP may have different results but looking at [LDAP RFC's](https://docs.ldap.com/specs/rfc2696.txt) I don't really see anything covering this except:

```
   A sequence of paged search requests is abandoned by the client
   sending a search request containing a pagedResultsControl with the
   size set to zero (0) and the cookie set to the last cookie returned
   by the server.  A client MAY use the LDAP Abandon operation to
   abandon one paged search request in progress, but this is discouraged
   as it MAY invalidate the client's cookie.
```

@ltcarbonell I think we can go with 0.

**Comment by Cajga** [comment]
As I wrote it in the related issue opened by others, **this bug closed us out from our vault cluster.**

We have all policies bind to LDAP groups and we revoked the root token.

**Review by jasonodonnell — APPROVED** [review]

File: website/content/docs/upgrading/upgrade-to-1.13.x.mdx [hunk 7]
```diff
@@ -127,3 +136,4 @@ Affects Vault 1.13.0 to 1.13.2. Fixed in 1.13.3.
 On upgrade, all local revocations will be synchronized between
 clusters; revocation requests are not persisted when failing to
 write cross-cluster.
+
```
Comment (ltcarbonell) [inline website/content/docs/upgrading/upgrade-to-1.13.x.mdx:139]:
```suggestion
```

File: sdk/helper/ldaputil/client.go [hunk 8]
```diff
@@ -553,7 +553,7 @@ func (c *Client) GetLdapGroups(cfg *ConfigEntry, conn Connection, userDN string,
 	if cfg.UseTokenGroups {
 		entries, err = c.performLdapTokenGroupsSearch(cfg, conn, userDN)
 	} else {
-		if paging, ok := conn.(PagingConnection); ok && cfg.MaximumPageSize >= 0 {
+		if paging, ok := conn.(PagingConnection); ok && cfg.MaximumPageSize > 0 {
```
Comment (calvn) [inline sdk/helper/ldaputil/client.go:556]: I'm not sure if there's already a test case that covers this, but wondering if we should make sure that setting max_page_size to zero doesn't actually result in an group search that returns no group (which was the main issue with the regression).

Comment (jasonodonnell) [reply sdk/helper/ldaputil/client.go:556]: @calvn When 0 is set it swaps out to the non-paged search which ldaputil has always used.

**Comment by ltcarbonell** [comment]
> As I wrote it in the related issue opened by others, **this bug closed us out from our vault cluster.** We have all policies bind to LDAP groups and we revoked the root token.
> 
> It would be nice if you could mention this regression in the CHANGELOG. So, people who use LDAP and read release notes before upgrade (like I did) will not run into this.

Good idea.  This will be added to this doc here: https://developer.hashicorp.com/vault/docs/upgrading/upgrade-to-1.13.x#known-issues

File: sdk/helper/ldaputil/client.go (hunk 8 above)
Comment (calvn) [reply sdk/helper/ldaputil/client.go:556]: Right, the removal of `=` makes it so that the zero value doesn't result in a paged search. I was mostly asking whether we should have a test case to cover this to prevent future regression.

File: changelog/20453.txt [hunk 9]
```diff
@@ -0,0 +1,3 @@
+```release-note:bug
+ldap: Set default value for `max_page_size` properly
```
Comment (austingebauer) [inline changelog/20453.txt:2]: nit: To follow changelog convention and make it clear the fix is in the auth method

```suggestion
auth/ldap: Set default value for `max_page_size` properly
```

**Review by austingebauer — APPROVED** [review]
