### PR TITLE
Correct migration case to Shamir where it's not explicit

### LINKED ISSUE #6455: Unable to migrate seal in V1.1.0
**Environment:**

* Vault Version: 1.1.0
* Operating System/Architecture: Linux

**Vault Config File:**

```hcl
storage "consul" {
address = "127.0.0.1:8500"
tls_skip_verify = "false"
scheme = "http"
redirect_addr = "https://vault1.**.com.:8200"
disable_clustering = "false"
}

ui = true
listener "tcp" {
address = "0.0.0.0:8200"
cluster_address = "vault1.**.com.:8201"

tls_cert_file = ""
tls_key_file = ""

tls_min_version = "tls10"
}
telemetry {
statsd_address = "localhost:8125"
disable_hostname = true
}

seal "awskms" {
disabled = "true"
region = "us-east-1"
kms_key_id = "abc"
}
```

**Startup Log Output:**

```
Error:
Could not create barrier seal! Most likely proper Seal configuration information was not set, but no error was generated.
```

**Expected Behavior:**
Migrate seal configuration from AWSKMS to Shamir

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

I am trying to migrate the seal configuration from KMS to Shamir in Vault 1.1.0.. However, I am getting the error mentioned above.
Steps:
1. Stop running vault server
2. Update vault seal config by adding disabled flag to true
3. Start Vault server
4. Unseal vault with -migrate flag

### PR DESCRIPTION
**Pull request by jefferai**
If you were migrating to Shamir but didn't specify a Shamir block
migration would fail. Being explicit is nice but it's also not really
obvious since you don't need the block normally.

Fixes #6455

### CODE REVIEW

File: command/server.go [hunk 1]
```diff
@@ -511,8 +511,15 @@ func (c *ServerCommand) Run(args []string) int {
 		barrierSeal = vault.NewAutoSeal(vaultseal.NewTestSeal(nil))
 	} else {
 		// Handle the case where no seal is provided
-		if len(config.Seals) == 0 {
+		switch len(config.Seals) {
+		case 0:
 			config.Seals = append(config.Seals, &server.Seal{Type: vaultseal.Shamir})
+		case 1:
```
Comment (tyrannosaurus-becks) [inline command/server.go]: What if they had multiple seal stanzas that were disabled? Should this logic instead be like, if they have no seal stanzas, or if they do but they're all disabled? 

Kind of an edge case, but could happen. Like maybe if they'd originally used a GCP key, then AWS, and now back to Shamir.

If that seems too edge-case-y, this seems totally fine.

Comment (jefferai) [reply command/server.go]: See https://github.com/hashicorp/vault/blob/master/command/server/config.go#L802 in conjunction with https://github.com/hashicorp/vault/blob/master/command/server/config.go#L834

Comment (tyrannosaurus-becks) [reply command/server.go]: Gotcha, thanks!

**Comment by v6** [comment]
Ah, I think I may have run into this here: 

https://groups.google.com/forum/#!topic/vault-tool/UJnofa9GloQ
