### PR TITLE
Have Okta respect its set max_ttl.

### LINKED ISSUE #4110: Okta auth backend doesn't respect its own max_ttl
**Environment:**

* Vault Version: 0.9.5
* Operating System/Architecture: linux_amd64

**Vault Config File:**
```
storage "file" {
  path = "/opt/vault/storage"
}
listener "tcp" {
  address         = "0.0.0.0:8200"
  tls_cert_file   = "/opt/vault/config/vault.crt"
  tls_key_file    = "/opt/vault/config/vault.key"
}
```

**Startup Log Output:**
```
==> Vault server configuration:

                     Cgo: disabled
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Storage: file
                 Version: Vault v0.9.5
             Version Sha: 36edb4d42380d89a897e7f633046423240b710d9

==> Vault server started! Log data will stream in below:
```

**Expected Behavior:**

After enabling and configuring [Okta auth backend](https://www.vaultproject.io/docs/auth/okta.html#configuration) with `max_ttl` different than zero, without changing the [default_lease_ttl](https://www.vaultproject.io/docs/configuration/index.html#default_lease_ttl) and the [max_lease_ttl](https://www.vaultproject.io/docs/configuration/index.html#max_lease_ttl), any successfully authenticated user should get a token with a duration <= `max_ttl`.

**Actual Behavior:**

Successfully authenticated users get a token with duration = 768h, although Okta backend was configured with `max_ttl=1h`.

**Steps to Reproduce:**

1. Enable Okta auth backend
1. Configure Okta auth backend with `max_ttl=1h`
1. Authenticate to Vault through Okta
1. Look for the `token_duration` line in Vault's output

**Important Factoids:**

If Okta auth backend is configured with both `max_ttl=1h` **and** `ttl=1h` then token's duration is limited to 1h.

### PR DESCRIPTION
**Pull request by jefferai**
Fixes #4110

### CODE REVIEW

File: builtin/credential/okta/path_login.go [hunk 1]
```diff
@@ -96,6 +96,21 @@ func (b *backend) pathLogin(ctx context.Context, req *logical.Request, d *framew
...
+	}
+	if cfg.MaxTTL > 0 {
+		maxTTL := cfg.MaxTTL
+		if maxTTL > b.System().MaxLeaseTTL() {
+			maxTTL = b.System().MaxLeaseTTL()
+		}
+
+		if resp.Auth.TTL > maxTTL {
+			resp.Auth.TTL = maxTTL
+			resp.AddWarning(fmt.Sprintf("Effective TTL of '%s' exceeded the effective max_ttl of '%s'; TTL value is capped accordingly", resp.Auth.TTL, maxTTL))
```
Comment (vishalnayak) [inline builtin/credential/okta/path_login.go]: I assume that you'd want the `%d` change done to this warning as well.

Comment (jefferai) [reply builtin/credential/okta/path_login.go]: We're pretty inconsistent across Vault on this. Other auth backends have it this way. Once we settle on a standard we can update them all.
