### PR TITLE
More Mount Conflict Detection

### LINKED ISSUE #2878: Mount conflict inconsistency
We stumbled across something interesting with regards to how generic mountpoint conflicts are handled. We are not sure if this is the desired behavior or not. We understand that "sub mounts" are not supported, however this constraint seems to be only enforced in one direction.

This particular set of commands exhibits the behavior we expect.
```
$ vault mount -path foo generic
Successfully mounted 'generic' at 'foo'!
$ vault mount -path foo/bar generic
Mount error: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/mounts/foo/bar
Code: 400. Errors:

* existing mount at foo/
```

The next set is what we find confusing. One might (possibly naively) expect that the second command, a "sub mount", would conflict with the first. Instead what we see is that the second mount works fine, with the third behaving consistently (as compared to the first example).

```
$ vault mount -path fom/bar generic
Successfully mounted 'generic' at 'fom/bar'!
$ vault mount -path fom generic
Successfully mounted 'generic' at 'fom'!
$ vault mount -path fom/baz generic
Mount error: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/mounts/fom/baz
Code: 400. Errors:

* existing mount at fom/
```

If this is considered a bug, I'm totally willing to submit a pull request to fix it. If it is not, then I am totally willing to to submit a pull request to clarify the documentation.

### PR DESCRIPTION
**Pull request by otakup0pe**
Ensure that we are not creating a "submount" underneath an already
existing mountpoint. This (hopefully) fixes #2878

Note that (locally) I'm seeing intermittent (~25% of the time on the full test suite) build failures 😿  

```
--- FAIL: TestCluster_ForwardRequests (9.16s)
        cluster_test.go:350: err: error during forwarding RPC request
```

### CODE REVIEW

**Comment by otakup0pe** [comment]
I'm missing something about the intersection between the router and logical backends... Doing some (manual) smoke testing, I noticed this repeating in the logs...

```
2017/06/24 10:14:45.630510 [ERROR] rollback: error rolling back: path=foo/ error=unsupported path
```

**Comment by jefferai** [comment]
The issue is that what's in the router's `Mount` code is only an extra check; the code in mount.go and auth.go check for an exact match via the router's MatchingMount, but then if that doesn't find a conflict they add the new entry into the table, *then* mount it on the router. The reason is that once a backend is able to be sent requests, we want it to already be stored so if Vault goes down it can come back up.

The right thing to do would probably be to take the logic you wrote and the check above for a longest prefix and combine it into two functions inside the router, something like AllowedMount and allowedMountInternal. The latter takes that logic and returns an error or not, and can be used inside the router's Mount function. The former does the same thing but gets a read lock (see MatchingMount); this can be called from mount.go and auth.go instead of the existing MatchingMount call.

**Comment by otakup0pe** [comment]
Thanks for the guidance, those changes cleared up the rollback error. Any guidance on why postgres tests are (consistently) failing? Basis test suite (`make test TEST=./vault`) is fine.

```
--- FAIL: TestPostgreSQL_RenewUser (8.30s)
        postgresql_test.go:182: Could not connect with new credentials: pq: password authentication failed for user "v-test-test-ZLS5aFHTd2RNsz8eDKV8-1498407266"
--- FAIL: TestPostgreSQL_RevokeUser (7.56s)
        postgresql_test.go:250: Could not connect with new credentials: pq: password authentication failed for user "v-test-test-WzseS2eTjqgckXSBWefZ-1498407274"
FAIL
FAIL    github.com/hashicorp/vault/plugins/database/postgresql  36.679s
```

File: vault/auth.go [hunk 1]
```diff
@@ -73,7 +73,7 @@ func (c *Core) enableCredential(entry *MountEntry) error {
 		return fmt.Errorf("token credential backend cannot be instantiated")
 	}
 
-	if match := c.router.MatchingMount(credentialRoutePrefix + entry.Path); match != "" {
+	if match := c.router.MountConflict(credentialRoutePrefix + entry.Path); match != "" {
```
Comment (jefferai) [inline vault/auth.go]: For ease of understanding, can you change `match` here to `conflict` and in the error message say "conflicting mount at ..."?

File: vault/router.go [hunk 2]
```diff
@@ -60,6 +60,13 @@ func (r *Router) Mount(backend logical.Backend, prefix string, mountEntry *Mount
 	if existing, _, ok := r.root.LongestPrefix(prefix); ok && existing != "" {
 		return fmt.Errorf("cannot mount under existing mount '%s'", existing)
 	}
+	// If this is a secret backend, check to see if the prefix conflicts
+	// with an existing mountpoint
+	if prefix != "" {
+		if match := r.MatchingPrefix(prefix); match != "" {
+			return fmt.Errorf("cannot mount under existing mount '%s'", match)
```
Comment (jefferai) [inline vault/router.go]: Isn't this checking for mounting *over* an existing mount?

File: vault/router.go [hunk 3]
```diff
@@ -174,6 +181,32 @@ func (r *Router) MatchingMount(path string) string {
 	return mount
 }
 
+//MatchingPrefix returns a mount prefix that a path may be a part of
+func (r *Router) MatchingPrefix(path string) string {
+	var existing string = ""
+	fn := func(existing_path string, _v interface{}) bool {
+		fmt.Println(fmt.Sprintf("comparing %v %v", path, existing_path))
```
Comment (jefferai) [inline vault/router.go]: I'm guessing this was a debug line you meant to take out

Comment (otakup0pe) [inline vault/router.go]: How embarrassing 😬

Comment (jefferai) [inline vault/router.go]: Mostly it was like, um, that's going to spam logs a *LOT*  :-)

Comment (otakup0pe) [inline vault/router.go]: Which is why it's embarrassing 👼 

New commit incorporates the feedback and I added a little blurb to the docs about mount conflicts.

File: vault/router.go [hunk 4]
```diff
@@ -174,6 +181,31 @@ func (r *Router) MatchingMount(path string) string {
 	return mount
 }
 
+//MatchingPrefix returns a mount prefix that a path may be a part of
+func (r *Router) MatchingPrefix(path string) string {
```
Comment (jefferai) [inline vault/router.go]: This function doesn't get a read lock but should, as it can be called externally (via MountConflict from the mount code). However, it is called with a lock already held from the router's Mount function.

The way to deal with this would be to have MatchingPrefix grab a read lock, then call matchingPrefixInternal which has the actual logic. The router's Mount function would then just call matchingPrefixInternal directly.

File: website/source/docs/secrets/index.html.md [hunk 5]
```diff
@@ -59,6 +59,13 @@ Once a secret backend is mounted, you can interact with it directly
 at its mount point according to its own API. You can use the `vault path-help`
 system to determine the paths it responds to.
 
+Note that mount point cannot conflict with each other in Vault. There are
```
Comment (jefferai) [inline website/source/docs/secrets/index.html.md]: s/point/points

File: vault/router.go [hunk 6]
```diff
@@ -174,6 +181,31 @@ func (r *Router) MatchingMount(path string) string {
...
+	var existing string = ""
+	fn := func(existing_path string, _v interface{}) bool {
```
Comment (jefferai) [inline vault/router.go]: If this function executes _at all_ wouldn't it mean that we've found a prefix? Is the `if` check unnecessary here?

**Comment by otakup0pe** [comment]
Added the read lock and fixed a typo but wasn't clear on the third statement. The `if` in what is now `matchingPrefixInternal` checks each entry in the radix tree... If you meant the `if` on line [67](https://github.com/otakup0pe/vault/blob/f3136f0fa49d5c32e5f63c103bb1bb0a72210e6e/vault/router.go#L67) - that is there because some entities (like policies iirc) didn't seem to have a prefix set...

**Comment by otakup0pe** [comment]
Just noticed tests failed (they are passing locally). Will take a look this afternoon/evening... Unless someone can restart the build 👼

File: vault/router.go [hunk 7]
```diff
@@ -62,6 +62,13 @@ func (r *Router) Mount(backend logical.Backend, prefix string, mountEntry *Mount
 	if existing, _, ok := r.root.LongestPrefix(prefix); ok && existing != "" {
 		return fmt.Errorf("cannot mount under existing mount '%s'", existing)
 	}
+	// If this is a secret backend, check to see if the prefix conflicts
+	// with an existing mountpoint
+	if prefix != "" {
```
Comment (jefferai) [inline vault/router.go]: I'm pretty sure that we don't allow empty prefixes in the API calls or core mount function. Have you seen this? This `if` seems unnecessary.

File: vault/router.go [hunk 8]
```diff
@@ -205,6 +212,39 @@ func (r *Router) MatchingMount(path string) string {
...
+func (r *Router) MatchingPrefix(path string) string {
+	r.l.RLock()
+	match := r.matchingPrefixInternal(path)
+	r.l.RUnlock()
+	return match
+}
+
+// MountConflict determines if there are potential path conflicts
+func (r *Router) MountConflict(path string) string {
+	if exact_match := r.MatchingMount(path); exact_match != "" {
```
Comment (jefferai) [inline vault/router.go]: Really this function should grab a single read lock for the entire function and then call matchingMountInternal and matchingPrefixInternal. That way nothing can change between the two functions.

**Comment by jefferai** [comment]
Regarding the `if` -- both, actually. I left a comment on the one at line 67. The other one was about the use of HasPrefix in the walking function. Wouldn't we never even hit that part of the walk function if HasPrefix wasn't true?

**Comment by otakup0pe** [comment]
Shuffled around the "internal" functions. When I removed the prefix matching code at in `Mount`, the build fails and I see a bunch of warnings/errors about audit logs (not sure why I thought policies). They might be a red herring, there is a lot of output to parse when the vault test suite fails.

```
2017/07/26 22:54:14.121014 [ERROR] audit: backend failed to log request: backend=foo error=failed
2017/07/26 22:54:14.121028 [ERROR] audit: backend failed to log request: backend=foo error=failed
2017/07/26 22:54:14.121037 [ERROR] audit: backend failed to log request: backend=bar error=failed
2017/07/26 22:54:14.121166 [ERROR] audit: backend failed to log response: backend=foo error=failed
2017/07/26 22:54:14.121178 [ERROR] audit: backend failed to log response: backend=foo error=failed
2017/07/26 22:54:14.121185 [ERROR] audit: backend failed to log response: backend=bar error=failed
2017/07/26 22:54:14.121376 [ERROR] audit: backend failed to log request: backend=foo error=failed
2017/07/26 22:54:14.121403 [ERROR] audit: backend failed to log request: backend=foo error=failed
2017/07/26 22:54:14.121430 [ERROR] audit: backend failed to log request: backend=bar error=failed
```

```
2017/07/26 22:54:14.078248 [ERROR] core: failed to create audit entry: path=noop/ error=failing enabling
2017/07/26 22:54:14.078259 [ERROR] core: failed to create audit entry: path=noop/ error=failing enabling
2017/07/26 22:54:14.078268 [ERROR] core: failed to create audit entry: path=noop2/ error=failing enabling
```

**Comment by jefferai** [comment]
@otakup0pe Your build works fine -- can you explain what you mean about "when I removed the prefix matching code in Mount"?

**Comment by jefferai** [comment]
Rather, the CI tests pass fine...so not sure what errors you're meaning.

**Comment by otakup0pe** [comment]
If I remove lines 67-71 the build will repeatedly fail locally. I left them in for the PR because it seems to be working properly based on the tests and the manual testing I did... I can push without those lines and we can see what Travis says if you'd like.

File: vault/router.go [hunk 9]
```diff
@@ -62,6 +62,13 @@ func (r *Router) Mount(backend logical.Backend, prefix string, mountEntry *Mount
 	if existing, _, ok := r.root.LongestPrefix(prefix); ok && existing != "" {
 		return fmt.Errorf("cannot mount under existing mount '%s'", existing)
 	}
+	// If this is a secret backend, check to see if the prefix conflicts
+	// with an existing mountpoint
+	if prefix != "" {
+		if match := r.matchingPrefixInternal(prefix); match != "" {
```
Comment (chrishoffman) [inline vault/router.go]: I'm a little concerned about adding this check in the router.  I've confirmed that adding this check will prevent servers that are in the situation of overlapping mounts from unsealing, where they would start fine before.  This may be ok since vault will never unseal and you can just downgrade to the earlier version, move their mounts, and then proceed with the upgrade.  It's at the very least something to not in the upgrade docs.  @jefferai thoughts?

File: vault/router.go (hunk 7 above)
Comment (chrishoffman) [inline vault/router.go]: Yes, this check appears unnecessary.

File: vault/router.go [hunk 10]
```diff
@@ -197,14 +204,48 @@ func (r *Router) MatchingMountByAccessor(mountAccessor string) *MountEntry {
...
+	}
+	r.root.WalkPrefix(path, fn)
+	return existing
+}
+
+// MountConflict determines if there are potential path conflicts
+func (r *Router) MountConflict(path string) string {
+	r.l.RLock()
+	if exact_match := r.matchingMountInternal(path); exact_match != "" {
+		r.l.RUnlock()
```
Comment (chrishoffman) [inline vault/router.go]: You should just `defer` the `RUnlock` instead of unlocking on all return paths.

**Comment by jefferai** [comment]
Note: moved to next release as it's super late in the dev cycle for 0.8 and this is a very core change, so that will give more time for review and baking the change in tests and such.

File: vault/router.go (hunk 9 above)
Comment (otakup0pe) [inline vault/router.go]: Let me know how to proceed. I can add some context on the upgrade docs, or is handling the data migration something we want to consider?

Comment (jefferai) [inline vault/router.go]: I think my preference here would be to allow it in the router but not the mount code. So existing setups will work, but it won't be allowed for new mounts.

**Comment by jefferai** [comment]
@otakup0pe Just wanted to check on on this and see if you were going to address the remaining review items.

**Comment by otakup0pe** [comment]
Hi @jefferai I was off grid for several weeks. Will pick wrap this up now that I'm back!

**Comment by otakup0pe** [comment]
I think this addresses the feedback. I adjusted the tests to account for the new pattern.

File: vault/router_test.go [hunk 11]
```diff
@@ -162,6 +167,24 @@ func TestRouter_Mount(t *testing.T) {
...
+		Path:     "prod/",
+		UUID:     meUUID,
+		Accessor: "prodaccessor",
+	}
+
+	if r.MountConflict("prod/aws/") == "" {
+		t.Fatalf("bad: prod/aws/")
+	}
+
+	err = r.Mount(n, "prod/", subMountEntry, view)
```
Comment (vishalnayak) [inline vault/router_test.go]: Can we have a comment here as to why this should pass?

File: vault/router_test.go [hunk 12]
```diff
@@ -118,6 +118,11 @@ func TestRouter_Mount(t *testing.T) {
 		t.Fatalf("err: %v", err)
 	}
 
+	meUUID, err = uuid.GenerateUUID()
```
Comment (vishalnayak) [inline vault/router_test.go]: Can we move this to be placed just above the definition of subMountEntry?

File: vault/router.go [hunk 13]
```diff
@@ -201,14 +200,46 @@ func (r *Router) MatchingMountByAccessor(mountAccessor string) *MountEntry {
 // MatchingMount returns the mount prefix that would be used for a path
 func (r *Router) MatchingMount(path string) string {
 	r.l.RLock()
-	mount, _, ok := r.root.LongestPrefix(path)
+	var mount = r.matchingMountInternal(path)
```
Comment (vishalnayak) [inline vault/router.go]: [Nitpick][Optional] We could do a `defer r.l.RUnlock()` and  `return r.matchingMountInternal(path)` and avoid the local var `mount`.
