### PR TITLE
Fix CLI namespace commands

### LINKED ISSUE #8313: CLI predict folders for namespace commands with no args
**Describe the bug**
`vault namespace create` and `vault namespace list` predict folders even though those commands expect no arguments.

**Environment:**
* Vault CLI Version (retrieve with `vault version`): Vault v1.3.2

### LINKED ISSUE #8314: CLI help text wrong for namespace commands
**Describe the bug**
`vault namespace delete` and `vault namespace lookup` have wrong help text.
https://github.com/hashicorp/vault/blob/462ef72b74aa61e7037bf45ebe4bde9c99cfb2b2/command/namespace_delete.go#L36
https://github.com/hashicorp/vault/blob/462ef72b74aa61e7037bf45ebe4bde9c99cfb2b2/command/namespace_lookup.go#L24

**Environment:**
* Vault CLI Version (retrieve with `vault version`): Vault v1.3.2

### PR DESCRIPTION
**Pull request by spangenberg**
Fixes #8314
Fixes #8313

Also, add namespace prediction capability.

### CODE REVIEW

File: command/namespace_lookup.go [hunk 1]
```diff
@@ -21,7 +21,7 @@ func (c *NamespaceLookupCommand) Synopsis() string {
 
 func (c *NamespaceLookupCommand) Help() string {
 	helpText := `
-Usage: vault namespace create [options] PATH
+Usage: vault namespace lookup [options] PATH
 
   Create a child namespace. The namespace created will be relative to the
```
Comment (catsby) [inline command/namespace_lookup.go]: I think this description should be updated to refer to `lookup` as well, correct?

Comment (spangenberg) [reply command/namespace_lookup.go]: Thanks, good catch, I addressed this.
