### PR TITLE
auth/aws: Allow wildcard in bound_iam_principal_id

### LINKED ISSUE #3179: auth/aws: support all  principal types
This is partially bug-report and partially feature-request:

Bug: The `aws` credential backend currently **panics** when given an IAM principal ending in `root` (e.g. `arn:aws:iam::111111111111:root`), despite it being a [valid](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html) IAM principal. It should return an error if this is unsupported.

FR: support this and all other principal types (currently missing `root`, `federated-user`, and `group`).

```
2017/08/13 18:08:59 http: panic serving 172.17.0.1:33966: runtime error: slice bounds out of range
goroutine 2535 [running]:
net/http.(*conn).serve.func1(0xc420d7c000)
	/goroot/src/net/http/server.go:1721 +0xd0
panic(0x17f5b00, 0x26ceb40)
	/goroot/src/runtime/panic.go:489 +0x2cf
github.com/hashicorp/vault/builtin/credential/aws.parseIamArn(0xc420644140, 0x1e, 0x0, 0xc420e1a938, 0x3b322f08)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/aws/path_login.go:1291 +0x7f5
github.com/hashicorp/vault/builtin/credential/aws.(*backend).resolveArnToRealUniqueId(0xc42088e280, 0x2683140, 0xc420d99b30, 0xc420644140, 0x1e, 0x140, 0x1a5b5c0, 0x1, 0xc420ccf900)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/aws/backend.go:194 +0x4d
github.com/hashicorp/vault/builtin/credential/aws.(*backend).(github.com/hashicorp/vault/builtin/credential/aws.resolveArnToRealUniqueId)-fm(0x2683140, 0xc420d99b30, 0xc420644140, 0x1e, 0xc4201408e0, 0x1, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/aws/backend.go:79 +0x52
github.com/hashicorp/vault/builtin/credential/aws.(*backend).pathRoleCreateUpdate(0xc42088e280, 0xc420d800e0, 0xc420140650, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/aws/path_role.go:497 +0x52e8
github.com/hashicorp/vault/builtin/credential/aws.(*backend).(github.com/hashicorp/vault/builtin/credential/aws.pathRoleCreateUpdate)-fm(0xc420d800e0, 0xc420140650, 0x0, 0x6, 0xc420dea2f8)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/aws/path_role.go:156 +0x3e
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc420def520, 0xc420d800e0, 0xc420d800e0, 0xc4209ee098, 0x19)
	/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:221 +0x4c8
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc42044d9b0, 0xc420d800e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:326 +0x636
github.com/hashicorp/vault/vault.(*Router).Route(0xc42044d9b0, 0xc420d800e0, 0xc420d800e0, 0xc4203a0ba0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:218 +0x3a
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc4201a0c00, 0xc420d800e0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:188 +0xb10
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc4201a0c00, 0xc420d800e0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:45 +0xc77
github.com/hashicorp/vault/http.request(0xc4201a0c00, 0x2681800, 0xc420d80000, 0xc4201c2100, 0xc420d800e0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:209 +0x3c
github.com/hashicorp/vault/http.handleLogical.func1(0x2681800, 0xc420d80000, 0xc4201c2100)
	/gopath/src/github.com/hashicorp/vault/http/logical.go:121 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc4203dd820, 0x2681800, 0xc420d80000, 0xc4201c2100)
	/goroot/src/net/http/server.go:1942 +0x44
github.com/hashicorp/vault/http.handleRequestForwarding.func1(0x2681800, 0xc420d80000, 0xc4201c2100)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:159 +0x1d6
net/http.HandlerFunc.ServeHTTP(0xc4203dd840, 0x2681800, 0xc420d80000, 0xc4201c2100)
	/goroot/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201e1e00, 0x2681800, 0xc420d80000, 0xc4201c2100)
	/goroot/src/net/http/server.go:2238 +0x130
github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x2681800, 0xc420d80000, 0xc4201c2100)
	/gopath/src/github.com/hashicorp/vault/http/help.go:22 +0x17f
net/http.HandlerFunc.ServeHTTP(0xc4203dd8e0, 0x2681800, 0xc420d80000, 0xc4201c2100)
	/goroot/src/net/http/server.go:1942 +0x44
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x2681800, 0xc420d80000, 0xc4201c2100)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:86 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc4203dd940, 0x2681800, 0xc420d80000, 0xc4201c2100)
	/goroot/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc42056c840, 0x2681800, 0xc420d80000, 0xc4201c2100)
	/goroot/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420d7c000, 0x2682980, 0xc42039e480)
	/goroot/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/goroot/src/net/http/server.go:2668 +0x2ce
```

### PR DESCRIPTION
**Pull request by joelthompson**
This allows specifying a trailing wildcard in the bound_iam_principal_id
in a semantically similar way to AWS. If a user specifies a
bound_iam_principal_arn with a trailing wildcard, then Vault will NOT
resolve the unqiue ID (analogous to the way AWS handles wildcards) and
instead will just store the ARN.

At login time, if a wildcard is specified in the bound ARN, Vault will
first resolve the full ARN of the authenticating principal because the
path component of roles is not visible from the GetCallerIdentity
response. A cache has been included to speed up performance of these
lookups and should be append only. To prevent unbounded growth of the
cache, old entries are cleaned up if not used within a period of time.

Also, as the complexity of scenarios of when Vault might make AWS API
calls increases, including a recommended IAM policy to give the Vault
server that can be more simply referenced in the future.

Fixes #3179

### CODE REVIEW

File: builtin/credential/aws/backend.go [hunk 1]
```diff
@@ -174,6 +181,9 @@ func (b *backend) periodicFunc(req *logical.Request) error {
 			b.tidyWhitelistIdentity(req.Storage, safety_buffer)
 		}
 
+		// get rid of old unique ID entries
+		b.cleanOldCachedUniqueIdMapping()
```
Comment (jefferai) [inline builtin/credential/aws/backend.go]: Do you see a reason to do it like this instead of using go-cache, since this is purely in-memory? I don't have a strong preference, go-cache will just do it internally and individually rather than on a schedule in a block.

Comment (jefferai) [reply builtin/credential/aws/backend.go]: This would also get rid of the need to hold a mutex to do this operation and the need to store a last-accessed time. The downside, mainly, is that updating the expiration time still requires a replace operation (but the locking is handled internally).

Comment (joelthompson) [reply builtin/credential/aws/backend.go]: Because I wasn't aware go-cache existed :) I was mainly pattern matching off of the cached AWS clients. And hopefully patrickmn/go-cache#66 will get merged to make it easier to update the expiration time.

I'll work on moving to go-cache and push a new commit when ready.

Comment (joelthompson) [reply builtin/credential/aws/backend.go]: Done!

File: builtin/credential/aws/path_login.go [hunk 2]
```diff
@@ -928,6 +928,12 @@ func (b *backend) pathLoginRenewIam(
 		}
 	}
 
+	// Note that the error messages below can leak a little bit of information about the role information
+	// For example, if on renew, the client gets the "error parsing ARN..." error message, the client
+	// will konw that it's a wildcard bind (but not the actual bind), even if the client can't actually
```
Comment (vishalnayak) [inline builtin/credential/aws/path_login.go]: s/konw/know

**Comment by jefferai** [comment]
Brilliant work as always, @joelthompson !

**Comment by joelthompson** [comment]
Thanks @jefferai! And also for the silly typo fix :)
