### PR TITLE
Fix #461 properly by defering potential revocation of a token until a…

### LINKED ISSUE #461: Token lookup-self does not modify use count
When calling `lookup-self` on a token, the number of remaining token uses is not decremented. Unfortunately, this leads to problems implementing various kinds of authentication workflows, as you cannot have a token expire after its metadata is accessed.

I've discussed at length with @armon who considers this a bug (as I do). However, looking at the code, it seems that the reason that it's marked as an unauthenticated path is so that immediately after the token is generated, it can perform a lookup-self to do two things: 1) verify that the token is properly stored and available; 2) indicate the roles available to the token on the output.

After digging into the code, I don't see a good way around these problems. Hacks like incrementing the use count internally by one before performing `lookup-self` have really ugly use cases.

Here's a small diff with changes that fix the problem and keep the unit tests working, but it does this by dropping the functionality of printing the roles, and by removing the test checking for validity; at this point Vault is mature enough that that test is probably not truly needed.

I can turn this into a merge request but would like feedback on the changes first. There may be a better way to deal with this bug.
```go
diff --git a/command/auth.go b/command/auth.go
index e42c05c..2370b8e 100644
--- a/command/auth.go
+++ b/command/auth.go
@@ -170,33 +170,7 @@ func (c *AuthCommand) Run(args []string) int {
 		return 1
 	}

-	// Verify the token
-	secret, err := client.Logical().Read("auth/token/lookup-self")
-	if err != nil {
-		c.Ui.Error(fmt.Sprintf(
-			"Error validating token: %s", err))
-		return 1
-	}
-	if secret == nil {
-		c.Ui.Error(fmt.Sprintf("Error: Invalid token"))
-		return 1
-	}
-
-	// Get the policies we have
-	policiesRaw, ok := secret.Data["policies"]
-	if !ok {
-		policiesRaw = []string{"unknown"}
-	}
-	var policies []string
-	for _, v := range policiesRaw.([]interface{}) {
-		policies = append(policies, v.(string))
-	}
-
-	c.Ui.Output(fmt.Sprintf(
-		"Successfully authenticated! The policies that are associated\n"+
-			"with this token are listed below:\n\n%s",
-		strings.Join(policies, ", "),
-	))
+	c.Ui.Output(fmt.Sprint("Successfully authenticated!"))

 	return 0
 }
diff --git a/command/auth_test.go b/command/auth_test.go
index 563d400..4d7ee63 100644
--- a/command/auth_test.go
+++ b/command/auth_test.go
@@ -113,29 +113,6 @@ func TestAuth_stdin(t *testing.T) {
 	}
 }

-func TestAuth_badToken(t *testing.T) {
-	core, _, _ := vault.TestCoreUnsealed(t)
-	ln, addr := http.TestServer(t, core)
-	defer ln.Close()
-
-	testAuthInit(t)
-
-	ui := new(cli.MockUi)
-	c := &AuthCommand{
-		Meta: Meta{
-			Ui: ui,
-		},
-	}
-
-	args := []string{
-		"-address", addr,
-		"not-a-valid-token",
-	}
-	if code := c.Run(args); code != 1 {
-		t.Fatalf("bad: %d\n\n%s", code, ui.ErrorWriter.String())
-	}
-}
-
 func TestAuth_method(t *testing.T) {
 	core, _, token := vault.TestCoreUnsealed(t)
 	ln, addr := http.TestServer(t, core)
diff --git a/vault/token_store.go b/vault/token_store.go
index d1b971c..f27f545 100644
--- a/vault/token_store.go
+++ b/vault/token_store.go
@@ -75,10 +75,6 @@ func NewTokenStore(c *Core) (*TokenStore, error) {
 			Root: []string{
 				"revoke-prefix/*",
 			},
-
-			Unauthenticated: []string{
-				"lookup-self",
-			},
 		},

 		Paths: []*framework.Path{
```

### PR DESCRIPTION
**Pull request by jefferai**
…fter the request is fully handled.

### CODE REVIEW

File: vault/core.go [hunk 1]
```diff
@@ -400,11 +400,20 @@ func (c *Core) HandleRequest(req *logical.Request) (resp *logical.Response, err
...
 
 	// Validate the token
-	auth, err := c.checkToken(req.Operation, req.Path, req.ClientToken)
+	auth, te, err := c.checkToken(req.Operation, req.Path, req.ClientToken)
+	if te != nil {
+		defer func() {
+			// Attempt to use the token (decrement num_uses)
+			if err := c.tokenStore.UseToken(te); err != nil {
+				c.logger.Printf("[ERR] core: failed to use token: %v", err)
+				retErr = ErrInternalError
```
Comment (armon) [inline vault/core.go]: we should change the `retResp` as well, so nothing leaks from core.
