### PR TITLE
Check ec2 instance metadata for region

### LINKED ISSUE #6016: awskms unseal: Region cannot be detected from instance profile as docs describe
**Describe the bug**
The `region` parameter for the `awskms` seal type is documented as follow:
> The AWS region where the encryption key lives. May also be specified by the AWS_REGION or AWS_DEFAULT_REGION environment variable or as part of the AWS profile from the AWS CLI or instance profile.

https://www.vaultproject.io/docs/configuration/seal/awskms.html

This suggests that _not_ configuring the AWS region is possible and Vault should detect the region from the instance profile, like it is able to do with the secret/access key. In reality, Vault (v1.0.1) does not do this and must be configured using the config parameter or an environment variable. (When I did specify the `region` parameter things worked).

I think Vault should be updated to use the region from the instance profile/metadata or the documentation should be changed. This seems to be the relevant code:
https://github.com/hashicorp/vault/blob/9af595ec61e5f7f435722ff19c811307f23ccc80/vault/seal/awskms/awskms.go#L90-L101

**To Reproduce**
1. Set up an instance profile for an EC2 instance with an instance profile and associated role that allows access to the KMS key that will be used for auto unseal. Do this in a region that is not the default (not `us-east-1`).
2. Configure the Vault server on the instance with the `awskms` seal type. Don't specify the region.
3. Start Vault and observe that Vault fails to start because it uses the default region `us-east-1` instead of reading the region from the instance profile.

**Expected behavior**
The correct AWS region should be detected from the EC2 instance profile.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.1
* Vault CLI Version (retrieve with `vault version`): 1.0.1
* Server Operating System/Architecture: Debian Linux

Vault server configuration file(s):
Relevant config JSON:
```json
{
  "seal": {
    "awskms": {
      "kms_key_id": "<key-id>"
    }
}
```

**Additional context**
Recent PR that seems somewhat related: #5974

### PR DESCRIPTION
**Pull request by tyrannosaurus-becks**
Closes #6016. I used a t2.nano instance to verify that this approach works IRL.

### CODE REVIEW

File: vault/seal/awskms/awskms.go [hunk 1]
```diff
@@ -98,6 +99,21 @@ func (k *AWSKMSSeal) SetConfig(config map[string]string) (map[string]string, err
 		k.region = region
 	default:
```
Comment (catsby) [inline vault/seal/awskms/awskms.go]: Could we just remove this `default:` case? It seems to me that if the user does not specify the region in the config, and there is no ENV vars that cover it, then we'd be in the case of "detect this for me". Instead we set it a default of `us-east-1` for no clear reason to me. 

Omitting this default should allow the [credsConfig.GenerateCredentialChain SDK call in `getAWSKMSClient`](https://github.com/hashicorp/vault/blob/master/vault/seal/awskms/awskms.go#L280) to do it's magic and set the region automatically from the instance. By providing a default, we prevent that:

https://github.com/hashicorp/vault/blob/ea8dacf583b0a50cc347e07669345f5739b60292/helper/awsutil/generate_credentials.go#L66-L70

Comment (catsby) [reply vault/seal/awskms/awskms.go]: OK, I see my error, I misread and got confused on where the GenerateCredentialChain was checking the ENV vars, in hindsight very silly 😄

Comment (tyrannosaurus-becks) [reply vault/seal/awskms/awskms.go]: No worries, I took the exact same thought path! Thanks for looking at this PR!
