### PR TITLE
Don't read AWS env vars

### LINKED ISSUE #5965: awskms unseal: UnrecognizedClientException: The security token included in the request is invalid.
**Describe the bug**
Vault does not consume the AWS_SESSION_TOKEN environmental variable used to pass credentials to the awskms autounseal logic.

When using temporary AWS credentials provided in the environment to perform awskms unsealing, Vault fails with:

```
Error parsing Seal configuration: error fetching AWS KMS sealkey information: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: REDACTED
```

https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html describes the three variables that may need to be consumed:
```
$ export AWS_ACCESS_KEY_ID=YOUR_AKID
$ export AWS_SECRET_ACCESS_KEY=YOUR_SECRET_KEY
$ export AWS_SESSION_TOKEN=TOKEN
```

https://github.com/hashicorp/vault/blob/e883087713c81106cc2b5b0a99f26197986fb038/vault/seal/awskms/awskms.go#L103 shows it is only consuming the access and secret key, instead of additionally checking for the session token. 

I'm able to utilize the awscli with the same set of variables so I am confident my credentials are correctly set.

**Expected behavior**
Temporary credentials may be passed in via the environment. This is useful when testing Vault on a desktop and using federated SAML-based logins to AWS.

**Environment:**
Vault v1.0.0 ('c19cef14891751a23eaa9b41fd456d1f99e7e856')
Darwin xxx 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Variables:
```
VAULT_SEAL_TYPE=awskms
AWS_SESSION_TOKEN=REDACTED
AWS_ACCESS_KEY_ID=REDACTED
AWS_SECRET_ACCESS_KEY=REDACTED
VAULT_AWSKMS_SEAL_KEY_ID=REDACTED
```

Vault server configuration file(s):
```hcl
ui = true

storage "file" {
  path = "/some/path/vault.dat"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  cluster_address     = "0.0.0.0:8201"

  tls_disable = 1
}
```

### PR DESCRIPTION
**Pull request by jefferai**
Let AWS SDK env cred chain provider do it for us

Fixes #5965

### CODE REVIEW

File: vault/seal/awskms/awskms.go [hunk 1]
```diff
@@ -99,19 +99,16 @@ func (k *AWSKMSSeal) SetConfig(config map[string]string) (map[string]string, err
...
 	}
 
-	// Check and set AWS access key and secret key
-	k.accessKey = os.Getenv("AWS_ACCESS_KEY_ID")
-	if k.accessKey == "" {
-		if accessKey, ok := config["access_key"]; ok {
-			k.accessKey = accessKey
-		}
+	// Check and set AWS access key, secret key, and session token
+	var accessKey, secretKey, sessionToken string
```
Comment (tyrannosaurus-becks) [inline vault/seal/awskms/awskms.go]: My code editor complains that these aren't actually read below.

File: vault/seal/awskms/awskms.go [hunk 2]
```diff
@@ -99,19 +99,16 @@ func (k *AWSKMSSeal) SetConfig(config map[string]string) (map[string]string, err
...
+	if os.Getenv("AWS_ACCESS_KEY_ID") == "" {
```
Comment (tyrannosaurus-becks) [inline vault/seal/awskms/awskms.go]: I think that since we use `credsConfig.GenerateCredentialChain()` below, and that includes adding an Env cred provider if the AWS key is unset, we can just do away with all fussing with pulling AWS environment variables here and let the Env provider do the right thing.

Comment (tyrannosaurus-becks) [reply vault/seal/awskms/awskms.go]: Looks like the Env provider supports pulling specifically the access key, secret key, and session token, but nothing else.

File: physical/dynamodb/dynamodb.go [hunk 3]
```diff
@@ -155,16 +155,14 @@ func NewDynamoDBBackend(conf map[string]string, logger log.Logger) (physical.Bac
...
 		accessKey = conf["access_key"]
 	}
-	secretKey := os.Getenv("AWS_SECRET_ACCESS_KEY")
-	if secretKey == "" {
+	if os.Getenv("AWS_SECRET_ACCESS_KEY") == "" {
 		secretKey = conf["secret_key"]
 	}
-	sessionToken := os.Getenv("AWS_SESSION_TOKEN")
-	if sessionToken == "" {
+	if os.Getenv("AWS_SESSION_TOKEN") == "" {
```
Comment (tyrannosaurus-becks) [inline physical/dynamodb/dynamodb.go]: We should just drop pulling all three of these here.

File: vault/seal/awskms/awskms.go (hunk 1 above)
Comment (jhmartin) [reply vault/seal/awskms/awskms.go]: Fails to `make` for me with:
```
Stderr: # github.com/hashicorp/vault/vault/seal/awskms
../../../../../GO/src/github.com/hashicorp/vault/vault/seal/awskms/awskms.go:103:6: accessKey declared and not used
../../../../../GO/src/github.com/hashicorp/vault/vault/seal/awskms/awskms.go:103:17: secretKey declared and not used
../../../../../GO/src/github.com/hashicorp/vault/vault/seal/awskms/awskms.go:103:28: sessionToken declared and not used```

File: physical/dynamodb/dynamodb.go (hunk 3 above)
Comment (jefferai) [reply physical/dynamodb/dynamodb.go]: The point of keeping it there was so that if you overrode the config with env vars we'd prioritize the env vars -- note that awsutil has the ordering static, env, shared, iam. Whether this is the right thing to do or not is debatable, but it's also how it's worked up to this point so I'm not sure changing them is the right move.

File: vault/seal/awskms/awskms.go (hunk 1 above)
Comment (jefferai) [reply vault/seal/awskms/awskms.go]: Fixed

File: physical/dynamodb/dynamodb.go (hunk 3 above)
Comment (tyrannosaurus-becks) [reply physical/dynamodb/dynamodb.go]: Oh I see! Maybe it would be nice to add a comment to that effect, then. But yes, I looked through the code in `GenerateCredentialChain` and I see why you're doing that but still using the method, that method does a lot of work.
