### PR TITLE
Fix consul token revocation with namespace specific policies

### LINKED ISSUE #22895: Vault fails to delete Consul tokens created by a role that has a namespace set
**Describe the bug**
Vault fails to delete Consul tokens that are created by a role that has a namespace set. It appears to use the namespace of the secrets engine, rather than the namespace of the token that it is attempting to delete. This will only affect scenarios where the secrets engine token is [not created in the same namespace that the tokens it issues are in](https://developer.hashicorp.com/consul/commands/acl/token/delete#namespace).

**To Reproduce**
1. Create a Consul secrets engine, ensuring it is configured with the "default" Consul namespace but with an ACL policy that grants `acl: write` in namespace "B".
2. Create a Consul credentials role, specify a Consul namespace of "B"
3. vault read consul/creds/the-role-created-in-step-2 -- the token is issued correctly
4. Observe that once the TTL is reached, Vault fails to delete the token from Consul.
    ```
    Request error: method=DELETE url=/v1/acl/token/xxx-192f5a from=x.x.x.x:61490 error="rpc error making call: Permission denied: token with AccessorID 'xxx502b5' lacks permission 'acl:write'"
    ```

**Expected behavior**
Vault should successfully delete the token from Consul. My guess is that it is [not specifying the correct Consul namespace when attempting the delete](https://github.com/hashicorp/vault/blob/55a901d423ffa4fbbbdabbf7cae877fe197b345e/builtin/logical/consul/secret_token.go#L95).

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.0+ent
* Vault CLI Version (retrieve with `vault version`): 1.13.0
* Server Operating System/Architecture: RHEL/x86-64

**Additional context**
Consul version: v1.16.1+ent

The secrets engine and role are provisioned with Terraform, see:
<details>
  <summary>Secrets engine</summary>
  
```hcl
# Consul / Namespaces #########################################################

resource "consul_namespace" "default" {
  for_each = var.environments
  name     = format(local.namespace_name_format, var.name, each.key)
}

# Consul / Secrets engine #####################################################

resource "consul_acl_policy" "vault_secrets_engine" {
  # brevity: a policy that contains only:
  # namespace_prefix "xyz-" {
  #   acl = "write"
  # }
}

resource "consul_acl_token" "vault_secrets_engine" {
  description = "vault/${var.name} (secrets engine)"
  namespace   = "default"
  local       = false
  policies    = [consul_acl_policy.vault_secrets_engine.name]
}

data "consul_acl_token_secret_id" "vault_secrets_engine" {
  accessor_id = consul_acl_token.vault_secrets_engine.id
}

resource "vault_consul_secret_backend" "default" {
  namespace   = var.name
  path        = "consul"
  description = "platform/consul"
  address     = "https://my.consul.server"
  token       = data.consul_acl_token_secret_id.vault_secrets_engine.secret_id
}

```
</details>

<details>
<summary>Secret backend role</summary>

```hcl
resource "consul_acl_policy" "app_deploy" {
  # brevity: a policy that allows service write and KV permissions for an app
}

resource "vault_consul_secret_backend_role" "app_deploy" {
  for_each = local.namespace_environments

  consul_namespace = "${var.namespace}-${each.key}"
  
  name     = "app-deploy-${var.namespace}-${each.key}-${local.safe_app_name}"
  backend  = "consul"
  policies = [consul_acl_policy.app_deploy[each.key].name]
  ttl      = 300
  max_ttl  = 300
}
```
</details>

### PR DESCRIPTION
**Pull request by davidadeleon**
This PR fixes a problem with the Consul Secrets engine where tokens generated in specific Consul namespaces were unable to be revoked if the token provided to Vault to be used for management had namespace specific policies.

Closes #22895

### CODE REVIEW

File: builtin/logical/consul/secret_token.go [hunk 1]
```diff
@@ -84,6 +85,17 @@ func (b *backend) secretTokenRevoke(ctx context.Context, req *logical.Request, d
...
+	// Extract Consul Namespace info from secret
+	var namespace string
+	namespaceRaw, ok := req.Data["consul_namespace"]
+	if ok {
+		namespace = namespaceRaw.(string)
+	}
+
+	revokeWriteOptions := &api.WriteOptions{
+		Namespace: namespace,
+	}
```
[the remark this answers is not in the document]
Comment (calvn) [reply builtin/logical/consul/secret_token.go:97]: Was thinking the same, +1 to this so that the revocation falls back to the secret engine's namespace if none is found on the token.

[the remark this answers is not in the document]
Comment (davidadeleon) [reply builtin/logical/consul/secret_token.go]: The original behavior was to pass nil for the WriteOptions. I made the change to have it be the same as it was if no namespace is found as part of the secret.

File: builtin/logical/consul/secret_token.go [hunk 2]
```diff
@@ -84,6 +85,16 @@ func (b *backend) secretTokenRevoke(ctx context.Context, req *logical.Request, d
...
 	}
 
+	// Extract Consul Namespace info from secret
+	var revokeWriteOptions *api.WriteOptions
+	namespaceRaw, ok := req.Data["consul_namespace"]
+	if ok {
+		namespace := namespaceRaw.(string)
+		revokeWriteOptions = &api.WriteOptions{
+			Namespace: namespace,
+		}
```
Comment (robmonte) [inline builtin/logical/consul/secret_token.go:95]: Hi David, thanks for catching this oversight!

Actually I believe this check is unnecessary. Unless I am mistaken, Consul never has an unnamed namespace to return because the default one is literally named "default". So this `ok` should always evaluate to true.

Also it turns out admin partitions have the exact same bug. I'm happy to make these changes myself if you don't mind me pushing to your branch?

File: builtin/logical/consul/backend_test.go [hunk 3]
```diff
@@ -857,6 +857,14 @@ func TestBackend_Enterprise_Namespace(t *testing.T) {
 	testBackendEntNamespace(t)
 }
 
+func TestBackend_Enterprise_Diff_Namespace_Revocation(t *testing.T) {
+	if _, hasLicense := os.LookupEnv("CONSUL_LICENSE"); !hasLicense {
```
Comment (robmonte) [inline builtin/logical/consul/backend_test.go:861]: Great test addition!

File: builtin/logical/consul/secret_token.go (hunk 2 above)
Comment (davidadeleon) [reply builtin/logical/consul/secret_token.go:95]: This check is to see if we had a consul namespace set in the secret itself in Vault. After some testing, it looks like in the case of not having a namespace set in the backend config, or the role config, namespace will return as an empty string so this can evaluate to false. I originally was just passing this WriteOptions struct along with the request even if there wasn't a namespace set as Consul seems to handle that case well, but I wanted to default to the original behavior here.

Comment (robmonte) [reply builtin/logical/consul/secret_token.go:95]: @davidadeleon I'm not seeing this behavior, am I maybe testing this the wrong way? If I remember correctly, when a token is created the namespace and partition are returned from Consul and set on the secret [here](https://github.com/hashicorp/vault/blob/eb03ef7d0e0d9ab6f8f88d613c0f1cb258f418e4/builtin/logical/consul/path_token.go#L139) which should be the "default" value if never set in Vault. It seems to be behaving this way in my testing.

Can you add debug output to confirm the values of `req.Data["consul_namespace"]` and `req.Data["partition"]` are empty strings since I'm unable to recreate it?

Comment (robmonte) [reply builtin/logical/consul/secret_token.go]: With Kyle's help I believe we discovered the discrepancy. When using Consul enterprise unset namespace and partition fields are indeed set to default, however free versions of Consul are set to empty strings.

In fact, due to this, the `ok` still always evaluates to true like I thought, but not exactly for the reason I stated. It is still "set" to `""` and the `ok` check passes, so I've committed my changed.

**Review by kschoche — APPROVED** [review]
LGTM!
