### PR TITLE
Remove agent reauthentication on new credentials.

### LINKED ISSUE #5522: aws auth.handler constant regeneration of tokens
I've used the vault auth agent successfully prior to 0.11.2, ever since 0.11.2 the sinks keep getting renewed , which eventually causes a problem cascading down from the other tokens its handling (consul ACL).

**To Reproduce**
1. vault  write auth/aws/role/XXXX auth_type=iam bound_iam_principal_arn=arn:aws:iam::xxxx:role/xxxx-tools@us-west-2.xxxx policies=xxxx max_ttl=500h period=24h
2. Run vault agent with like:
pid_file = "/opt/vault/vault_pid"

```
auto_auth {
        method "aws" {
                config = {
                        type = "iam"
                        role = "XXXX"
                }
        }
        sink "file" {
                config = {
                        path = "/dev/shm/.vault-token"
                }
        }
}
```

3. Vault keeps getting 
```auth.handler: auth method found new credentials, re-authenticating```

Every ten minutes or so.
**Expected behavior**
On prior to 0.11.2, those tokens stay getting renewed properly:

```
Key                  Value
---                  -----
accessor             xxxx-xxx-xxxx-xxxx-xxxx
creation_time        1538081493
creation_ttl         24h
display_name         aws-ssss-tools@us-west-2.xxxx
entity_id            xxxx-xxx-xxxx-xxxx-xxxx
expire_time          2018-10-16T19:04:21.886225588Z
explicit_max_ttl     0s
id                   xxxx-xxx-xxxx-xxxx-xxxx
issue_time           2018-09-27T20:51:33.281613732Z
last_renewal         2018-10-15T19:04:21.886225723Z
last_renewal_time    1539630261
meta                 map[inferred_aws_region: inferred_entity_id: inferred_entity_type: account_id:xxxxauth_type:iam canonical_arn:arn:aws:iam::xxxxx:role/shxxxxmoop-tools@us-west-2.xxxx client_arn:arn:aws:sts::xxxxx:assumed-role/xxxxx-tools@us-west-2.xxxxx/i-0xxxxxxb client_user_id:xxxxxx]
num_uses             0
orphan               true
path                 auth/aws/login
policies             [default hive]
renewable            true
ttl                  22h28m38s

```

Now they just keep getting regenerated somehow:

```
issue_time           2018-10-15T23:36:24.627894613Z
last_renewal         2018-10-15T23:36:24.67803671Z
last_renewal_time    1539646584
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): Version         0.11.3

* Vault CLI Version (retrieve with `vault version`): Version         0.11.3
* Server Operating System/Architecture: Kernel Version: 4.18.9-coreos
Operating System: Container Linux by CoreOS 1911.0.2 (Rhyolite)
OSType: linux
Architecture: x86_64

Vault server configuration file(s):

```hcl
storage "consul" {
  address = "unix:///opt/consul/.consul.http.sock"
  path    = "vault"
}

listener "tcp" {
  address     = "{{env "attr.unique.platform.aws.local-ipv4"}}:8200"
  tls_cert_file = "/opt/ssl/combined_ssl.pem"
  tls_key_file = "/opt/ssl/private_key.pem"
  tls_disable_client_certs = "true"
}
api_addr = "https://{{env "attr.unique.platform.aws.public-ipv4"}}:8200"
cluster_addr = "https://{{env "attr.unique.platform.aws.public-ipv4"}}:8201"
max_lease_ttl = "120000h"
```

**Additional context**
Works just fine prior to 0.11.2

### PR DESCRIPTION
**Pull request by jefferai**
Functionality is left in for use in testing (where it is indeed quite
useful).

Fixes #5522

### CODE REVIEW

File: command/agent/auth/auth.go [hunk 1]
```diff
@@ -77,6 +80,21 @@ func (ah *AuthHandler) Run(ctx context.Context, am AuthMethod) {
...
+					case <-ctx.Done():
+						return
+					case <-realCredCh:
+					}
+				}
+			}()
+		}
+	}
 	if credCh == nil {
 		credCh = make(chan struct{})
```
Comment (kalafut) [inline command/agent/auth/auth.go]: Is this needed?

Comment (jefferai) [reply command/agent/auth/auth.go]: Can you be more specific? Is which part needed?

Comment (kalafut) [reply command/agent/auth/auth.go]: Checking `credCh` for nil and assigning a new channel if it is nil. The nil channel will block, so I think the behavior is the same without this `if` block, right?

**Comment by jefferai** [comment]
It's the code that was there before. It's possible it's not necessary, I just didn't change it here. If select on a nil channel is valid and blocks it's probably not needed, I just don't remember nil channel semantics.
