### PR TITLE
CLI Enhancements

### LINKED ISSUE #3869: Argument handling in shell scripts broken by ANSI escape sequences in colorized output
Argument handling from shell scripts (i.e. stdin not tty 🤣) seems to be broken in the new CLI. In this case, `vault operator unseal` is not accepting a key as an arg from within the included simple shell script, but accepts it as expected from a shell in a terminal.

**Environment:**

CLI: Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')
Server: 0.9.3
Linux amd64

**Vault Config File:**

N/A

**Startup Log Output:**

N/A

**Expected Behavior:**

`vault operator unseal` executed within my shell script should accept a variable and use it as an argument to the command.

**Actual Behavior:**

```
Error unsealing: Error making API request.

URL: PUT http://localhost:8200/v1/sys/unseal
Code: 400. Errors:

* 'key' must be a valid hex or base64 string
```

**Steps to Reproduce:**

Use this shell script:

```
#!/bin/sh

vault version

vault operator init > vault.tmp

cat vault.tmp

vault status

K1=$(sed '2q;d' vault.tmp | awk '{print $NF}')

echo "Got unseal key $K1"

vault operator unseal "$K1"
```

Initially, I suspected quoting, but this script worked before upgrading to 0.9.2; it makes no difference whether `"$K1"` is quoted or not in the `vault operator unseal` command.

**Important Factoids:**

N/A

**References:**

N/A

### PR DESCRIPTION
**Pull request by calvn**
- [x] Automatically disable colored UI if stdout no a tty
- [x] Add `-no-color` flag to all leaf subcommands ~(caveat: Warnings printed by DeprecatedCommand is always colored, since flags gets parsed afterwards)~
- [x] Add `-format` to all applicable subcommands
- [x] ~Ignore warnings and return _only_ structured responses for non-table outputs (toggleable).~ (This is not done since the current behavior for existing commands that supports formatted output do print warnings; e.g. token_renew.go).

Fixes #3869 
Closes #3914

### CODE REVIEW

**Comment by calvn** [comment]
/cc @sethvargo, it'd be great to get your feedback on this :)

This PR mainly aims to address two main points:
 - Ability to automatically detect and disable colored UI in a non-tty environment, with the option to disable globally as well.
- Add `-format` option to all commands that returns any sort of non-error output from the client API. The bulk of the formatting logic/changes is in format.go, and commands simply use that helper function to print desired formatted output.

**Comment by sethvargo** [comment]
Hey @calvn 

Thank you for the ping. This looks really good, but I do have a few comments.

- It's worth noting that with "raw", we specifically do _not_ use the CLI and just [output to the underlying `io.Writer` in whatever CLI is given](https://github.com/hashicorp/vault/blob/b020d310e4d4fcaedd0bff9bed6397fa261fbc21/command/util.go#L98-L129). Would it be possible to extend that further and just feed all the output functions through that?

- The repeated `if c.flagNoColor` scares me a bit. It seems like we might be able to centralize that in the base command (untested) or at least a shared helper. Alternatively, we could create our own UI that just wraps ColoredUI and does the `terminal.IsTerminal` check on `Write` calls. (I think this would work really well and would always ensure that we don't include colors when piping). If you want some guidance on how this might look, feel free to ping me - happy to talk though it or sketch it out.

- Having a CLI flag to disable color seems like more hassle than it's worth IMO. If we solve the "pipe" problem like mentioned above and give folks an envvar to disable globally, I think that covers most use cases. The challenge (as you've identified) with a CLI flag is that the CLI and UI are tightly coupled. If we just make it an envvar (not a CLI option), the code becomes a lot simpler and solves for that 1% use case that isn't covered by TTY and raw.

File: command/main.go [hunk 1]
```diff
@@ -23,6 +23,10 @@ func Run(args []string) int {
 			args = []string{"version"}
 			break
 		}
+
+		if arg == "-no-color" {
+			os.Setenv("VAULT_OUTPUT_NO_COLOR", "true")
```
Comment (jefferai) [inline command/main.go]: I think VAULT_CLI_NO_COLOR would be better here

**Comment by calvn** [comment]
@sethvargo thanks for taking a look! I think I've got a path forward with points 2 and 3, as we will probably end up removing the `no-color` flag in `BaseCommand` and use env-var at a higher level (probably in `command.go`'s `init()` func) to toggle (which will determine what kind of UI to use).

I am still unclear on the first point though, and why we'd need to feed the output functions through `PrintRaw`.

File: command/main.go (hunk 1 above)
Comment (calvn) [reply command/main.go]: Going to remove this flag entirely. If we do the os.Getenv logic check on command.go's `init()` func as discussed, the envvar will be read before this gets applied.

Optionally, we could keep this if we change `init()` to a func that needs to be called explicitly (and call it after the args have been parsed) in main.go's `Run()`.

**Comment by sethvargo** [comment]
Hey @calvn 

Sorry - I'm not suggesting we need to use `PrintRaw` - I was just showcasing an example of how we can:

1. Detect if there's a TTY
2. Grab the underlying `io.Writer` out of a CLI object and write directly to it

**Comment by calvn** [comment]
Ahh, I see. I am using a pretty much the same logic to detect whether there's a TTY, but instead of grabbing the `io.Writter`, it's used to determine whether we need to wrap the UI around `ColoredUI`. 

https://github.com/hashicorp/vault/blob/8f2a229abce992142d1c7334b98f4e2c1dd16141/command/commands.go#L126-L138

**Comment by sethvargo** [comment]
Yea, so the problem is that, even if you don't use color, you'll still include a newline at the end of the line if piping to another process with the non-colored UI. The only way to avoid that is to use the underlying `io.Writer` object. I was envisioning just making our own like this:

```go
type VaultUI struct {
  cli.ColoredUi
}

func (u *VaultUI) Output(m string) {
  terminal.IsTerminal(int(os.Stdout.Fd())) {
    c.ColoredUi.Output(m)
  } else {
    getWriter(c).Write(m)
  }
}
```

Then we just basically never think about it. We instantiate exactly 1 type of CLI, and that CLI decides, based on each output, whether there's a TTY present and "does the right thing". We could add the envvar logic in there too. If we want to be efficient, we could use an initializer and parse the envvar and tty check once and cache it on the struct.

**Comment by calvn** [comment]
Ah, I see what you mean, but I don't think that the additional newline would be an issue here as the intention for the no-color option was to avoid having ANSI color escape sequences specifically. 

I think for most cases people still end up using `awk`, `jq`, or similar in their scripts to filter out values from the output before using any values. For instance, a script to get the unseal keys from `vault operator init` command would go through `awk` (or if `-format=json` is provided, `jq`), before the values are used, so having an extra newline in there wouldn't matter. In the cases where people might pipe directly, (e.g. `operator generate-root`), `PrintRaw` is already being used to output to the writer directly.

Jeff suggested that in the future we may add a `-format=raw` option that would output response as it would appear from curl, and in that case it would definitely make sense to use the underlying `io.Writer`. Maybe @jefferai could chime in on this.

File: command/format.go [hunk 2]
```diff
@@ -87,19 +113,30 @@ type TableFormatter struct {
...
 
-func (t TableFormatter) OutputList(ui cli.Ui, secret *api.Secret, list []interface{}) error {
+func (t TableFormatter) OutputList(ui cli.Ui, secret *api.Secret, data interface{}) error {
 	t.printWarnings(ui, secret)
 
+	switch data.(type) {
+	case []interface{}:
+	case []string:
+		ui.Output(tableOutput(data.([]string), nil))
+		return nil
```
Comment (vishalnayak) [inline command/format.go]: Can we add a `default` case returning an error here quoting that its an unknown type? This avoids panic when the data is actually cast to `[]interface{}` below.

File: command/format.go [hunk 3]
```diff
@@ -19,29 +19,55 @@ const (
...
-	// sequences for outputting json, etc.
-	colorUI, ok := ui.(*cli.ColoredUi)
-	if ok {
-		ui = colorUI.Ui
+// OutputWithFormat supports printing arbitrary data under a specified format.
+func OutputWithFormat(ui cli.Ui, format string, data interface{}) int {
+	switch data.(type) {
+	case *api.Secret:
+		secret := data.(*api.Secret)
+		// Best-guess effort that is this a list, so parse out the keys
```
Comment (jefferai) [inline command/format.go]: What's the reason for doing this? There could very well be "keys" coming back from various different backends, including k/v.

Comment (calvn) [reply command/format.go]: Right, so in that case you output things that are inside `secret.Data[“keys”]`

Comment (calvn) [reply command/format.go]: `OutputWithFormat` is basically the combined functionality of `OutputSecret` and `OutputList`

Comment (jefferai) [reply command/format.go]: > Right, so in that case you output things that are inside secret.Data[“keys”]

But....why?  :-)

Comment (calvn) [reply command/format.go]: This is the original OutputList behavior: https://github.com/hashicorp/vault/pull/3897/files#diff-3e4377911a05a6f261016d1d5e1fec91L27

If you just passed in the `secret`, listing keys would be not formatted correctly:
```
Key                 Value
---                 -----
keys               [foo]
```

Instead of: 
```
$ vault list secret/
Keys
----
foo
```

File: command/format.go (hunk 2 above)
Comment (calvn) [reply command/format.go]: Done below.

File: command/base.go [hunk 4]
```diff
@@ -40,8 +40,9 @@ type BaseCommand struct {
 	flagTLSSkipVerify bool
 	flagWrapTTL       time.Duration
 
-	flagFormat string
-	flagField  string
+	flagFormat  string
+	flagField   string
+	flagNoColor bool
```
Comment (sethvargo) [inline command/base.go]: I think we can remove this and the var below if we are just using the envvar

File: command/format.go [hunk 5]
```diff
@@ -58,6 +67,14 @@ var Formatters = map[string]Formatter{
 	"yml":   YamlFormatter{},
 }
 
+func Format() string {
+	format := os.Getenv(EnvVaultFormat)
```
Comment (sethvargo) [inline command/format.go]: Could we retrieve this as part of an init function instead of doing the envvar lookup each time?

File: command/main.go [hunk 6]
```diff
@@ -23,8 +47,85 @@ func Run(args []string) int {
 			args = []string{"version"}
 			break
 		}
+
+		if arg == "-no-color" {
```
Comment (sethvargo) [inline command/main.go]: UX-ey thing. We should be nice and add `|| arg == "-nocolor"`. Even if we never advertise that, people will forget the dash and "auto-correcting them" will be a nice UX.

File: command/base.go (hunk 4 above)
Comment (jefferai) [reply command/base.go]: The idea was to allow it in a flag but not advertise it. Now that you mention autocorrect below, I wonder if it's better to just remove it rather than have people get it autocorrected and then complain that it's not documented. What do you think?

File: command/format.go (hunk 5 above)
Comment (jefferai) [reply command/format.go]: We just got away from init functions in favor of being able to intercept the args earlier in the main run function. This isn't going to be meaningfully slow for interactive uses, is there a reason not to just call this a couple of times?

File: command/base.go (hunk 4 above)
Comment (sethvargo) [reply command/base.go]: I think the code will be a lot simpler if we drop the flag entirely. People are more likely to "never want colored output" that "not want colored output for this specific command", and even in the latter case, they can specify the envvar first.

File: command/format.go (hunk 5 above)
Comment (sethvargo) [reply command/format.go]: I've experienced `Getenv` being slow (in relative terms), particularly on Windows systems. I wonder if we could use a Once instead and cache the result?

**Comment by jefferai** [comment]
@sethvargo Your comments should be addressed in https://github.com/hashicorp/vault/pull/3897/commits/9b62480eabc2531b5d0663aed4a3322b90fbaa8f

File: command/main.go [hunk 7]
```diff
@@ -23,7 +48,83 @@ func Run(args []string) int {
 			args = []string{"version"}
 			break
 		}
+
+		// Parse a given flag here, which overrides the env var
+		if strings.HasPrefix(arg, "-format=") {
```
Comment (calvn) [inline command/main.go]: Haven't tested, but does this handle `--format` as well?

File: command/main.go [hunk 8]
```diff
@@ -10,11 +10,36 @@ import (
...
+func (u *VaultUI) Output(m string) {
+	if u.isTerminal {
+		u.Ui.Output(m)
+	} else {
+		getWriterFromUI(u.Ui).Write([]byte(m))
+	}
+}
+
+// setupEnv parses args and may replace them and sets some env vars to known
+// values based on color/format options
```
Comment (calvn) [inline command/main.go]: Doesn't handle color (anymore..?)

File: command/main.go [hunk 9]
```diff
@@ -23,7 +48,83 @@ func Run(args []string) int {
...
+		// For backwards compat, it could be specified without an equal sign
+		if arg == "-format" {
+			nextArgFormat = true
+		}
+	}
+
+	envVaultFormat := os.Getenv(EnvVaultFormat)
+	// If we did not parse a value, fetch the env var
+	if format == "" && envVaultFormat != "" {
+		format = envVaultFormat
```
Comment (calvn) [inline command/main.go]: We can probably do `format = strings.ToLower(envVaultFormat)` directly.

File: command/main.go [hunk 10]
```diff
@@ -23,7 +48,83 @@ func Run(args []string) int {
...
+		format = "table"
+	}
+	// Put back into the env for later
+	os.Setenv(EnvVaultFormat, format)
+
+	return args
+}
+
+func Run(args []string) int {
+	args = setupEnv(args)
```
Comment (calvn) [inline command/main.go]: Probably should rename `setupEnv` to `setupFormatEnv`.

File: command/main.go (hunk 7 above)
Comment (jefferai) [reply command/main.go]: Didn't even know we supported that. Will address.

File: command/main.go (hunk 9 above)
Comment (jefferai) [reply command/main.go]: We'd still need it outside the `if` block so it doesn't buy us anything.
