### PR TITLE
Fix AWS auth renewals

### LINKED ISSUE #8972: [1.4.x] Nomad integration breakage with aws / aws-ec2 auth and instance metadata
Upgrading vault from 1.3.x to 1.4.x causes token renew-self failures with nomad 0.11.1 (and possibly others). This might be a silent BC break for nomad users. It went unnoticed for several days in my test environment, but I suspect that it could have lead to widespread downtime if left long enough.

Error message logged by nomad:
```
nomad.vault: got error or bad auth, so backing off: error="failed to renew the vault token: Error making API request.#012#012URL: PUT https://active.vault.service.consul:8200/v1/auth/token/renew-self#012Code: 500. Errors:#012#012* 1 error occurred:#012#011* failed to renew entry: unable to fetch instance ID from metadata during renewal#012#012" recoverable=true
```

Gitter discussions:
* https://gitter.im/hashicorp-nomad/Lobby?at=5eb99c3a8c044c1914946c21
* https://gitter.im/hashicorp-vault/Lobby?at=5eb9972d20eaac185302484d

The issue seems to be related to recent value changes related to EC2 instance metadata:
* https://github.com/hashicorp/vault/pull/8783
* https://github.com/hashicorp/vault/pull/8880

In my environment, adding back the the ec2_metadata attributes appears to completely fix the issue:
```
vault write auth/aws-ec2/config/identity ec2_metadata=account_id,auth_type,ami_id,instance_id,region iam_metadata=account_id,auth_type,canonical_arn,client_arn,client_user_id,inferred_aws_region,inferred_entity_id,inferred_entity_type
```

I also added iam_metadata based on a previous community member's findings, but those may not be necessary to fix this particular problem.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.1
* Vault CLI Version (retrieve with `vault version`): 1.4.1
* Server Operating System/Architecture: CentOS 7

### PR DESCRIPTION
**Pull request by tyrannosaurus-becks**
Fixes #8972 

This PR fixes AWS auth renewals. Its tests are contained in #9021 and have been separated out so this will contain the minimum code change necessary.

### CODE REVIEW

File: builtin/credential/aws/path_login.go [hunk 1]
```diff
@@ -1709,6 +1716,23 @@ func (b *backend) fullArn(ctx context.Context, e *iamEntity, s logical.Storage)
...
+		if val, ok := raw.(string); ok {
+			return val, nil
+		} else {
+			return "", fmt.Errorf("unable to fetch %q from auth metadata due to type of %T", forKey, raw)
+		}
+	}
+	if val, ok := fromAuth.Metadata[forKey]; ok {
+		return val, nil
+	}
+	return "", fmt.Errorf("%q unfound in auth metadata", forKey)
```
Comment (kalafut) [inline builtin/credential/aws/path_login.go:1733]:
```suggestion
	return "", fmt.Errorf("%q not found in auth metadata", forKey)
```

File: builtin/credential/aws/path_login.go [hunk 2]
```diff
@@ -996,16 +1001,19 @@ func (b *backend) pathLoginRenewIam(ctx context.Context, req *logical.Request, d
...
 			}
-			instanceRegion, ok := req.Auth.Metadata["inferred_aws_region"]
-			if !ok {
-				return nil, fmt.Errorf("no inferred AWS region in auth metadata")
+			instanceRegion, err := getMetadataValue(req.Auth, "inferred_aws_region")
+			if err != nil {
+				return nil, err
 			}
-			_, err := b.validateInstance(ctx, req.Storage, instanceID, instanceRegion, req.Auth.Metadata["account_id"])
+			accountID, err := getMetadataValue(req.Auth, "account_id")
```
Comment (briankassouf) [inline builtin/credential/aws/path_login.go:1012]: Previously it doesn't seem like we were returning an error if account id wasn't set. Is this going to cause issues with older leases?

File: builtin/credential/aws/path_login.go [hunk 3]
```diff
@@ -1070,28 +1078,22 @@ func (b *backend) pathLoginRenewIam(ctx context.Context, req *logical.Request, d
...
-
-	// Ensure backwards compatibility for older clients without account_id saved in metadata
-	accountID, ok := req.Auth.Metadata["account_id"]
-	if ok {
-		if accountID == "" {
-			return nil, fmt.Errorf("unable to fetch account_id from metadata during renewal")
-		}
+	accountID, err := getMetadataValue(req.Auth, "account_id")
+	if err != nil {
+		return nil, err
```
Comment (briankassouf) [inline builtin/credential/aws/path_login.go:1092]: Same here, previously we were only erroring if the accountID was set but blank, is this going to cause issues?

File: builtin/credential/aws/path_login.go (hunk 2 above)
Comment (tyrannosaurus-becks) [reply builtin/credential/aws/path_login.go:1012]: Hm, good point. Theoretically _should_ have errored if it didn't exist, because [here](https://github.com/hashicorp/vault/blob/master/builtin/credential/aws/path_login.go#L1007) it would have been passed in as `""` to `validateInstance`. However, in tracing the code around, it does look _possible_ in some places that it could continue even with an account ID of `""`. Since there's not any test coverage either way, yes, I think that's a good idea - I will not error here and will pass in `""` if it's unset. Good catch.

File: builtin/credential/aws/path_login.go (hunk 3 above)
Comment (tyrannosaurus-becks) [reply builtin/credential/aws/path_login.go]: https://github.com/hashicorp/vault/pull/8991/commits/bb3cdb6d0231fa4e77c6a9ddbf7025d316d8530b

File: builtin/credential/aws/path_login.go (hunk 2 above)
Comment (tyrannosaurus-becks) [reply builtin/credential/aws/path_login.go:1012]: https://github.com/hashicorp/vault/pull/8991/commits/bb3cdb6d0231fa4e77c6a9ddbf7025d316d8530b

I put it at Debug log level versus Warn so if anyone was in this situation, it wouldn't spam their logs unless they wanted it to. Also, if there's a resulting error, it'll be loud enough without a preceding warning.
