### PR TITLE
Do the mariadb rotate-root query without prepared statements

### LINKED ISSUE #6116: rotate-root fails for MariaDB
When using rotate-root in a Database Secret Engine mount that is connected to MariaDB, it fails with error:

```
Error writing to: database/rotate-root/db.
URL: /v1/database/rotate-root/db
Code: 500
Errors:
  1 error occurred:
	* Error 1295: This command is not supported in the prepared statement protocol yet
```

**To Reproduce**
1. Use the latest stable version of MariaDB (10.3), downloaded from https://downloads.mariadb.org/mariadb/repositories. Quick script for convenience attached
2. Run 
```
vault secrets enable database
vault write database/config/db \
          plugin_name=mysql-database-plugin \
          allowed_roles="*" \
          connection_url="{{username}}:{{password}}@tcp(db.service.consul:3306)/mysql" \
          username="vaultadmin" \
          password="vaultadminpassword"
vault write database/roles/readonly \
          db_name=db \
          creation_statements="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'; GRANT SELECT ON *.* TO '{{name}}'@'%';" \
          default_ttl=1h max_ttl=24h
```
3. See error
```
vault write -force database/rotate-root/db
```

**Expected behavior**
Vault's password for the "db" connection to be rotated.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.0.0+prem
* Vault CLI Version (retrieve with `vault version`): Vault 1.0.0+prem
* Server Operating System/Architecture: Red Hat Enterprise Linux Server 7.5, x86_64

Vault server configuration file(s):

```hcl
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}
ui=true
```

**Additional context**
There is a comment in the source code regarding this error in the "CreateUser" and in the "RevokeUser" blocks, but not on the "RotateUser" https://github.com/hashicorp/vault/blob/df18871704fe869e9be45b542a6b1eb2fe46c293/plugins/database/mysql/mysql.go#L170
[install_mariadb.txt](https://github.com/hashicorp/vault/files/2800601/install_mariadb.txt)

### PR DESCRIPTION
**Pull request by ncabatoff**
Fixes #6116.

### CODE REVIEW

File: plugins/database/mysql/mysql.go [hunk 1]
```diff
@@ -294,11 +293,13 @@ func (m *MySQL) RotateRootCredentials(ctx context.Context, statements []string)
...
-			m := map[string]string{
-				"username": m.Username,
-				"password": password,
-			}
-			if err := dbtxn.ExecuteTxQuery(ctx, tx, m, query); err != nil {
+			// This is not a prepared statement because not all commands are supported
+			// 1295: This command is not supported in the prepared statement protocol yet
+			// Reference https://mariadb.com/kb/en/mariadb/prepare-statement/
+			query = strings.Replace(query, "{{username}}", m.Username, -1)
+			query = strings.Replace(query, "{{password}}", password, -1)
```
Comment (tyrannosaurus-becks) [inline plugins/database/mysql/mysql.go]: Question . . . is there any way this could be leveraged for a SQL injection attack? If so, should we add guards like checking for special characters or something?

Comment (tyrannosaurus-becks) [reply plugins/database/mysql/mysql.go]: Okay! I think that should be fine because the username is operator-provided and the password probably is originally too, and then is generated. Thanks!
