### PR TITLE
Use null strings in MSSQL to prevent errs

### LINKED ISSUE #6060: MSSQL plugin revoke users issue
There is an issue with revoking users in the MSSQL plugin. The error I get is this:

`[ERROR] expiration: failed to revoke lease: lease_id=database/creds/test/1oeia5hGjyneURHkpBeC9IZo error="failed to revoke entry: resp: (*logical.Response)(nil) err: sql: Scan error on column index 1, name "DBName": unsupported Scan, storing driver.Value type <nil> into type *string"`

The core of the issue is that the stored procedure `sp_msloginmappings` will always return a row, even if the login has no users / db's associated with it.

The issue comes into play when the first attempt to revoke fails at any stage AFTER the users associated with the logins are removed from all databases. On the next attempt to revoke, the stored procedure `sp_msloginmappings` returns NULL in the column DBName and the revoke attempt fails. This results in all the logins created to remain on the server as disabled and the leases build up within HashiCorp. 

A check here for DBName = null should do it: https://github.com/hashicorp/vault/blob/6e99c837e5eac025db729285e7d93566d43aa620/plugins/database/mssql/mssql.go#L269

### PR DESCRIPTION
**Pull request by tyrannosaurus-becks**
Closes #6060

### CODE REVIEW

File: builtin/logical/mssql/secret_creds.go [hunk 1]
```diff
@@ -118,13 +118,12 @@ func (b *backend) secretCredsRevoke(ctx context.Context, req *logical.Request, d
...
 	for rows.Next() {
-		var loginName, dbName, qUsername string
-		var aliasName sql.NullString
+		var loginName, dbName, qUsername, aliasName sql.NullString
 		err = rows.Scan(&loginName, &dbName, &qUsername, &aliasName)
 		if err != nil {
 			return nil, err
 		}
-		revokeStmts = append(revokeStmts, fmt.Sprintf(dropUserSQL, dbName, username, username))
+		revokeStmts = append(revokeStmts, fmt.Sprintf(dropUserSQL, dbName.String, username, username))
```
Comment (jefferai) [inline builtin/logical/mssql/secret_creds.go]: I'm curious about how the change to username from string to sql.NullString behaves here. NullString doesn't implement any of the marshaling interfaces (that I can see) so what happens when it's pulled into `dropUserSQL`, and why is it not using `.String` like dbName?

Comment (ncabatoff) [reply builtin/logical/mssql/secret_creds.go]: I'm uncomfortable with the (I believe undefined) behaviour of "USE []".  Even if it behaves fine now, it might do something different in the future, which could lead to us dropping the user from the wrong DB.

Moreover the MSSQL docs for DROP USER say "Removes a user from the current database."  So what would we expect our DROP USER to do when our query didn't return any DBs they belong to?

I think you should go with the check/continue approach.

Comment (tyrannosaurus-becks) [reply builtin/logical/mssql/secret_creds.go]: @ncabatoff all good points! I will use that approach.
