### PR TITLE
Fix group alias loading when identity memdb is initialized

### LINKED ISSUE #5288: group_alias memDB table does not get initialized properly
**Describe the bug**
When identityStore is initialized (post-unseal, leadership taken) it does not properly fill the group_alias memDB table.
Since all aliases content are stored in the identity group as well, any update on the group, will correctly save the alias in MemDB.

**To Reproduce**
```
#!/bin/bash

export VAULT_ADDR=http://localhost:8200
export VAULT_TOKEN=devtoken

function poison_pill
{
	pkill -P $$
}

FILE=$(mktemp)

function vault_up
{
	vault server -dev -dev-root-token-id="$VAULT_TOKEN" 2>&1 > $FILE &
}

function unseal_key
{
    grep 'Unseal Key:' $FILE | awk '{print $3}' | tr -d '\n'
}

function vault_reseal
{
    vault operator seal
    vault operator unseal $(unseal_key)
}

vault_up

trap poison_pill EXIT

set -e

sleep 1

GROUP_ID=$(vault write -format=json identity/group type=external name=test-group | jq -r '.data.id' | tr -d '\n')

vault auth enable ldap

ACCESSOR=$(vault auth list -format=json | jq -r '.["ldap/"].accessor' | tr -d '\n')

ALIAS_ID=$(vault write -format=json identity/group-alias name=test-alias canonical_id=$GROUP_ID mount_accessor=$ACCESSOR | jq -r '.data.id' | tr -d '\n')


echo "--- LIST ALL ALIASES"
vault list identity/group-alias/id
echo "---------------------"

echo "Resealing Vault"
vault_reseal

sleep 1

echo "--- LIST ALL ALIASES AFTER RE-UNSEAL"
vault list identity/group-alias/id
echo "---------------------"

rm -f "$FILE"

exit 1
```

**Expected behavior**
Aliases should get loaded properly

**Environment:**
* Vault Server Version (retrieve with `vault status`): master ( tested on 0.10 and 0.11 too)
* Vault CLI Version (retrieve with `vault version`): can be made via api calls
* Server Operating System/Architecture: all

**Additional context**
Impacts all backends as it's a functional problem in identityStore, not backend specific layer

### PR DESCRIPTION
**Pull request by uepoch**
Fixes #5288 

This move the MemDB Alias upsert deeper in UpsertGroupInTxn which get called in loadGroups at initialization.

This way aliases get initialized properly when loading groups from storagePacker

### CODE REVIEW

File: vault/identity_store_util.go [hunk 1]
```diff
@@ -1092,6 +1086,12 @@ func (i *IdentityStore) UpsertGroupInTxn(txn *memdb.Txn, group *identity.Group,
 	// Increment the modify index of the group
 	group.ModifyIndex++
 
+	if group.Alias != nil {
```
Comment (vishalnayak) [inline vault/identity_store_util.go]: This block is also present in https://github.com/hashicorp/vault/blob/master/vault/identity_store.go#L222 which needs to be removed.

**Comment by vishalnayak** [comment]
We'd like this PR to be in sooner. So we'll be addressing the comment post-merge. Thanks for submitting this!
