### PR TITLE
transit cache is an Interface implemented by wrapped versions of sync…

### LINKED ISSUE #5746: Upserting Keys via Transit seems to leak Memory
**Describe the bug**
We are calling the transit's backends encrypt method (i.e.  `encrypt/<key>`) in batch mode with a large amount of keys (millions). The memory consumption of vault just increases monotonically and never decreases again. (See attached picture from our monitoring)

cpu and memory graph

**To Reproduce**
1. call the encrypt endpoint of the transit backend in a tight loop (ideally in parallel) with key upsert (i.e. a new unknown key per call)

**Expected behavior**
Memory goes down again or plateaus.

**Environment:**
* Vault Server Version 0.10.1, but we also tested with 0.11.4

Vault server configuration file(s):

default config with Google Storage as storage backend. No other setting (like cache setting) have been changed from the default.

### PR DESCRIPTION
**Pull request by Lexman42**
…map and golang-lru

fixes #5746

### CODE REVIEW

**Comment by Lexman42** [comment]
Some notes/thoughts:
- calling `vault write transit/cache-config cache-type=<existing type>` has the effect of clearing the cache of that type, perhaps it should instead be a no op, or, in the case of a cache-type that requires a size, like LRU, just modify the size (delete some elements if downsizing, create more space if upsizing)
- it might be useful to be able to read the cache size (in this PR added ability to read cache type and length, but, not the size)
- maybe ability to read cache length isn't really relevant and should be taken out, not sure what this will do on a very large cache using syncmap

File: builtin/logical/transit/path_cache_config.go [hunk 1]
```diff
@@ -51,22 +42,21 @@ This can be a long operation for large syncmap caches.
...
 		cacheType = keysutil.LRU
 	default:
-		cacheType = keysutil.NOTIMPLEMENTED
+		cacheType = keysutil.NotImplemented
 	}
 
 	// err if the requested cacheType has not been implemented
-	if cacheType == keysutil.NOTIMPLEMENTED {
+	if cacheType == keysutil.NotImplemented {
 		return logical.ErrorResponse(fmt.Sprintf("unknown cache-type %s", cacheTypeStr)), logical.ErrInvalidRequest
```
Comment (ncabatoff) [inline builtin/logical/transit/path_cache_config.go]: Minor nit: use %q instead of %s, will be more readable e.g. in the empty string case.

File: helper/keysutil/transit_lru.go [hunk 2]
```diff
@@ -3,12 +3,13 @@ package keysutil
 import lru "github.com/hashicorp/golang-lru"
 
 type TransitLRU struct {
-	lru *lru.TwoQueueCache
+	size int
+	lru  *lru.TwoQueueCache
 }
 
 func NewTransitLRU(size int) *TransitLRU {
 	lru, _ := lru.New2Q(size)
```
Comment (ncabatoff) [inline helper/keysutil/transit_lru.go]: Why do you ignore the error value?

File: builtin/logical/transit/path_cache_config.go [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+
+	return resp, nil
+}
+
+const pathCacheConfigHelpSyn = `Configure caching strategy`
+
+const pathCacheConfigHelpDesc = `
+This path is used to configure and query the caching strategy for the transit mount.
+For cache-types that do not have an upperbound like "syncmap", 0 is returned.
+`
```
Comment (ncabatoff) [inline builtin/logical/transit/path_cache_config.go]: Wording is a bit ambiguous here.  You don't say what '0 is returned' is in reference to, i.e. cache-size.  I would also make it explicit that this is the max size of the cache, not the number of entries it currently contains.

File: helper/keysutil/transit_lru.go (hunk 2 above)
Comment (Lexman42) [reply helper/keysutil/transit_lru.go]: shouldn't be ignored imo - it bubbles up to the user now.

File: builtin/logical/transit/path_cache_config.go (hunk 3 above)
Comment (Lexman42) [reply builtin/logical/transit/path_cache_config.go]: agreed and reworded, @ncabatoff let me know if it is clearer now

File: builtin/logical/transit/path_cache_config.go [hunk 4]
```diff
@@ -70,11 +70,12 @@ func (b *backend) pathCacheConfigWrite(ctx context.Context, req *logical.Request
 		b.lm.ConvertCacheToSyncmap()
 	}
 
+	var err error
 	if cacheType == keysutil.LRU {
-		b.lm.ConvertCacheToLRU(cacheSize)
+		err = b.lm.ConvertCacheToLRU(cacheSize)
```
Comment (ncabatoff) [inline builtin/logical/transit/path_cache_config.go]: Shouldn't we return a logical.ErrorResponse for the first return value in this scenario (rather than nil)?

Comment (Lexman42) [reply builtin/logical/transit/path_cache_config.go]: I am unsure. I was influenced by patterns like [this](https://github.com/hashicorp/vault/blob/master/builtin/logical/transit/path_decrypt.go#L62). Returning `logical.ErrorResponse, nil` will give some feedback to the user, returning `nil, err` will bubble up the error. My gut feeling is to go with what you are suggesting because I think this error should be returned to the user but maybe someone else can provide some input @briankassouf @calvn?

Comment (Lexman42) [reply builtin/logical/transit/path_cache_config.go]: Seems that returning a `nil` _*logical.Response_ and a `internal-error` _error_ is the established pattern to default to an _InternalServerError_.

Looking at response_util [here](https://github.com/hashicorp/vault/blob/e9b8dffd763cbc847fd9552992ae8284444483a7/logical/response_util.go#L16) and [here](https://github.com/hashicorp/vault/blob/e9b8dffd763cbc847fd9552992ae8284444483a7/logical/response_util.go#L90).

File: builtin/logical/transit/path_cache_config.go [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+	"github.com/hashicorp/vault/helper/keysutil"
+	"github.com/hashicorp/vault/logical"
+	"github.com/hashicorp/vault/logical/framework"
+)
+
+func (b *backend) pathCacheConfig() *framework.Path {
+	return &framework.Path{
+		Pattern: "cache-config",
+		Fields: map[string]*framework.FieldSchema{
+			"cache-type": &framework.FieldSchema{
```
Comment (calvn) [inline builtin/logical/transit/path_cache_config.go]: Can we default to a preferred cache type instead of erroring out if none is provided?

File: builtin/logical/transit/path_cache_config.go [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+			"cache-size": &framework.FieldSchema{
+				Type: framework.TypeInt,
+				Description: `
+Size of cache for a cache type that accepts a size. This is required for cache types
+that accept a size and currently applies only to "lru" cache type.
+`,
+			},
+		},
+
+		Operations: map[logical.Operation]framework.OperationHandler{
```
Comment (calvn) [inline builtin/logical/transit/path_cache_config.go]: Missing summary and descriptions for these operations.

File: builtin/logical/transit/path_cache_config.go [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+		return logical.ErrorResponse(fmt.Sprintf("unknown cache-type %q", cacheTypeStr)), logical.ErrInvalidRequest
+	}
+
+	// err if cacheType is lru but no cache-size was specified
+	if cacheType == keysutil.LRU && cacheSize <= 0 {
+		return logical.ErrorResponse("for lru cache-type, cache-size must be specified and be greater than zero"), logical.ErrInvalidRequest
+	}
+
+	// change the cache type
+	if cacheType == keysutil.SyncMap {
```
Comment (calvn) [inline builtin/logical/transit/path_cache_config.go]: Call convert if the cache type is different from the current one since it will reset the cache.

File: builtin/logical/transit/path_cache_config.go [hunk 8]
```diff
@@ -0,0 +1,124 @@
...
+		b.lm.ConvertCacheToSyncmap()
+	}
+
+	if cacheType == keysutil.LRU {
```
Comment (calvn) [inline builtin/logical/transit/path_cache_config.go]: Same as above, we should only call convert if it's different, but maybe also take cache size into consideration (i.e. if a new value is provided that's different from the current one).

File: builtin/logical/transit/path_cache_config.go [hunk 9]
```diff
@@ -0,0 +1,124 @@
...
+		cacheType = "syncMap"
+	case keysutil.LRU:
+		cacheType = "lru"
+	default:
+		cacheType = "unknown"
+	}
+
+	resp := &logical.Response{
+		Data: map[string]interface{}{
+			"cache-type":     cacheType,
```
Comment (kalafut) [inline builtin/logical/transit/path_cache_config.go]: Underscore separators are typically used throughout Vault for API responses.

File: helper/keysutil/transit_lru.go [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+	lru, err := lru.New2Q(size)
+	return &TransitLRU{lru: lru, size: size}, err
+}
+
+func (c *TransitLRU) Delete(key interface{}) {
+	c.lru.Remove(key)
+}
+
+func (c *TransitLRU) Load(key interface{}) (value interface{}, ok bool) {
+	value, ok = c.lru.Get(key)
```
Comment (kalafut) [inline helper/keysutil/transit_lru.go]: This can just be: `return c.lru.Get(key)`

File: helper/keysutil/transit_syncmap.go [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+func NewTransitSyncMap() *TransitSyncMap {
+	return &TransitSyncMap{syncmap: sync.Map{}}
+}
+
+func (c *TransitSyncMap) Delete(key interface{}) {
+	c.syncmap.Delete(key)
+}
+
+func (c *TransitSyncMap) Load(key interface{}) (value interface{}, ok bool) {
+	value, ok = c.syncmap.Load(key)
```
Comment (kalafut) [inline helper/keysutil/transit_syncmap.go]: This can just be: `return c.lru.Get(key)`

File: builtin/logical/transit/path_cache_config.go [hunk 12]
```diff
@@ -0,0 +1,124 @@
...
+
+func (b *backend) pathCacheConfig() *framework.Path {
+	return &framework.Path{
+		Pattern: "cache-config",
+		Fields: map[string]*framework.FieldSchema{
+			"cache-type": &framework.FieldSchema{
+				Type:     framework.TypeString,
+				Required: true,
+				Description: `
+Type of cache to use. Currently "syncmap" and "lru" are supported.
```
Comment (kalafut) [inline builtin/logical/transit/path_cache_config.go]: I'm not sure about the term "syncmap", as it seems quite coupled to the Go stdlib and isn't a generally used term. Plus we might switch the implementation but retain the behavior. From a customer perspective, I know what "lru" implies, but what are the characteristics of what is now "syncmap"? Maybe simplifying to "map" is enough, but I'd be curious what others think.

Comment (ncabatoff) [reply builtin/logical/transit/path_cache_config.go]: Good points.  How about "unlimited"?

Comment (briankassouf) [reply builtin/logical/transit/path_cache_config.go]: I think a better UX would be removing the `cache-type` parameter all together and just require a `cache-size` to be set. It doesn't really matter to the user what data structure is used under the hood. The default can be `0` which means unlimited (syncmap) and if `>0` we use the LRU

File: builtin/logical/transit/path_cache_config.go (hunk 5 above)
Comment (Lexman42) [reply builtin/logical/transit/path_cache_config.go]: When a new cache is created it will default to `unlimited` (syncmap). Kind of related is whether this parameter should be `required`. Presently, there are only two cache types, one with a size and one without size, so we don't even really need this parameter. However, as soon as we add a 3rd cache-type we will _likely_ need this parameter. The case where we wouldn't need it is if we opt for some logic that only updates the underlying type if it is specified or if it can be inferred (ie there are 3 caches, 2 that do not have a size and one that does -> user specifies a size but not a cache-type, there is only one possibility). In my mind it is slightly simpler in the code and for users to have to specify the cache-type each time they configure it. Thoughts?

File: builtin/logical/transit/path_cache_config.go (hunk 12 above)
Comment (Lexman42) [reply builtin/logical/transit/path_cache_config.go]: @briankassouf I was just thinking something similar here: https://github.com/hashicorp/vault/pull/6225#discussion_r261336646

File: builtin/logical/transit/path_cache_config.go [hunk 13]
```diff
@@ -0,0 +1,103 @@
...
+				Default:     0,
+				Description: `Size of cache, use 0 for an unlimited cache size, defaults to 0`,
+			},
+		},
+
+		Operations: map[logical.Operation]framework.OperationHandler{
+			logical.ReadOperation: &framework.PathOperation{
+				Callback:    b.pathCacheConfigRead,
+				Summary:     "Returns the size of the active cache",
+				Description: "",
```
Comment (calvn) [inline builtin/logical/transit/path_cache_config.go]: You can omit setting this field at all.

File: builtin/logical/transit/backend.go [hunk 14]
```diff
@@ -64,6 +68,28 @@ type backend struct {
 	lm *keysutil.LockManager
 }
 
+// initializeCache initializes a transit's cache
+func (b *backend) initializeCache(ctx context.Context, s logical.Storage) error {
+	// default to an unlimited cache size
+	targetSize := 0
+	// override default size with a stored size value if one is available
+	if entry, _ := s.Get(ctx, "config/cache-size"); entry != nil {
```
Comment (calvn) [inline builtin/logical/transit/backend.go]: You might want to capture and return this error

File: builtin/logical/transit/backend.go [hunk 15]
```diff
@@ -64,6 +68,28 @@ type backend struct {
...
+		var storedCacheSize configCacheSize
+		if err := entry.DecodeJSON(&storedCacheSize); err != nil {
```
Comment (calvn) [inline builtin/logical/transit/backend.go]: Before decoding this entry, you might want to check if it's nil (which can happen if you're mounting a fresh backend) and if so, simply call `b.lm.ConvertCacheToSyncmap()` and return.

File: builtin/logical/transit/backend.go [hunk 16]
```diff
@@ -64,6 +68,26 @@ type backend struct {
 	lm *keysutil.LockManager
 }
 
+// a lock manager defaults to a syncmap cache, initializeCache modifies the cache type
```
Comment (calvn) [inline builtin/logical/transit/backend.go]: Maybe something along the lines of:
```
// initializeCache sets the backend's lock manger cache accordingly using the stored configuration.
```

File: builtin/logical/transit/backend.go [hunk 17]
```diff
@@ -47,6 +50,7 @@ func Backend(conf *logical.BackendConfig) *backend {
 			b.pathBackup(),
 			b.pathRestore(),
 			b.pathTrim(),
+			b.pathCacheConfig(),
```
Comment (jefferai) [inline builtin/logical/transit/backend.go]: Is there a reason this should be part of a config path instead of a mount option?

Comment (Lexman42) [reply builtin/logical/transit/backend.go]: The new cache type is only available to the transit backend so I thought it would be confusing to have a mount option that only applies to one kind of mount (but it could be if that seems more reasonable).

Comment (jefferai) [reply builtin/logical/transit/backend.go]: In theory this is exactly what the options map is for. I think the main issue is plumbing them into CLI, if we start adding options only valid for some backends it could make the CLI kind of ugly. This might be a good topic for the offsite as it's come up a few times in various ways, let's talk there!

File: builtin/logical/transit/path_cache_config.go [hunk 18]
```diff
@@ -0,0 +1,100 @@
...
+	}
+
+	if cacheSize == 0 {
+		b.lm.ConvertCacheToSyncmap()
+	} else {
+		err := b.lm.ConvertCacheToLRU(cacheSize)
+		if err != nil {
+			return nil, errwrap.Wrapf("failed to create cache: {{err}}", err)
+		}
+	}
```
Comment (briankassouf) [inline builtin/logical/transit/path_cache_config.go]: I wonder if lines 55->66 could be internal to the lock manager and only use a `lm.SetCacheSize(cacheSize)` function here?

Comment (Lexman42) [reply builtin/logical/transit/path_cache_config.go]: @briankassouf moved that logic [here](https://github.com/hashicorp/vault/pull/6225/files#diff-70530f22fc776fd9e11919754f7fa137R110)

File: helper/keysutil/lock_manager.go [hunk 19]
```diff
@@ -54,27 +54,85 @@ type PolicyRequest struct {
...
+	defer lm.lock.RUnlock()
+	return lm.cacheType
+}
+
+func (lm *LockManager) GetCacheSize() int {
+	// Locked because lm.cache could change
+	lm.lock.RLock()
+	defer lm.lock.RUnlock()
+	return lm.cache.Size()
+}
```
Comment (briankassouf) [inline helper/keysutil/lock_manager.go]: I think we can remove most (or all?) of these functions now that `SetCacheSize` exists, right?

Comment (briankassouf) [reply helper/keysutil/lock_manager.go]: Or at least make them non-exported

File: helper/keysutil/lock_manager.go [hunk 20]
```diff
@@ -54,27 +54,85 @@ type PolicyRequest struct {
...
+
+func (lm *LockManager) SetCacheSize(size int) error {
+	switch {
+	case size < 0:
+		return errors.New("cache size must be greater or equal to zero")
+	case size == lm.GetCacheSize():
+		return fmt.Errorf("cache size is already set at: %d", size)
```
Comment (briankassouf) [inline helper/keysutil/lock_manager.go]: Perhaps we just return nil here, seems like this doesn't need to be an error case?

File: builtin/logical/transit/backend.go [hunk 21]
```diff
@@ -64,6 +68,25 @@ type backend struct {
...
+	if err != nil {
+		return err
+	}
+	if entry != nil {
+		var storedCacheSize configCacheSize
+		if err := entry.DecodeJSON(&storedCacheSize); err != nil {
+			return err
+		}
+		if storedCacheSize.Size > 0 {
+			return b.lm.ConvertCacheToLRU(storedCacheSize.Size)
```
Comment (briankassouf) [inline builtin/logical/transit/backend.go]: We could just use the `SetCacheSize` function instead

File: helper/keysutil/lock_manager.go (hunk 19 above)
Comment (Lexman42) [reply helper/keysutil/lock_manager.go]: Still making use of them but they certainly don't need to be exported

File: helper/keysutil/lock_manager.go (hunk 20 above)
Comment (Lexman42) [reply helper/keysutil/lock_manager.go]: I debated on this and am happy to change it. Here is my reasoning that led me to making it an error case:
- nothing is actually `set` and I want to provide feedback to a user who might be trying to leverage SetCacheSize as a mechanism to clear cache. Returning nil will ultimately provide a 'Success' response to the user which opens some room for ambiguity as to whether the cache was just set now and cleared or had been set previously. The error message removes that ambiguity imo.
- it is a clean way to avoid writing to vault's storage [here](https://github.com/hashicorp/vault/pull/6225/files#diff-ce466f4b2b0b2027c1bfac932657007bR54) without needing to call b.lm.GetCacheSize() and make a comparison. I wanted to avoid that call so that the lock manager logic really is all in the lock manager and I also don't want to write to the storage entry when there has been no update to the lock manager.

Thoughts?

Comment (briankassouf) [reply helper/keysutil/lock_manager.go]: I mentioned this because i believe when we call `initializeCache` in the Factory function we would hit this error case and the Factory would return an error. But i'll also comment on your other points:

> nothing is actually set and I want to provide feedback to a user who might be trying to leverage SetCacheSize as a mechanism to clear cache. Returning nil will ultimately provide a 'Success' response to the user which opens some room for ambiguity as to whether the cache was just set now and cleared or had been set previously. The error message removes that ambiguity imo.

Since SetCacheSize doesn't guarantee a cache clear (it's more of a side effect than an intent) I think it's fine to return a "Success" response. The intent of the function is to set the size to X and if the value is already at X it's just a no-op, but IMO is still a success. If we need a Cache Clear mechanism in the future we can add a separate function for it.

> it is a clean way to avoid writing to vault's storage here without needing to call b.lm.GetCacheSize() and make a comparison. I wanted to avoid that call so that the lock manager logic really is all in the lock manager and I also don't want to write to the storage entry when there has been no update to the lock manager.

This is a good point, but it is a common pattern in Vault to write to storage without first reading it to make sure we are not duplicating data (e.g. If you write the same value to k/v over and over we will persist it each time) I think it's fine to still update storage even if the value isn't changing. Though another option is to change the set function to return `bool, error` where the bool is indicating that the cache was updated.

Comment (Lexman42) [reply helper/keysutil/lock_manager.go]: This is great context - thank you. Since there doesn't seem to be any concern with updating the storage even if the cache size value hasn't changed I think that is the cleanest solution. I'm inclined to avoid returning the bool following your reasoning that cache clearing is a side effect and not the intended purpose of setCache() (and that we can add something specific for clearing the cache if there is a need for it later).

File: builtin/logical/transit/path_cache_config.go [hunk 22]
```diff
@@ -0,0 +1,106 @@
...
+		HelpSynopsis:    pathCacheConfigHelpSyn,
+		HelpDescription: pathCacheConfigHelpDesc,
+	}
+}
+
+func (b *backend) pathCacheConfigWrite(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
+	// get target size
+	cacheSize := d.Get("size").(int)
+	if cacheSize < 0 {
+		return nil, errors.New("size must be greater or equal to 0")
```
Comment (briankassouf) [inline builtin/logical/transit/path_cache_config.go]:
```suggestion
		return logical.ErrorResponse("size must be greater or equal to 0"), logical.ErrInvalidRequest
```

Will cause it to return a 400 instead of a 500

File: builtin/logical/transit/path_cache_config.go [hunk 23]
```diff
@@ -0,0 +1,106 @@
...
+
+func (b *backend) pathCacheConfigRead(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
+	// error if no cache is configured
+	if !b.lm.GetUseCache() {
+		return nil, errors.New(
+			"There is no cache for this backend. It was enabled with {force_no_cache: true}",
+		)
+	}
+
+	// compare current and stored cache sizes. If they are different warn the user.
```
Comment (briankassouf) [inline builtin/logical/transit/path_cache_config.go]:
```suggestion
	// Compare current and stored cache sizes. If they are different warn the user.
```

File: builtin/logical/transit/path_cache_config.go [hunk 24]
```diff
@@ -0,0 +1,106 @@
...
+
+type configCacheSize struct {
+	Size int `json:"size"`
+}
+
+func (b *backend) pathCacheConfigRead(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
+	// error if no cache is configured
+	if !b.lm.GetUseCache() {
+		return nil, errors.New(
+			"There is no cache for this backend. It was enabled with {force_no_cache: true}",
```
Comment (briankassouf) [inline builtin/logical/transit/path_cache_config.go]:
```suggestion
			"caching is disabled for this transit mount",
```

File: website/source/api/secret/transit/index.html.md [hunk 25]
```diff
@@ -1252,3 +1252,62 @@ $ curl \
     --data @payload.json \
     http://127.0.0.1:8200/v1/transit/keys/my-key/trim
 ```
+
+## Configure Cache
+
+This endpoint is used to configure the transit engine's cache. Note that configuration
+changes will not be applied until the transit plugin is reloaded which can be achieved
+ using the [`/sys/plugins/reload/backend`](../../system/plugins-reload-backend.html.md#reload-plugins) endpoint.
```
Comment (Lexman42) [inline website/source/api/secret/transit/index.html.md]: Will linking like this work when the website doc is produced?

File: website/source/api/secret/transit/index.html.md [hunk 26]
```diff
@@ -1252,3 +1252,62 @@ $ curl \
...
+    --header "X-Vault-Token: ..."
+    --request GET \
+    http://127.0.0.1:8200/v1/transit/cache-config
+```
+
+### Sample Response
+
+```json
+  "data": {
+    "cache_size": 0
```
Comment (Lexman42) [inline website/source/api/secret/transit/index.html.md]: should this be changed to just `size` to be consistent with the parameter provided to the POST endpoint?

**Comment by Lexman42** [comment]
@briankassouf added docs which could use a review on language/grammar/formatting.

File: website/source/api/secret/transit/index.html.md (hunk 25 above)
Comment (Lexman42) [reply website/source/api/secret/transit/index.html.md]: I believe the `.md` will get dropped.

File: builtin/logical/transit/backend.go [hunk 27]
```diff
@@ -47,23 +52,55 @@ func Backend(conf *logical.BackendConfig) *backend {
...
 }
 
 type backend struct {
 	*framework.Backend
 	lm *keysutil.LockManager
 }
 
+func GetCacheSizeFromStorage(ctx context.Context, s logical.Storage) (int, error) {
+	size := 0
+	entry, err := s.Get(ctx, "config/cache-size")
```
Comment (jefferai) [inline builtin/logical/transit/backend.go]: Is there a reason to make this entry so special purpose? Could it just be some kind of generic `config`/`transitConfig thing so that if we add more knobs later we can reuse the same struct?

File: sdk/helper/keysutil/policy_test.go [hunk 28]
```diff
@@ -52,8 +52,10 @@ func TestPolicy_KeyEntryMapUpgrade(t *testing.T) {
 }
 
 func Test_KeyUpgrade(t *testing.T) {
-	testKeyUpgradeCommon(t, NewLockManager(false))
-	testKeyUpgradeCommon(t, NewLockManager(true))
+	lockManagerWithCache, _ := NewLockManager(false, 0)
```
Comment (jefferai) [inline sdk/helper/keysutil/policy_test.go]: Shouldn't this be `true`?

File: sdk/helper/keysutil/policy_test.go [hunk 29]
```diff
@@ -97,8 +99,10 @@ func testKeyUpgradeCommon(t *testing.T, lm *LockManager) {
 }
 
 func Test_ArchivingUpgrade(t *testing.T) {
-	testArchivingUpgradeCommon(t, NewLockManager(false))
-	testArchivingUpgradeCommon(t, NewLockManager(true))
+	lockManagerWithCache, _ := NewLockManager(false, 0)
```
Comment (jefferai) [inline sdk/helper/keysutil/policy_test.go]: Same here?

File: sdk/helper/keysutil/policy_test.go [hunk 30]
```diff
@@ -255,8 +259,10 @@ func testArchivingUpgradeCommon(t *testing.T, lm *LockManager) {
 }
 
 func Test_Archiving(t *testing.T) {
-	testArchivingCommon(t, NewLockManager(false))
-	testArchivingCommon(t, NewLockManager(true))
+	lockManagerWithCache, _ := NewLockManager(false, 0)
```
Comment (jefferai) [inline sdk/helper/keysutil/policy_test.go]: And here
