### PR TITLE
pgp list fix

### LINKED ISSUE #7250: Vault web UI can't provide PGP key for init
**The bug**
When accessing the init form through the UI, it seems that we can't input PGP keys through file selection or text.

**To Reproduce**
1. Open the Vault web UI init form 
2. Input 1 for key shares
3. Input 1 for key threshold
4. Develop the "Encrypt output with PGP" section
5. Input PGP data by choosing a file or entering as Base64 text
6. Notice that the PGP form part disappear
7. Click on "Initialize"
8. Notice that Vault was initialized without encrypting output with PGP

**Expected behavior**
I suppose that the PGP form part should not disappear and the PGP key be taken in account for initialization.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.0, also happens on 1.1.3
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: CentOS Server x64
* Browsers (All on Win10) :  
  * Firefox 68.0.1
  * Chrome 75.0.3770.142
  * Internet Explorer 11.885.17134.0
  * Edge 42.17134.1.0

**Additional context**
Hopefully, everything works fine if Vault is initialized through the CLI :)

### PR DESCRIPTION
**Pull request by meirish**
The `PgpList` component was erroring out on `replace` which is an ember array proxy method, but not a native JS array method. One of the ember updates must have changed how prototype extensions work and there were no tests for `PgpList` so we missed the breakage.

This adds tests for `PgpList` and refactors the component so we're not mutating a computed property.

Fixes #7250

### CODE REVIEW

File: ui/app/components/pgp-list.js [hunk 1]
```diff
@@ -1,23 +1,57 @@
...
+    // no update needed
+    if (this.listData.length === this.listLength) {
+      return;
+    }
+    // shorten the current list
+    if (this.listLength < this.listData.length) {
+      list = this.listData.slice(0, this.listLength);
+    }
+    // add to the current list by creating a new list and copying over existing list
+    if (this.listLength > this.listData.length) {
```
Comment (noelledaley) [inline ui/app/components/pgp-list.js]: should this be an `else if`?

Comment (meirish) [reply ui/app/components/pgp-list.js]: I think that would be functionally the same, I just like keeping track of a single thing and this feels more like shallow`if` statements, but adding else isn't really another level. Let me update it!
