### PR TITLE
Fix empty consistency option issue for Cassandra

### LINKED ISSUE #1981: Cassandra role parameter consistency is mandatory
Cassandra role parameter consistency is mandatory but docs state it's optional defaulting to `Quorum`.

Vault Version: 0.6.2

**Role setup without consistency parameter**
```
vault write cassandra/roles/readonly creation_cql="..."
Error writing data to cassandra/roles/readonly: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/cassandra/roles/readonly
Code: 400. Errors:

* Error parsing consistency value of "": ParseConsistencyWrapper: invalid consistency: 
```

**Role setup with consistency parameter**
```
vault write cassandra/roles/readonly creation_cql="..." consistency=All
Success! Data written to: cassandra/roles/readonly
```

### PR DESCRIPTION
**Pull request by LLBennett**
Resolves #1981

### CODE REVIEW

File: builtin/logical/cassandra/path_roles.go [hunk 1]
```diff
@@ -131,6 +131,9 @@ func (b *backend) pathRoleCreate(
 	}
 
 	consistencyStr := data.Get("consistency").(string)
+	if consistencyStr == "" {
```
Comment (jefferai) [inline builtin/logical/cassandra/path_roles.go]: This should be the value of the "Default" member of the field. That way `Get` will automatically populate it with `"Quorum"` if they do not specify a different value.

File: builtin/logical/cassandra/backend_test.go [hunk 2]
```diff
@@ -35,7 +35,7 @@ func TestBackend_roleCrud(t *testing.T) {
 		Backend:        b,
 		Steps: []logicaltest.TestStep{
 			testAccStepConfig(t),
-			testAccStepRole(t),
+			testAccStepRoleWithOptions(t),
```
Comment (jefferai) [inline builtin/logical/cassandra/backend_test.go]: Sadly Cassandra doesn't yet use `dockertest` so these tests are skipped by Travis -- but this will actually cause tests to fail. You removed the role creation step that writes the role `test` in favor of one that writes the role `test2`, so when the next steps are executed it'll fail. Probably you should do both -- call `testAccStepRole` and the rest using `"test"`, then call the options version and the rest using "test2".
