### PR TITLE
Fix multiple OpenAPI generation issues with new AST-based generator

### LINKED ISSUE #18484: Vault OpenAPI is incorrect for new PKI secrets engine endpoints
**Describe the bug**
The Vault OpenAPI generator relies on reverse-engineering path regexps to correctly generate the OpenAPI document.

Several regexps used in the new (circa 1.11) PKI secrets engine are now too complicated for the OpenAPI generator to handle correctly.

**To Reproduce**
1. Mount a PKI secrets engine
2. Examine the generated OpenAPI
3. Observe these clearly incorrect paths:

```
/pki//delta
/pki//delta/pem
/pki//der
/pki//json
/pki//pem
/pki/internal|exported
/pki/{issuer_ref}/crl/pem|/der|/delta/pem
/pki/{issuer_ref}/der|/pem
```

**Expected behavior**
The Vault OpenAPI generator should generate a document which accurately describes the Vault API.

In order to achieve this, it may well be helpful to define a strict subset of regexp syntax which can be used in Vault path regexps.

### LINKED ISSUE #18488: Auto-generated OpenAPI is *incorrect* for /aws/creds again (regression)
#17926 has regressed the fix for #12794 in 1.13-dev

Meanwhile I've filed #18484 which also concerns use of alternation (the `|` character) in regexes confusing the OpenAPI generator, as well.

### PR DESCRIPTION
**Pull request by maxb**
Currently, the Vault OpenAPI generator attempts to use a variety of ad-hoc regexps, to simplify the path regexps that are the canonical specification of URL paths in Vault backends, and convert them into OpenAPI URL patterns. Regexps are not well suited to parsing regexps, and this approach is fragile and incomplete.

Happily, the Go regexp library provides easy access to its string-to-AST parser, so we can just ask it to parse the regexps for us, and then walk the resulting AST for a more reliable translation from regexps to OpenAPI patterns - this PR makes that change.

Whilst developing this change, it came to light that there are incorrectly unescaped full stops in some existing patterns - so the dot in `/.well-known/` could in fact be any character. These are now properly escaped.

As a result of these changes, the OpenAPI document changes in the following ways:

In the AWS secrets engine, the `/creds/{name}` endpoint was being incorrectly documented as `/creds` - fixed (closes #18488).

In the GCP secrets engine, the `/roleset` and `/static-account` endpoints were missing - fixed.

~~In the KV v2 secrets engine, the `/.*` endpoint, which already had no visible operations since they are all marked as `Unpublished`, is now removed from the OpenAPI document entirely, since `'/.*` is not a valid OpenAPI path pattern.~~

In the PKI secrets engine, widespread inaccuracies are fixed (closes #18484):

The following endpoints, which were incorrectly undocumented, are added:

    /cert/crl
    /cert/delta-crl
    /crl/delta
    /crl/delta/pem
    /crl/pem
    /issuer/{issuer_ref}
    /issuer/{issuer_ref}/crl
    /issuer/{issuer_ref}/crl/delta
    /issuer/{issuer_ref}/crl/delta/der
    /issuer/{issuer_ref}/crl/delta/pem
    /issuer/{issuer_ref}/crl/der
    /issuer/{issuer_ref}/crl/pem
    /issuer/{issuer_ref}/der
    /issuer/{issuer_ref}/json
    /issuer/{issuer_ref}/pem
    /issuers/import/bundle
    /issuers/import/cert
    /keys/generate/exported
    /keys/generate/internal
    /keys/generate/kms

The following endpoints, which were documented but don't actually exist, are removed:

    //delta
    //delta/pem
    //der
    //json
    //pem
    /bundle
    /cert
    /delta-crl
    /internal|exported
    /kms
    /{issuer_ref}/crl/pem|/der|/delta/pem
    /{issuer_ref}/der|/pem

In the RADIUS auth method, `/login` endpoint no longer documents an incorrect `urlusername` field in the request body.

In the `/sys/plugins/catalog/{type}/{name}` endpoint, the `type` parameter is now no longer also incorrectly included in the request body.

In the `/sys/tools/hash` endpoints, the `urlalgorithm` parameter is now no longer incorrectly included in the request body.

In the `/sys/tools/random` and `/transit/random` endpoints, the `source` and `urlbytes` parameters are now no longer incorrectly included in the request body.

In various `/transit/` endpoints, the `urlalgorithm` parameter is now no longer incorrectly included in the request body.

In the `/transit/restore` endpoints, the `name` parameter is now no longer incorrectly included in the request body.

These "parameter is now no longer incorrectly included in the request body" fixes are helpful, but accidental, and dependent on another bug - the request schema for multiple expansions for the same endpoint overwrites each other, with last generated wins, and the generation is simply happening in a more convenient order in this version of the code.

### CODE REVIEW

File: sdk/framework/openapi.go [hunk 1]
```diff
@@ -575,84 +565,188 @@ func specialPathMatch(path string, specialPaths []string) bool {
...
-	matches := altRe.FindAllStringSubmatch(pattern, -1)
-	if len(matches) > 0 {
-		paths = []string{matches[0][1], matches[0][2]}
-	} else {
-		paths = []string{pattern}
+	paths, err := collectPathsFromRegexpAST(rx)
+	if err != nil {
+		// Pattern cannot be transformed into sensible OpenAPI paths, so drop it entirely.
+		// See lengthier comment inside collectPathsFromRegexpASTInternal below for more detailed discussion.
+		return nil
```
Comment (maxb) [inline sdk/framework/openapi.go:581]: I was undecided as to whether I should add trace-level logging at this point.

On the plus side: It makes it easier for plugin developers to find out this condition is being hit.

On the minus side: It is additional logging which is uninteresting to server operators, as there is nothing that can be done to change it other than rebuilding the Vault or plugin binary, and it will trigger **every** time `sys/internal/specs/openapi` or any relevant HelpOperation is invoked.

One alternative approach here would be to move the check to Backend.init, which is already set up to panic on initialisation if a backend author writes an empty or uncompilable path pattern - this could be expanded to include impossible-to-OpenAPI patterns not also marked as Unpublished. (I furthermore have another open PR, #18492, which seeks to add a check for CreateOperation being defined without an ExistenceCheck at the same point.)

File: sdk/framework/openapi.go [hunk 2]
```diff
@@ -575,84 +565,188 @@ func specialPathMatch(path string, specialPaths []string) bool {
...
 
-	// Expand all optional regex elements into two paths. This approach is really only useful up to 2 optional
-	// groups, but we probably don't want to deal with the exponential increase beyond that anyway.
-	for i := 0; i < len(paths); i++ {
-		p := paths[i]
-
-		// match is a 2-element slice that will have a start and end index
-		// for the left-most match of a regex of form: (lease/)?
-		match := optRe.FindStringIndex(p)
+	return paths
```
Comment (maxb) [inline sdk/framework/openapi.go:584]: I considered adding a trace-level log line to document the inputs and outputs of expandPattern:
```
logger.Trace("OpenAPI generator expanded regexp pattern", "n", len(paths), "regexp", pattern, "openapi", paths)
```

However, I decided that whilst this was incredibly useful whilst working on this PR, it would be too noisy to dump the entire list of all paths mounted in Vault to the logs every time `sys/internal/specs/openapi` was invoked, along with smaller subsets when HelpOperations were invoked.

File: sdk/framework/openapi_test.go [hunk 3]
```diff
@@ -18,75 +18,6 @@ import (
 )
 
 func TestOpenAPI_Regex(t *testing.T) {
-	t.Run("Required", func(t *testing.T) {
```
Comment (lursu) [inline sdk/framework/openapi_test.go:21]: Are all of these tests just not doing anything any more, or is there a need for more test cases to be added back in place of these?

Comment (maxb) [reply sdk/framework/openapi_test.go:21]: All of the tests being deleted, test the behaviour of various ad-hoc regexps, which were being used to parse other regexps (!).

They have all been deleted, and their job replaced by `regexp/syntax` from the Go standard library.

The new code that has been written to process the output of the stdlib's `regexp/syntax` is already well-exercised by the existing `TestOpenAPI_ExpandPattern` - although, I could add some additional inputs and expected outputs to that test, which would fail with the old implementation, but pass with this rewritten one.

File: sdk/framework/openapi.go [hunk 4]
```diff
@@ -575,84 +565,188 @@ func specialPathMatch(path string, specialPaths []string) bool {
...
+	//     OpStar         - i.e. *
+	//     OpPlus         - i.e. +
+	//     OpRepeat       - i.e. {N}, {N,M}, etc.
+	//
+	// In any of these conditions, there is no sensible translation of the path to OpenAPI syntax. (Note, this only
+	// applies to these appearing outside of a named capture group, otherwise they are handled in the previous case.)
+	//
+	// At the time of writing, the only pattern in the builtin Vault plugins that hits this codepath is the ".*"
+	// pattern in the KVv2 secrets engine, which is not a valid path, but rather, is a catch-all used to implement
+	// custom error handling behaviour to guide users who attempt to treat a KVv2 as a KVv2. It is already marked as
```
Comment (averche) [inline sdk/framework/openapi.go:740]:
```suggestion
	// custom error handling behaviour to guide users who attempt to treat a KVv2 as a KVv1. It is already marked as
```

Was that the intended comment?

File: sdk/framework/openapi.go (hunk 1 above)
Comment (averche) [reply sdk/framework/openapi.go:581]: Perhaps a reasonable compromise could be added to change [this error](
https://github.com/hashicorp/vault/pull/18554/files#diff-0cdfd38aed5eef1c1303f1d294d382c1202b6035ab35e6687f8f76b24834fe97R745-R746):

```go
return nil, fmt.Errorf("pattern could not be translated for OpenAPI due to %v operation", rx.Op)
```

into a named error and then capturing it here with `if errors.Is(...) { return nil }`. The advantage of this approach is that the code will be explicit about the intention of skipping specific regex operations. If `collectPathsFromRegexpASTInternal` is modified in the future to return other errors, those will be propagated correctly.

File: sdk/framework/openapi.go [hunk 5]
```diff
@@ -575,84 +565,188 @@ func specialPathMatch(path string, specialPaths []string) bool {
...
 	}
+	return paths, nil
+}
 
-	// Replace named parameters (?P<foo>) with {foo}
-	var replacedPaths []string
+func collectPathsFromRegexpASTInternal(rx *syntax.Regexp, appendingTo []*pathCollector) ([]*pathCollector, error) {
+	var err error
+
+	switch rx.Op {
```
Comment (averche) [inline sdk/framework/openapi.go:622]: Nit on code organization: it's a little hard to tell that these cases fall through to `return appendingTo, nil`. Perhaps refactoring some of the larger case blocks into their own functions could help. It may be just me not being able to parse these correctly so I'm OK to keep it as is as well.

File: sdk/framework/openapi_test.go (hunk 3 above)
Comment (averche) [reply sdk/framework/openapi_test.go:21]: >  I could add some additional inputs and expected outputs to that test, which would fail with the old implementation, but pass with this rewritten one.

These would be awesome! I would also love to see some of the edge cases tested like ".*" that you mentioned in the comments.

**Review by averche — COMMENTED** [review]
Overall I love this approach, I think it will be a great improvement to the stability of the generated OpenAPI output!

File: sdk/framework/openapi.go (hunk 5 above)
Comment (maxb) [reply sdk/framework/openapi.go:602]: You are not the first person to comment that my preferred code style leans towards big functions, so I did think hard about this. My rationale for doing it this way, is that when you have code that is only used once, in a specific place in the control flow, then factoring it out into a separate function can remove the easily visible evidence that it is in fact only used once in that specific control flow.

Since many of the cases are small, with only OpCapture, OpQuest and OpAlternate being big enough even consider factoring them out, I'd rather not introduce the inconsistency of most Op types being handled in-situ and just a few separated out.

What I can do, and arguably should have done in the first place, is provide a few lines of comment at the top of the switch, to guide someone reading the code top-to-bottom to an overall understanding:

```suggestion
	// Depending on the type of this regexp AST node (its Op, i.e. operation), figure out whether it contributes any
	// characters to the URL path, and whether we need to recurse through child AST nodes.
	//
	// Each element of the appendingTo slice tracks a separate path, defined by the alternatives chosen when traversing
	// the | and ? conditional regexp features, and new elements are added as each of these features are traversed.
	//
	// To share this slice across multiple recursive calls of this function, it is passed down as a parameter to each
	// recursive call, potentially modified throughout this switch block, and passed back up as a return value at the
	// end of this function - the parent call uses the return value to update its own local variable.
	switch rx.Op {
```

File: sdk/framework/openapi.go [hunk 6]
```diff
@@ -575,84 +565,188 @@ func specialPathMatch(path string, specialPaths []string) bool {
...
-			expandedRoots = append(expandedRoots, expandPattern(root+match[2])...)
-		}
-		return expandedRoots
+	// Happily, the Go regexp library exposes its underlying "parse to AST" functionality, so we can rely on that to do
+	// the hard work of interpreting the regexp syntax.
+	rx, err := syntax.Parse(pattern, syntax.Perl)
+	if err != nil {
+		// This should be impossible to reach, since regexps have previously been compiled with MustCompile in
+		// Backend.init.
+		panic(err)
```
[the remark this answers is not in the document]
Comment (maxb) [reply sdk/framework/openapi.go:554]: > Is there a possibility that the regex pattern scanned here does not come from `Backend.init`

The assurance comes from https://github.com/hashicorp/vault/blob/04b2461c91a86f4543d579c3895cdfdaf19387f8/sdk/framework/openapi.go#L239 explicitly passing in the value from the `Pattern` field of a `framework.Path` struct.

> or is not already compiled for some reason?

This is safe because you can't get to this code without being in a request handling context, meaning you've already traversed the start of `sdk/framework.(*Backend).HandleRequest` which has already called `sdk/framework.(*Backend).init` which has already panicked if the regexp was invalid:
https://github.com/hashicorp/vault/blob/04b2461c91a86f4543d579c3895cdfdaf19387f8/sdk/framework/backend.go#L472

Given earlier code will already have panicked, I don't think there's a need to write error handling logic that won't be invoked.

To my mind, this is a good application of the principal that panic is absolutely not appropriate for handling mistakes arising at runtime, but is appropriate when the programmer asserts that something should never happen, but still provides defined behaviour for when what shouldn't happen, does, due to a coding bug.

> I'm not sure whether Vault will just crash on a `panic` or recover in some way but it's probably not great regardless.

Since we're within the code flow of Go's `net/http` request handling, it traps the panic, logs a `http: panic serving` (or `http2: panic serving`) log message, and then closes the connection (HTTP/1) or returns an `INTERNAL_ERROR` status (HTTP/2).

The wider operation of the Vault server is not impacted, just the individual OpenAPI-related request fails.

[the remark this answers is not in the document]
Comment (averche) [reply sdk/framework/openapi.go:554]: Thanks for the detailed explanation and context 👍

File: sdk/framework/openapi.go (hunk 1 above)
Comment (maxb) [reply sdk/framework/openapi.go]: Done!

File: sdk/framework/openapi_test.go (hunk 3 above)
Comment (maxb) [reply sdk/framework/openapi_test.go:21]: Done!

File: vault/logical_system_test.go [hunk 7]
```diff
@@ -3618,158 +3618,130 @@ func TestSystemBackend_InternalUIMount(t *testing.T) {
...
-	}
-
-	// Simple check of response size (which is much larger than most
-	// Vault responses), mainly to catch mass omission of expected path data.
-	const minLen = 70000
-	if len(body) < minLen {
-		t.Fatalf("response size too small; expected: min %d, actual: %d", minLen, len(body))
-	}
-}
-
```
Comment (maxb) [inline vault/logical_system_test.go:3673]: Note for reviewer: this test is being removed because it was a **partial** copy of the next test, just changed to have generic_mount_paths=true.

Since I needed to make changes, and didn't want to have to update both copies of the duplicated code, I resolved the duplication.

File: vault/logical_system_test.go [hunk 8]
```diff
@@ -3618,158 +3618,130 @@ func TestSystemBackend_InternalUIMount(t *testing.T) {
...
 func TestSystemBackend_OpenAPI(t *testing.T) {
 	_, b, rootToken := testCoreSystemBackend(t)
-	var oapi map[string]interface{}
```
Comment (maxb) [inline vault/logical_system_test.go:3676]: Note for reviewer: You're going to want to view this part of the diff ignoring whitespace.

I noticed there was potential cross-talk between local variables in different parts of this function, so I introduced enclosing scopes so each part of the function is defining its own local variables.

File: vault/logical_system_test.go [hunk 9]
```diff
@@ -3618,158 +3618,130 @@ func TestSystemBackend_InternalUIMount(t *testing.T) {
...
-			t.Fatalf("didn't find expected path %q.", path)
+		pathSamples := []struct {
+			path        string
+			tag         string
+			unpublished bool
+		}{
+			{path: "/auth/token/lookup", tag: "auth"},
+			{path: "/cubbyhole/{path}", tag: "secrets"},
+			{path: "/identity/group/id", tag: "identity"},
+			{path: expectedSecretPrefix + "^.*$", unpublished: true},
```
Comment (maxb) [inline vault/logical_system_test.go:3697]: Note for reviewer: This `secret` thing here is actually neither a KV v1 nor a KV v2, it's actually the builtin passthrough backend within the Vault core, which has its own path regexp which is different to the real KV v1 that users use.

You can see here that the old code generated a path of `.*` (because it strips out the anchor metacharacters), whereas the new code leaves them in, giving `^.*$` - I think that's an accidental improvement, as it makes it even more clear this is a weird edge case.

Since the new code forces operations whose regexps can't be successfully translated to OpenAPI patterns to be unpublished, the test expectations arae being updated accordingly.

**Comment by maxb** [comment]
All feedback addressed and CircleCI is now happy.

**Review by averche — APPROVED** [review]
LGTM 👍 This is an awesome contribution! Thanks for fixing all the tests & adding new ones.
