### PR TITLE
UI - auth method edit

### LINKED ISSUE #4769: UI doesn't allow editing of auth methods
**Describe the bug**
New authentication methods cannot be properly edited once created.

**To Reproduce**
1. Enable a new authentication method (eg LDAP).
2. Enter details (eg under sections 'LDAP Options', 'Customize User Search', etc).
3. Click 'Enable Method'
4. Edit Auth Method.
5. Only 'Method Options' is available.

**Expected behavior**
To get the same options as when auth method was enabled. If the values of the stored fields cannot be retrieved, then the fields should be displayed with the contents of '<unable to retrieve>' or similar.

**Environment:**
version 0.10.1 on Linux x86_64

Vault server configuration file(s):
n/a (running in dev mode)
screenshot_2018-06-14_14-39-25
screenshot_2018-06-14_14-32-42
screenshot_2018-06-14_14-31-59

### PR DESCRIPTION
**Pull request by meirish**
Some auth methods were erroneously left out of the helper so they wouldn't show up on the edit pages. This fixes that and adds some tests ensuring they're there in the application! 

Fixes #4769

### CODE REVIEW

File: ui/tests/acceptance/settings/auth/configure/section-test.js [hunk 1]
```diff
@@ -37,3 +42,16 @@ test('it can save options', function(assert) {
...
 });
+
+['aws', 'azure', 'gcp', 'github', 'kubernetes', 'ldap', 'okta', 'radius'].forEach(function(type) {
+  test(`it shows tabs for auth method: ${type}`, assert => {
+    let path = `${type}-${Date.now()}`;
+    cli.consoleInput(`write sys/auth/${path} type=${type}`);
+    cli.enter();
+    indexPage.visit({ path });
+    andThen(() => {
+      let numTabs = type === 'aws' ? 4 : 2;
```
Comment (alisdair) [inline ui/tests/acceptance/settings/auth/configure/section-test.js]: Looking at the data structure in the helper, it took me a few minutes to figure out why this wasn't `? 3 : 1` instead: https://github.com/hashicorp/vault/blob/9b91394a68a8ba774d9ea2bb3a34be70fd25d1d1/ui/app/helpers/tabs-for-auth-section.js#L67-L74

Maybe a comment in the test explaining would help clarify?

Comment (meirish) [reply ui/tests/acceptance/settings/auth/configure/section-test.js]: Added, thanks!
