### PR TITLE
UI aws engine tweaks

### LINKED ISSUE #5291: Vault-UI requires update permission to read AWS creds
**Describe the bug**
In 0.11.0 generating AWS credentials from the UI ie https://host/ui/vault/secrets/aws/credentials/role reverted to requiring update permission in addition to the normal read permission.

**To Reproduce**
1. Create aws secret engine
2. Add a aws role
3. Create a policy with read permission to `aws/creds/role`
3. Log into UI with that policy active and try to generate aws credentials.
4. Receive error `Error 1 error occurred: * permission denied`

It will work if the update permission is added to `aws/creds/role`

**Expected behavior**
AWS Credentials are generated.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.0 
* Vault CLI Version (retrieve with `vault version`): 0.11.0 
* Server Operating System/Architecture: Centos 7 / AMD64

Vault server configuration file(s):

```hcl
listener "tcp" {
  address         = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file   = "/opt/vault/tls/vault.crt.pem"
  tls_key_file    = "/opt/vault/tls/vault.key.pem"
}
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
  scheme  = "http"
  service = "vault"

  # HA settings
  cluster_addr  = "https://10.64.10.55:8201"
  api_addr      = "https://10.64.10.55:8201"
}
ui = true
```

### PR DESCRIPTION
**Pull request by meirish**
Instead of trying to guess the type of credential we're generating, we now have the user select. This will then change the form inputs to have the relevant fields.

Additionally, this fixes and issue where generating an IAM user did a POST (update capability) instead of a GET (read capability). Fixes #5291 

screen shot 2018-09-06 at 4 19 09 pm
screen shot 2018-09-06 at 4 19 18 pm
screen shot 2018-09-06 at 4 19 28 pm

### CODE REVIEW

File: ui/app/helpers/path-or-array.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import Ember from 'ember';
+
+export function pathOrArray([maybeArray, target]) {
+  if (Array.isArray(maybeArray)) {
+    return maybeArray;
+  }
+  return target.get(maybeArray);
+}
+
+export default Ember.Helper.helper(pathOrArray);
```
Comment (johncowen) [inline ui/app/helpers/path-or-array.js]: hehe, this reminds me of something I've just done in one of my own PR's 🤔 make me think I should expand on what I've done myself - I was checking for a number, but I figure there it's relatively common to type check things in helpers. Anyway, just thinking out loud really

File: ui/tests/unit/adapters/aws-credential-test.js [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+  test(`aws-credential: ${description}`, function(assert) {
+    assert.expect(3);
+    let adapter = this.subject();
+    adapter.createRecord(...args);
+    let { method, url, requestBody } = this.server.handledRequests[0];
+    assert.equal(url, '/v1/aws/creds/foo', `calls the correct url`);
+    assert.equal(method, expectedMethod, `${description} uses the correct http verb: ${expectedMethod}`);
+    assert.equal(requestBody, JSON.stringify(expectedRequestBody));
+  });
+});
```
Comment (johncowen) [inline ui/tests/unit/adapters/aws-credential-test.js]: Bit nitpicky this, but I've also noticed this elsewhere. Would you call this a unit test?

It seems to be testing more than a single isolated unit? It looks like this is testing `urlForCreateRecord` and also `createRecord`.

I've just had a quick snoop around the code here, plus a couple of different `ember-data` versions, and it looks like it's impossible to dynamically set the request method without using `ds-ajax-improved` so you have to overwrite the entire `createRecord` method, so I can see why you've done that here.

Could you overwrite `urlForCreateRecord` and then unit test that? Then you could stub `urlForCreateRecord` and `this.ajax` to unit test `createRecord`. Alternatively move this to an integration and/or acceptance test?

**Comment by johncowen** [comment]
Hey @meirish !

I left a few things inline above, no biggies there from a code point of view I don't think.

I wasn't quite sure how to test it myself (so manually), but I think I figured it and found a found related bugs, neither of which are huge.

1. If you type a character (so not a number) into the TTL field and change the select menu you get an error:

screen shot 2018-09-17 at 11 55 52

2. The tooltip pointer thing is pointing in the wrong place - not sure. I'm going to have this problem in Consul very soon 😂 . I would guess it's difficult to get this exact maybe, even if the pointer thing was on the left it would look better?

screen shot 2018-09-17 at 11 55 22

3. Tiny one this one but the select down arrows look misplaced?

screen shot 2018-09-17 at 11 56 55

File: ui/app/adapters/aws-credential.js [hunk 3]
```diff
@@ -4,15 +4,21 @@ export default ApplicationAdapter.extend({
...
+    let options;
     let data = {};
-    if (ttl) {
-      data.ttl = ttl;
+    if (roleType === 'iam_user') {
+      method = 'GET';
+    } else {
+      if (ttl) {
+        data.ttl = ttl;
+      }
```
[the remark this answers is not in the document]
Comment (meirish) [reply ui/app/adapters/aws-credential.js]: Oops! Good catch - will update that. /me shakes fist at JavaScript

File: ui/tests/unit/adapters/aws-credential-test.js (hunk 2 above)
Comment (meirish) [reply ui/tests/unit/adapters/aws-credential-test.js]: Ah yeah fair, these are probably more accurately described as integration tests since they're testing both the adapter and the serializer usually. I'll probably change that after all of the ember updates get in since the 3.0 update rewrites most of the tests for the new style async/await tests: https://github.com/hashicorp/vault/pull/5342

File: ui/app/helpers/path-or-array.js (hunk 1 above)
Comment (johncowen) [reply ui/app/helpers/path-or-array.js]: Here's the link:

https://github.com/hashicorp/consul/pull/4677/files#diff-84d5eca0802aae16295fd808d3a95441

This is the 'possible beginnings' of something, something simple but looks like it might be useful, need to think about it a bit more tho. It's very specific to helpers, not sure whether to keep it that way or not at the moment. I half think its so simple its not wort hit, but then again with helpers it might be.

**Comment by meirish** [comment]
@johncowen Thanks for the review! Oof that ttl bug is gnarly :(, I'll look into that. I think the quick fix might be just restricting the input to numbers, but will then look at adding JS verification as well. 

Ha those tooltips are the bane of my existence - it's actually an ember component though and it should be switching the class based on the layout to flip the arrow to the other side but that seems to have broken at some point. I'll check it out.

For 3, @joshuaogle fixed that here: https://github.com/hashicorp/vault/pull/5282 I think this must not be up to date since that merged.

**Comment by johncowen** [comment]
Cool - hehe I'm still reeling from my ACL token `null` bug, so I feel your pain! :joy:

Shout me when you commit those up and I can give it the 👍

File: ui/app/adapters/aws-credential.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (meirish) [reply ui/app/adapters/aws-credential.js]: I changed this check, but coming out of the TTL picker it won't be zero because it'll also have the unit attached. Still better to check undefined though 😅

File: ui/tests/unit/adapters/aws-credential-test.js (hunk 2 above)
Comment (meirish) [reply ui/tests/unit/adapters/aws-credential-test.js]: That's merged now, going to move them over in another PR!

**Comment by meirish** [comment]
@johncowen sorry that took a bit, but got back around to this! 

I fixed the tooltip positioning: 
screen shot 2018-09-26 at 10 14 05 am
screen shot 2018-09-26 at 10 14 22 am

And invalid TTL input will now show an error like this (and not call the onChange action with invalid values): 
screen shot 2018-09-26 at 10 14 37 am

**Comment by meirish** [comment]
Ember tests are green so going to merge to get this in the next release - thanks for the review!

**Comment by johncowen** [comment]
Ah doh, sorry didn't realise that commit in there, FWIW just tried it and all looks good to me, schweet!
