### PR TITLE
Fix aspects of `auth/token/create` request parsing

### LINKED ISSUE #18550: vault `/auth/token/create` returns `ignoring unrecognized parameters [meta]` when creating token
**Describe the bug**
- vault `/auth/token/create` returns `ignoring unrecognized parameters [meta]` when creating token
- according to [docs](https://developer.hashicorp.com/vault/api-docs/auth/token#create-token) we can use meta  in payload
- the meta value is being set (see curl response below) so im unsure why the warning is  included in the response

**To Reproduce**
1. [send this payload](https://github.com/nirv-ai/configs/blob/develop/vault/role/admin_role_vault.json)
2. to this endpoint `/auth/token/create`
  1. see warning about meta, but confirm metadata includes appropriate value

**Expected behavior**
- no warnings are returned if request payload matches api spec

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
# @see https://developer.hashicorp.com/vault/docs/configuration

default_lease_ttl = "7d"
default_max_request_duration = "30s"
disable_cahe = false
disable_mlock = false
enable_response_header_hostname = true
enable_response_header_raft_node_id = true
log_format= "json"
max_lease_ttl = "30d"
raw_storage_endpoint = false
ui = true # requires at least 1 listener stanza

storage "raft" {
  path    = "/vault/data"
  node_id = "node1"
}


# advertise the non-loopback interface
api_addr = "https://127.0.0.1:8300"
cluster_addr = "https://127.0.0.1:8301"

listener "tcp" {
  address = "0.0.0.0:8300" # provides access to vault UI
  tls_cert_file = "/etc/ssl/certs/live/dev.nirv.ai/fullchain.pem"
  tls_key_file = "/etc/ssl/certs/live/dev.nirv.ai/privkey.pem"
  tls_disable = false
}


############################# todo
# plugin_directory
# plugin_file_uid
# plugin_file_permissions
// telemetry {
//   statsite_address = "127.0.0.1:8125"
//   disable_hostname = true
// }
// seal "transit" { @see https://developer.hashicorp.com/vault/docs/configuration/seal/transit
// }

```

**Additional context**
```sh
01:16 PM (develop *|u=) 
$ ./script.vault.sh create token child config/vault/vault_admin/admin_role_vault.json

creating child token with payload: /home/poop/git/private/nirv/scripts/config/vault/vault_admin/admin_role_vault.json

[DEBUG] SCRIPT.VAULT.SH
------------
[url]: https://dev.nirv.ai:8300/v1/auth/token/create
[rest]: -H X-Vault-Token: pooperscooper --data @/home/poop/git/private/nirv/scripts/config/vault/vault_admin/admin_role_vault.json

------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8300...
* Connected to dev.nirv.ai (127.0.0.1) port 8300 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS header, Certificate Status (22):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.2 (IN), TLS header, Finished (20):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
{ [45 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3817 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.2 (OUT), TLS header, Finished (20):
} [5 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
} [8 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=dev.nirv.ai
*  start date: Dec 14 07:03:19 2022 GMT
*  expire date: Mar 14 07:03:18 2023 GMT
*  subjectAltName: host "dev.nirv.ai" matched cert's "dev.nirv.ai"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x562fc76ade80)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
> POST /v1/auth/token/create HTTP/2
> Host: dev.nirv.ai:8300
> user-agent: curl/7.81.0
> accept: */*
> connection: close
> content-length: 203
> content-type: application/x-www-form-urlencoded
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [130 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* We are completely uploaded and fine
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
< HTTP/2 200 
< cache-control: no-store
< content-type: application/json
< strict-transport-security: max-age=31536000; includeSubDomains
< x-vault-hostname: dev.nirv.ai
< x-vault-raft-node-id: node1
< content-length: 671
< date: Sat, 24 Dec 2022 20:16:35 GMT
< 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
100   874  100   671  100   203   7983   2415 --:--:-- --:--:-- --:--:-- 10530
* Connection #0 to host dev.nirv.ai left intact
{
  "request_id": "37033ef6-8d02-8736-3d4d-8a7be4b12ccd",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": null,
  "wrap_info": null,
  "warnings": [
    "Policy \"admin_policy_vault\" does not exist",
    "Endpoint ignored these unrecognized parameters: [meta]"
  ],
  "auth": {
    "client_token": "merry.christmas",
    "accessor": "supa dupa fly",
    "policies": [
      "admin_policy_vault",
      "default"
    ],
    "token_policies": [
      "admin_policy_vault",
      "default"
    ],
    "metadata": {
      "created_by_root": "1"
    },
    "lease_duration": 2592000,
    "renewable": true,
    "entity_id": "",
    "token_type": "service",
    "orphan": false,
    "mfa_requirement": null,
    "num_uses": 0
  }
}
```

### PR DESCRIPTION
**Pull request by maxb**
Fixes #18550

Currently, the `auth/token/create` family of APIs (`create`, `create-orphan`, `create/{role}`) does non-standard parsing of requests, by directly using `mapstructure.WeakDecode(request.Data, ...)` instead of using the standard `framework.FieldData` abstraction.

Furthermore, the fields declared for these APIs are incorrect, leading to inappropriate OpenAPI generation, and inappropriate warnings about ignored parameters.

Detailed changes:

* Factor out triplicated definitions of common fields across these three APIs.

* Remove incorrect `role_name` field from `create-orphan`.

* Add missing `lease` deprecated field.

* Rename incorrectly named `metadata` field to `meta`, and change from `TypeMap` to `TypeKVPairs` to reflect actual underlying Go type is `map[string]string`.

* Remove entirely incorrect `format` field.

* Add declarative `Default: true` to `renewable` field, to match behaviour currently implemented in code.

* Having fixed the field definitions to match current usage, remove the secondary decoding of the request via `mapstructure` inside `handleCreateCommon`, and migrate to using `FieldData` APIs like a normal operation function.

### CODE REVIEW

**Comment by maxb** [comment]
Hi @averche ,

As this PR relates to fixing field definitions that will affect OpenAPI correctness, and so the correctness of the new generated client libraries, I wonder if it is something you might be interested in looking into?

**Comment by hghaf099** [comment]
@maxb This is a great PR and I would like to make it ready to be merged in. Would you please rebase with main such that the failing tests are fixed?

**Comment by maxb** [comment]
I've updated the branch, but it looks like there are quite a few new PR checks which don't work for community PRs, due to credentials limited to branches within the main repo.

**Comment by maxb** [comment]
@hghaf099 Thanks for your interest in my PR, what needs to happen next?

File: vault/token_store.go [hunk 1]
```diff
@@ -2890,7 +2758,16 @@ func (ts *TokenStore) handleCreateCommon(ctx context.Context, req *logical.Reque
 		explicitEntityID = entity.ID
 	}
 
-	// Setup the token entry
+	// By using GetOk here, we set TokenEntry.Meta to nil instead of an empty map, when no meta was passed in the
+	// token creation API call. This maintains closer compatibility with previous behaviour of Vault, helping to avoid
+	// user surprise, and saving the need to update quite a few tests which expect this to be nil in such a case.
```
Comment (averche) [inline vault/token_store.go:2763]: This comment seems more useful for the PR reviewer rather than for the future readers/maintainers of the code. Consider removing it or at least shortening it to the first sentence (since `GetOk` seems to be a fairly established pattern throughout the code and the code below is quite self-explanatory).

File: vault/token_store.go [hunk 2]
```diff
@@ -138,6 +137,77 @@ var (
...
+
+	fieldsForCreateWithRole := map[string]*framework.FieldSchema{
+		"role_name": {
+			Type:        framework.TypeString,
+			Description: "Name of the role",
+		},
+	}
+	for k, v := range commonFieldsForCreate {
+		fieldsForCreateWithRole[k] = v
+	}
```
Comment (averche) [inline vault/token_store.go:209]: Nit: it might be cleaner to use maps.Copy here but I'm OK leaving it as is since `maps` is still an `x/exp` package.

**Review by averche — APPROVED** [review]
Hi @maxb!

Sorry did not see the tag till today. This PR is great both for the OpenAPI correctness and for bringing the code in line with the current Vault conventions! I left a couple of nit comments. Otherwise, LGTM!

File: vault/token_store.go (hunk 2 above)
Comment (maxb) [reply vault/token_store.go:209]: Since `x/exp/maps` has not so far been used anywhere in Vault, and the `x/exp` warning of lack of compatibility is rather strongly worded, I'd prefer not to introduce it to save just a couple of lines of code.

File: vault/token_store.go (hunk 1 above)
Comment (maxb) [reply vault/token_store.go:2763]: Well - the point I was trying to preserve for future readers, was why this particular parameter is using `GetOk` and a follow-up `if ok`, rather than just using the shorter `Get` to do it all on one line - like most of the other fields in this function do - and in fact, how I wrote the code originally.

Essentially, I'm recording why this code is not written in the natural way one would write it, if compatibility wasn't an issue.

`GetOk` is _usually_ for when code needs to get a field which might not be present in the request schema - but here it is being used solely to avoid coercing nil to an empty map.

Comment (maxb) [reply vault/token_store.go]: Comment rephrased to more directly express the core point.

**Review by averche — APPROVED** [review]
