### PR TITLE
Detect and bypass cycles during token revocation

### LINKED ISSUE #4803: Vault Crashes OOM
**Describe the bug**
When a Vault node in cluster of 6 with consul back-end becomes leader, the CPU Load and Memory increases to the point is crashes because of OOM.

**To Reproduce**
Vault node becomes leader and is crashing with:
```fatal error: runtime: out of memory```

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    5
Threshold       3
Version         0.10.1
Cluster Name    vault-cluster-
Cluster ID      
HA Enabled      true
HA Cluster      https://
HA Mode         active

* Server Operating System/Architecture:

Docker version 18.03.1-ce, build 9ee9f40
4.14.48-coreos-r2

Vault server configuration file(s):
```hcl
{"storage": {"consul": {"address": ":8500", "path": "vault", "token": "${consul_token}" }}, "listener": { "tcp": { "address": "0.0.0.0:443", "tls_cert_file": "/vault/certs/tls.crt", "tls_key_file": "/vault/certs/tls.key" }}, "disable_cache": "true", "disable_mlock": "true", "ui": "true"}
```

**Additional context**
Consul back-end : Consul 1.1.0
Crash log:  [vault_crash.log](https://github.com/hashicorp/vault/files/2119290/vault_crash.log)
Prometheus Monitoring Graph: 
vault

### PR DESCRIPTION
**Pull request by kalafut**
Fixes #4803

### CODE REVIEW

File: vault/token_store.go [hunk 1]
```diff
@@ -1200,16 +1200,31 @@ func (ts *TokenStore) revokeTree(ctx context.Context, id string) error {
...
 		}
+
+		// Filter the child list to remove any items that have ever been in the dfs queue.
+		// This is a robustness check, as a parent/child cycle can lead to an OOM crash.
+		children := make([]string, 0, len(childrenRaw))
+		for _, child := range childrenRaw {
+			if _, seen := seenIDs[child]; !seen {
+				children = append(children, child)
+			} else {
+				ts.Logger().Warn("token cycle found", "token", child)
```
Comment (briankassouf) [inline vault/token_store.go]: It might be best to remove the key that is causing the cycle here, otherwise we will lose all reference to this key and it will live forever

Comment (kalafut) [reply vault/token_store.go]: If we delete the key here, the depth-first order is bypassed, which could break references if the whole operation doesn't complete. e.g. if ID `root` showed up as a child and we deleted it, revoke fails for some reason, now there are possibly tokens with `root` as an ancestor but `root` is gone.

But as to whether everything gets cleaned up the way it's written, I _think_ it does:

1. If the ID is showing up as as "seen", then it was definitely added to the dfs queue (line 1248).
2. Eventually it was or will be at the front of the queue, with no more of its own children to delete, and it will be deleted.

I'm happy to add tests of any corner cases for this.

Comment (briankassouf) [reply vault/token_store.go]: I think it's worth testing out, I could see a situation where `parentPrefix + id + "/" + child` is never cleaned up if the child token has the parent encoded incorrectly. Which if we are in this situation is likely.

Comment (briankassouf) [reply vault/token_store.go]: Also i wasn't proposing deleting the whole token here, just the extra parent reference that is causing it to be seen more than once. The previously seen version of the token will still allow for it to be cleaned up.

Comment (kalafut) [reply vault/token_store.go]: Yep, adding a delete of the parent reference here is a good improvement.
