### PR TITLE
Fix Cluster object being returned as nil when unsealed

### LINKED ISSUE #1708: Potential TLS issues in rc2
https://groups.google.com/d/msgid/vault-tool/b942b61e-6c7c-4080-946b-433af7c3ad3b%40googlegroups.com

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #1708

### CODE REVIEW

File: vault/cluster.go [hunk 1]
```diff
@@ -23,21 +23,23 @@ type Cluster struct {
...
+// input. This method errors out when Vault is sealed. This function never
+// returns a nil Cluster object.
 func (c *Core) Cluster() (*Cluster, error) {
+	var cluster Cluster
+
 	// Fetch the storage entry. This call fails when Vault is sealed.
 	entry, err := c.barrier.Get(coreLocalClusterInfoPath)
 	if err != nil {
-		return nil, err
+		return &cluster, err
```
Comment (jefferai) [inline vault/cluster.go]: I actually think that this should return nil. On errors, we want the error to be handled; if the error isn't being handled, trying to operate on a nil pointer is a good way to ensure that people realize that they aren't handling the error (assuming it's caught in tests :-D )

File: vault/cluster.go [hunk 2]
```diff
@@ -23,21 +23,23 @@ type Cluster struct {
...
 	if entry == nil {
-		return nil, nil
+		return &cluster, nil
 	}
 
 	// Decode the cluster information
-	var cluster Cluster
 	if err = jsonutil.DecodeJSON(entry.Value, &cluster); err != nil {
-		return nil, fmt.Errorf("failed to decode cluster details: %v", err)
+		return &cluster, fmt.Errorf("failed to decode cluster details: %v", err)
```
Comment (jefferai) [inline vault/cluster.go]: Same here.

File: http/sys_seal.go [hunk 3]
```diff
@@ -155,16 +155,10 @@ func handleSysSealStatusRaw(core *vault.Core, w http.ResponseWriter, r *http.Req
 	var clusterName, clusterID string
 	if !sealed {
 		cluster, err := core.Cluster()
-
-		// Don't set the cluster details in the status when Vault is sealed
 		if err != nil {
 			respondError(w, http.StatusInternalServerError, err)
 			return
 		}
-		if cluster == nil {
```
Comment (jefferai) [inline http/sys_seal.go]: It's not a bad check to leave in just in case something changes, just put an actual error message in there. :-)
