### PR TITLE
core: Don't shutdown if key upgrades fail due to canceled context

### LINKED ISSUE #7065: Catch performKeyUpgrades context canceled errors
Standbys that fail to perform key upgrades shut themselves down, this is because they no longer have the latest keyring or master key and would be unable to perform certain decryptions. However if `performKeyUpgrades` fails due to a context canceled error we should not shutdown since this likely just means we are changing state.

### PR DESCRIPTION
**Pull request by briankassouf**
fixes #7065

### CODE REVIEW

File: vault/ha.go [hunk 1]
```diff
@@ -472,18 +473,31 @@ func (c *Core) waitForLeadership(newLeaderCh chan func(), manualStepDownCh, stop
...
-				// We call this in a goroutine so that we can give up the
-				// statelock and have this shut us down; sealInternal has a
-				// workflow where it watches for the stopCh to close so we want
-				// to return from here
 				c.logger.Error("error performing key upgrades", "error", err)
-				go c.Shutdown()
+
+				// If we fail due to anything other than a context canceled
+				// error we should shutdown as we may have the incorrect Keys.
+				if !strings.Contains(err.Error(), context.Canceled.Error()) {
```
Comment (jefferai) [inline vault/ha.go]: Thoughts on DeadlineExceeded? Probably also continue for now?

Comment (briankassouf) [reply vault/ha.go]: These contexts should never have deadlines

Comment (jefferai) [reply vault/ha.go]: That is fair. :-)
