### PR TITLE
Provide option to disable host key checking

### LINKED ISSUE #1322: Handle host checking in ssh command
If `vault ssh` command fails to establish a connection automatically because of not trusting the host machine, then throw an error with the same reason.

Also, provide an option in the command to disable host checking.

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #1322

### CODE REVIEW

**Comment by jefferai** [comment]
This looks good but I think might be nice to allow these to be specified in env vars. That way we can keep the `vault ssh` command more simple rather than requiring a lot of boilerplate, since most users will probably use the same value always.

**Comment by vishalnayak** [comment]
@jefferai That's right. I will add it.

File: command/ssh.go [hunk 1]
```diff
@@ -45,6 +47,15 @@ func (c *SSHCommand) Run(args []string) int {
 	if err := flags.Parse(args); err != nil {
 		return 1
 	}
+
+	if os.Getenv("VAULT_STRICT_HOST_KEY_CHECKING") != "" {
```
Comment (jefferai) [inline command/ssh.go]: Command line flags override env vars in Vault, but this has that logic flipped. Rather than set a default for the two parameters in the flags StringVars, check for the env var here, and if not set, and if the flag is empty, *then* set to the default.

File: command/ssh.go [hunk 2]
```diff
@@ -45,6 +47,15 @@ func (c *SSHCommand) Run(args []string) int {
...
+		strictHostKeyChecking = os.Getenv("VAULT_STRICT_HOST_KEY_CHECKING")
```
Comment (jefferai) [inline command/ssh.go]: I think the vars should be `VAULT_SSH_......` as they're specific to this command. I realize that they're rather long, but I don't think they'll be toggled often.

File: command/ssh.go (hunk 1 above)
Comment (vishalnayak) [inline command/ssh.go]: You are right. Done!

 I had referred to `DEV_ROOT_TOKEN_ID` way of doing things. It looks like that can take a change as well. If you agree I will give precedence to flags for `devRootTokenID` and `devListenAddress`, in a follow up PR.

File: command/ssh.go (hunk 2 above)
Comment (vishalnayak) [inline command/ssh.go]: Done!

**Comment by jefferai** [comment]
:+1:
