### PR TITLE
UI - upgrading generic secret engines to v2 format

### LINKED ISSUE #4740: Vault UI shows an empty list of secrets for KV v2 store after upgrade to 0.10.2
**Describe the bug**
I enabled versioning (KV v2) for a KV secret store on Vault v.0.10.0 and I was able to get a list of secrets and to read them in Vault UI and in CLI. 
After upgrade to v.0.10.2 I lost ability to get access to secrets in UI. Vault UI shows an empty list of secrets for secret/. If I use Vault CLI all secrets are in place.
After downgrade to Vault v.0.10.0  Vault UI works as expected and shows all secrets in secret/ (KV v2)

**To Reproduce**
1. Install Vault  v0.10.2
2. Enable versioning KV secret backend
3. Try to list secrets in secret/ on Vault UI

**Expected behavior**
I should see a list of secrets for KV v2 store in UI.

**Environment:**
* Vault Server Version 0.10.2
* Vault CLI Version 0.10.2
* Server Operating System/Architecture: Debian 8.7 in a Docker container

**Additional context**
Request log from UI for v0.10.0:
`{"time":"2018-06-11T13:34:59.633531278Z","type":"request","auth":{"client_token":"hmac-sha256:6a8aaf0335dca1238babe3808838416a363b07e1873ca09c9dfd80cff5a86c1a","accessor":"hmac-sha256:06ac7cb74b72b9afabad2561feb0beb5f43ad5ad9794084732376f66ab7d8304","display_name":"ldap-alexander.susha","policies":["admin-policy","default"],"metadata":{"username":"alexander.susha"},"entity_id":"1daa44a9-bb29-7fdd-50ad-c99939c7e0ba"},"request":{"id":"2b9e01c6-2a55-8254-10f1-12290c0d4278","operation":"list","client_token":"hmac-sha256:6a8aaf0335dca1238babe3808838416a363b07e1873ca09c9dfd80cff5a86c1a","client_token_accessor":"hmac-sha256:06ac7cb74b72b9afabad2561feb0beb5f43ad5ad9794084732376f66ab7d8304","path":"secret/metadata/","data":null,"policy_override":false,"remote_address":"x.x.x.x","wrap_ttl":0,"headers":{}},"error":""}`

Request log from UI for v0.10.2:
`{"time":"2018-06-11T13:24:05.756343265Z","type":"response","auth":{"client_token":"hmac-sha256:6a8aaf0335dca1238babe3808838416a363b07e1873ca09c9dfd80cff5a86c1a","accessor":"hmac-sha256:06ac7cb74b72b9afabad2561feb0beb5f43ad5ad9794084732376f66ab7d8304","display_name":"ldap-alexander.susha","policies":["admin-policy","default"],"metadata":{"username":"alexander.susha"},"entity_id":"1daa44a9-bb29-7fdd-50ad-c99939c7e0ba"},"request":{"id":"c95aa284-d31b-c9d0-f32d-6f0aae54c719","operation":"list","client_token":"hmac-sha256:6a8aaf0335dca1238babe3808838416a363b07e1873ca09c9dfd80cff5a86c1a","client_token_accessor":"hmac-sha256:06ac7cb74b72b9afabad2561feb0beb5f43ad5ad9794084732376f66ab7d8304","path":"secret/","data":null,"policy_override":false,"remote_address":"x.x.x.x","wrap_ttl":0,"headers":{}},"response":{"data":{"http_content_type":"hmac-sha256:b3cc9b71699bc2de0aed0cc59e3573dcffc52717849c6d69496c4d64f12ad9a3","http_raw_body":"hmac-sha256:1e2d1cb06efd93980c833b532e144cbd52b3d91b23af041d0df92a2b4447cb8f","http_status_code":404}},"error":""}
`

### PR DESCRIPTION
**Pull request by meirish**
Previously we were detecting version 2 of the KV mounts only if the type was "kv" and options.version was "2" - this didn't account for the legacy type of "generic" ("kv" was previously named "generic" and "generic" still works for backwards compatibility though you cannot mount a "generic" engine through the UI form any longer).

This PR fixes that. 

Note: the added tests did not work when using `-dev-leased-kv` flag that we are currently relying on for lease testing. Upgrading a generic mount would tune the version correctly, but leave the data in the old format. The lease tests have been skipped for now and we'll address that in a PR in the future.

Fixes #4740

### CODE REVIEW

File: ui/app/routes/vault/cluster/secrets/backend/secret-edit.js [hunk 1]
```diff
@@ -52,10 +52,11 @@ export default Ember.Route.extend(UnloadModelRoute, {
     };
     let backendModel = this.modelFor('vault.cluster.secrets.backend', backend);
     let defaultType = 'secret';
-    if (backendModel.get('type') === 'kv' && backendModel.get('options.version') === 2) {
+    let type = backendModel.get('type');
+    if ((type === 'generic' || type === 'kv') && backendModel.get('options.version') === 2) {
```
Comment (johncowen) [inline ui/app/routes/vault/cluster/secrets/backend/secret-edit.js]: Just a possible suggestion, you could possibly hoist this up and out as a util? Something similar to..
```
// obvs a more description name here, don't fully understand the context though, `isV2Secret` maybe?
function isSomething(model) {
  let type = model.get('type');
  return (type === 'generic' || type === 'kv') && model.get('options.version') === 2) 
}
// or more decoupled
function isSomething(type, version) {
  return (type === 'generic' || type === 'kv') && version === 2) 
}
```
You could then externalise the above and `import` it in the 3 places you are using it above, and have a simple unit test it in isolation also?
