### PR TITLE
Lazy-load plugin mounts

### LINKED ISSUE #3241: Vault crashes after unseal due to uninitialised tokenStore when using a custom plug-in
**Environment:**
Cluster of 3 nodes running on Ubuntu 14.04 with Cassandra storage backend.

* Vault Version: `Vault v0.8.1 ('a7105536d613c0dce40d5439ae88fe0c5271298e')` (Built from master, but the same issue occurred with the "stock" Vault v0.8.1 (`'8d76a41854608c547a233f2e6292ae5355154695'`) )

* Operating System/Architecture:
Ubuntu 14.04 - `Linux host 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Vault Config File:**
```
backend "cassandra" {
  hosts = "cassandra-ZZZ"
  protocol_version = 3
  connection_timeout = 600
}

ha_storage "etcd" {
  address = "http://XXX:2379"
  ha_enabled = 1
  etcd_api = "v3"
  redirect_addr = "http://YYY:8200"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}

plugin_directory = "/opt/vault/plugins"
```

**Startup Log Output:**

```
==> Vault server configuration:

              HA Storage: etcd
                     Cgo: disabled
         Cluster Address: YYY:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")
               Log Level: trace
                   Mlock: supported: true, enabled: true
        Redirect Address: YYY:8200
                 Storage: cassandra
                 Version: Vault v0.8.1
             Version Sha: a7105536d613c0dce40d5439ae88fe0c5271298e

==> Vault server started! Log data will stream in below:

[TRACE] physical/cache: creating LRU cache: size=32768
[WARN ] Failed to dial %s: %v; please retry. IP:2379 grpc: the connection is closing
[WARN ] Failed to dial %s: %v; please retry. IP:2379 grpc: the connection is closing
[WARN ] Failed to dial %s: %v; please retry. IP:2379 grpc: the connection is closing
[WARN ] Failed to dial %s: %v; please retry. IP:2379 grpc: the connection is closing
[WARN ] Failed to dial %s: %v; please retry. XXX:2379 grpc: the connection is closing
[WARN ] Failed to dial %s: %v; please retry. IP:2379 grpc: the connection is closing
[TRACE] cluster listener addresses synthesized: cluster_addresses=[0.0.0.0:8201]
[DEBUG] core: cannot unseal, not enough keys: keys=1 threshold=3 nonce=AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA
[DEBUG] core: cannot unseal, not enough keys: keys=2 threshold=3 nonce=AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA
[INFO ] core: vault is unsealed
[INFO ] core: entering standby mode
[INFO ] core: acquired lock, enabling active operation
[TRACE] core: generating cluster private key
[TRACE] core: generating local cluster certificate
[INFO ] core: post-unseal setup starting
[TRACE] core: clearing forwarding clients
[TRACE] core: done clearing forwarding clients
[INFO ] core: loaded wrapping token key
[INFO ] core: successfully mounted backend: type=generic path=secret/
[INFO ] core: successfully mounted backend: type=system path=sys/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15f6bf1]

goroutine 128 [running]:
github.com/hashicorp/vault/vault.(*TokenStore).Salt(0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/hashicorp/vault/vault/token_store.go:511 +0x41
github.com/hashicorp/vault/vault.(*TokenStore).SaltID(0x0, 0xc420392d80, 0x24, 0x0, 0x2, 0xed130d414, 0xc407c6ebfb)
        /root/go/src/github.com/hashicorp/vault/vault/token_store.go:631 +0x2f
github.com/hashicorp/vault/vault.(*TokenStore).create(0x0, 0xc4204ba8f0, 0x0, 0x0)
        /root/go/src/github.com/hashicorp/vault/vault/token_store.go:730 +0x126
github.com/hashicorp/vault/vault.(*Core).wrapInCubbyhole(0xc4201ad400, 0xc4205a5468, 0xc4205a5420, 0x7f06b8a52000, 0xc4205a5412, 0xc4205a54b8)
        /root/go/src/github.com/hashicorp/vault/vault/wrapping.go:111 +0x2cc
github.com/hashicorp/vault/vault.dynamicSystemView.ResponseWrapData(0xc4201ad400, 0xc42049f680, 0xc420392d50, 0xdf8475800, 0xc4201d4401, 0x28afa90, 0xc4205a5608, 0xc42019a060)
        /root/go/src/github.com/hashicorp/vault/vault/dynamic_system_view.go:113 +0x135
github.com/hashicorp/vault/vault.(*dynamicSystemView).ResponseWrapData(0xc420013f50, 0xc420392d50, 0xdf8475800, 0xc4201d4501, 0xc420392d50, 0x0, 0xc4201c52e0)
        <autogenerated>:162 +0x73
github.com/hashicorp/vault/helper/pluginutil.wrapServerConfig(0x7f06b8a1f7a8, 0xc420013f50, 0xc4204b0280, 0x24e, 0x24e, 0xc4204c8030, 0x0, 0x0, 0xc4201ac000, 0xc4203e1fb0)
        /root/go/src/github.com/hashicorp/vault/helper/pluginutil/tls.go:116 +0x229
github.com/hashicorp/vault/helper/pluginutil.(*PluginRunner).Run(0xc4204a1380, 0x7f06b8a1f7a8, 0xc420013f50, 0xc4203e1fb0, 0x1, 0x1bd81b3, 0x14, 0x1bfe49a, 0x24, 0xc4205a5840, ...)
        /root/go/src/github.com/hashicorp/vault/helper/pluginutil/runner.go:64 +0xfb
github.com/hashicorp/vault/logical/plugin.newPluginClient(0x7f06b8a1f7a8, 0xc420013f50, 0xc4204a1380, 0x285f1e0, 0xc42049b840, 0x0, 0x0, 0x100000000000000, 0x0)
        /root/go/src/github.com/hashicorp/vault/logical/plugin/plugin.go:82 +0x191
github.com/hashicorp/vault/logical/plugin.NewBackend(0xc4203f7540, 0x1d, 0x7f06b8a1f720, 0xc420013f50, 0x285f1e0, 0xc42049b840, 0x38, 0x38, 0x0, 0x0)
        /root/go/src/github.com/hashicorp/vault/logical/plugin/plugin.go:68 +0x2f2
github.com/hashicorp/vault/builtin/plugin.Backend(0xc4203ae700, 0xc4203e1ad0, 0x1bc2a74, 0xb, 0xc4201d4628)
        /root/go/src/github.com/hashicorp/vault/builtin/plugin/backend.go:37 +0xee
github.com/hashicorp/vault/builtin/plugin.Factory(0xc4203ae700, 0xc4203ae700, 0xc4204b9c96, 0x6, 0xc420067208)
        /root/go/src/github.com/hashicorp/vault/builtin/plugin/backend.go:19 +0x6f
github.com/hashicorp/vault/vault.(*Core).newLogicalBackend(0xc4201ad400, 0xc4204b9c96, 0x6, 0x285d8e0, 0xc420013f50, 0x28584e0, 0xc4203e1aa0, 0xc4203e1ad0, 0x2d, 0xc4204b9fb0, ...)
        /root/go/src/github.com/hashicorp/vault/vault/mount.go:768 +0x14d
github.com/hashicorp/vault/vault.(*Core).setupMounts(0xc4201ad400, 0x0, 0x0)
        /root/go/src/github.com/hashicorp/vault/vault/mount.go:686 +0x382
github.com/hashicorp/vault/vault.(*Core).postUnseal(0xc4201ad400, 0x0, 0x0)
        /root/go/src/github.com/hashicorp/vault/vault/core.go:1356 +0x42d
github.com/hashicorp/vault/vault.(*Core).runStandby(0xc4201ad400, 0xc4205986c0, 0xc420598720, 0xc420598780)
        /root/go/src/github.com/hashicorp/vault/vault/core.go:1573 +0x9e5
created by github.com/hashicorp/vault/vault.(*Core).unsealInternal
        /root/go/src/github.com/hashicorp/vault/vault/core.go:1000 +0x236
```

**Expected Behavior:**
Vault should successfully shutdown, unseal and load the plug-in. The plug-in worked after when it was loaded. Additionally if there are any problematic plugins they should be skipped during the initial mount load run, retried at the end and then eventually dropped.

**Actual Behavior:**
The Vault service crashes due to the `tokenStore` being nil at https://github.com/hashicorp/vault/blob/master/vault/wrapping.go#L111
From what I can tell this is because the [setupMounts](https://github.com/hashicorp/vault/blob/master/vault/core.go#L1356) call that loads the plugin is before the [setupCredentials](https://github.com/hashicorp/vault/blob/master/vault/core.go#L1371) call, which initialises the [tokenStore](https://github.com/hashicorp/vault/blob/master/vault/auth.go#L459).

**Steps to Reproduce:**
This issue is caused by a custom plugin. I can't share the whole plug-in, but it uses the same structure as the mock plugin inside Vault. As the error occurs during mount, rather than executing the APIs believe this should be okay. Please see source below:

`main.go`
```
import (
	"os"

	"log"

	"github.com/hashicorp/vault/helper/pluginutil"
	"github.com/hashicorp/vault/logical/plugin"
	customplugin "github.com/.../plugin"
)

func main() {
	apiClientMeta := &pluginutil.APIClientMeta{}
	flags := apiClientMeta.FlagSet()
	flags.Parse(os.Args)

	tlsConfig := apiClientMeta.GetTLSConfig()
	tlsProviderFunc := pluginutil.VaultPluginTLSProvider(tlsConfig)

	err := plugin.Serve(&plugin.ServeOpts{
		BackendFactoryFunc: customplugin.Factory,
		TLSProviderFunc:    tlsProviderFunc,
	})
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}
}
```

`plugin/backend.go`
```
package plugin

import (
	"github.com/hashicorp/vault/logical"
	"github.com/hashicorp/vault/logical/framework"
)

func Factory(conf *logical.BackendConfig) (logical.Backend, error) {
	b := Backend()
	if err := b.Setup(conf); err != nil {
		return nil, err
	}
	return b, nil
}

func Backend() *backend {
	b := &backend{
		storage: &logical.InmemStorage{},
	}

	b.Backend = &framework.Backend{
		Help: "Help",
		Paths: []*framework.Path{
			pathX(b), // some custom APIs
		},
		Secrets:     []*framework.Secret{},
		BackendType: logical.TypeLogical,
	}

	return b
}

type backend struct {
	*framework.Backend

	storage *logical.InmemStorage
}

func pathX(b *backend) *framework.Path {
	return &framework.Path{
		Pattern: "test",
		Callbacks: map[logical.Operation]framework.OperationFunc{
		},
		HelpSynopsis:    "TODO",
		HelpDescription: "TODO",
	}
}
```

DO NOT attempt this on your production cluster, as it will brick it!

0) Setup Vault in non-dev mode
1) Compile the source code, `go build -o myplugin ./main.go`
2) Create plugin directory and add the plugin binary to it, e.g. `/opt/vault/plugins`
3) Add `plugin_directory` to your vault.conf/hcl, e.g. `plugin_directory = "/opt/vault/plugins"`
4) Run vault (non-dev mode!)
5) Unseal vault
6) Add the plugin to the plugin catalog, e.g.
`vault write sys/plugins/catalog/myplugin sha_256=$(shasum -a 256 myplugin|cut -d ' ' -f 1) command="myplugin"` executed in `/opt/vault/plugins`
7) Mount the plugin, `vault mount -path=myplugir -plugin-name=myplugin plugin`
8) Seal and restart Vault
9) Start Vault and unseal it

**Important Factoids:**
The plugin has `BackendType` = `logical.TypeLogical`. This crash leads to an irrecoverable failure as it's impossible to unseal Vault and remove the plugin.
This issue does not occur when Vault is ran in dev mode, as it's always unsealed.

### LINKED ISSUE #3266: A mounted non-existing plugin cannot be unmounted
**Environment:**
* Operating System/Architecture:
Ubuntu 14.04 - `Linux host 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

* Vault Version:  Vault v0.8.1 ('d54258253906596d22975a2174189913d1610cb9+CHANGES')

**Vault Config File:**
```
backend "cassandra" {
  hosts = "cassandra-ZZZ"
  protocol_version = 3
  connection_timeout = 600
}

ha_storage "etcd" {
  address = "http://XXX:2379"
  ha_enabled = 1
  etcd_api = "v3"
  redirect_addr = "http://YYY:8200"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}

plugin_directory = "/opt/vault/plugins"
```

**Startup Log Output:**
```
==> Vault server configuration:

              HA Storage: etcd
                     Cgo: disabled
         Cluster Address: https://vault-cluster:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: http://vault-host:8200
                 Storage: cassandra
                 Version: Vault v0.8.1
             Version Sha: d54258253906596d22975a2174189913d1610cb9+CHANGES
```

**Expected Behavior:**
It should not be possible to mount plugins that are not present in the plugin catalog.

**Actual Behavior:**
`mount` returned successful result when mounting the non existing plugin and it is impossible to unmount afterwards.

**Steps to Reproduce:**
Attempt to mount a plugin, which does not exist in the plugin catalog.

Command output:
```
# vault mount -path=plugin-1 -plugin-name=notexistingplugin  plugin
Successfully mounted plugin 'notexistingplugin' at 'plugin-1'!
# vault unmount plugin-1
Unmount error: Error making API request.

URL: DELETE http://127.0.0.1:8200/v1/sys/mounts/plugin-1
Code: 400. Errors:

* no plugin found with name: notexistingplugin
# vault mounts
Path            Type       Accessor            Plugin                           Default TTL  Max TTL  Force No Cache  Replication Behavior  Description
...
plugin-1/       plugin     plugin_c941fc4e     notexistingplugin                system       system   false           replicated
```

Logs:
```
[INFO ] core: successful mount: path=plugin-1/ type=plugin
[TRACE] rollback: attempting rollback: path=plugin-1/
[ERROR] rollback: error rolling back: path=plugin-1/ error=no plugin found with name: notexistingplugin
[TRACE] rollback: attempting rollback: path=plugin-1/
[ERROR] rollback: error rolling back: path=plugin-1/ error=no plugin found with name: notexistingplugin
[ERROR] sys: unmount failed: path=plugin-1/ error=no plugin found with name: notexistingplugin
[TRACE] rollback: attempting rollback: path=plugin-1/
[ERROR] rollback: error rolling back: path=plugin-1/ error=no plugin found with name: notexistingplugin
```

### PR DESCRIPTION
**Pull request by calvn**
Fixes #3241 
Closes #3266

### CODE REVIEW

File: builtin/plugin/backend.go [hunk 1]
```diff
@@ -53,16 +73,24 @@ type backend struct {
...
-	b.Logger().Trace("plugin: reloading plugin backend", "plugin", pluginName)
 
 	// Ensure proper cleanup of the backend (i.e. call client.Kill())
 	b.Backend.Cleanup()
 
-	nb, err := bplugin.NewBackend(pluginName, b.config.System, b.config.Logger)
+	nb, err := bplugin.NewBackend(pluginName, b.config.System, b.config.Logger, false)
 	if err != nil {
 		return err
 	}
```
Comment (jefferai) [inline builtin/plugin/backend.go]: At this point, please check the type and special paths against the values retrieved from when it was run in metadata mode and make sure they match.

File: helper/pluginutil/runner.go [hunk 2]
```diff
@@ -98,6 +102,39 @@ func (r *PluginRunner) Run(wrapper RunnerUtil, pluginMap map[string]plugin.Plugi
 	return client, nil
 }
 
+func (r *PluginRunner) RunMetadataMode(wrapper RunnerUtil, pluginMap map[string]plugin.Plugin, hs plugin.HandshakeConfig, env []string, logger log.Logger) (*plugin.Client, error) {
+	cmd := exec.Command(r.Command, r.Args...)
```
Comment (jefferai) [inline helper/pluginutil/runner.go]: This appears to be, other than whether metadatamode env var is enabled or not, the same exact logic as the latter part of Run. Any chance they can be combined into a runCommon that Run and RunMetadataMode call with appropriate bool var?

Comment (calvn) [reply helper/pluginutil/runner.go]: @briankassouf reverted this on https://github.com/hashicorp/vault/commit/5526108c3df336281cb2f52a550c5f526459dcf6#diff-217b9ed237f303ae16a69462dfcc6bf3. I think it's because he wanted to keep the behavior separate explicitly. Brian correct me if otherwise :)

Comment (briankassouf) [reply helper/pluginutil/runner.go]: That's correct, but i'm okay with `RunMetadataMode`, `Run`, and `runCommon`. Other plugin types shouldn't have to know about metadata mode IMO.

**Comment by briankassouf** [comment]
@calvn can you merge with master, the tests wont run on travis otherwise

File: logical/plugin/plugin.go [hunk 3]
```diff
@@ -40,8 +40,9 @@ func (b *BackendPluginClient) Cleanup() {
 
 // NewBackend will return an instance of an RPC-based client implementation of the backend for
 // external plugins, or a concrete implementation of the backend if it is a builtin backend.
-// The backend is returned as a logical.Backend interface.
-func NewBackend(pluginName string, sys pluginutil.LookRunnerUtil, logger log.Logger) (logical.Backend, error) {
+// The backend is returned as a logical.Backend interface. The isMetadataMode param determines whether
+// the plugin should run with the -metadata flag.
```
Comment (briankassouf) [inline logical/plugin/plugin.go]: This comment is old

File: builtin/plugin/backend.go (hunk 1 above)
Comment (calvn) [reply builtin/plugin/backend.go]: This should be addressed. It is checked further down in the `b.loaded` conditional.

**Comment by kirilmonzo** [comment]
Hi @calvn, just tried deploying the latest version and having some trouble mounting the plugin. Logs below:
```
[ERROR] plugin.metadata.myplugin-binary: plugin tls init: error=map[]
[ERROR] sys: mount failed: path=myplugin/ error=plugin exited before we could connect
```
