### PR TITLE
Sanitize policy behavior across backends

### LINKED ISSUE #3318: Userpass backend encodes default into policies list
This is old-style behavior; we should instead keep the set explicitly passed-in and let the core add default between auth response and token generation.

### LINKED ISSUE #3323: Writing roles with policy arrays fails
Hi, I am experiencing an issue with creating new roles in the AWS backend. Even if I go strictly by the docs https://www.vaultproject.io/api/auth/aws/index.html#sample-payload-5 it does not work as expected.
**Environment:**

* Vault Version: 0.8.2
* Operating System/Architecture: macOS 10.12.6

**Expected Behavior:**

```
curl -X POST -H "X-Vault-Token:$VAULT_TOKEN" --data @sample.json https://vault.mgmt.acmecorp.com/v1/auth/aws/role/sample
```
Above curl should successfully create the sample role.

**Actual Behavior:**

```
{"errors":["Error converting input [default dev prod] for field policies: '' expected type 'string', got unconvertible type '[]interface {}'"]}
```
Expected behavior can be achieved when putting the policies as comma separated values `policies: "default, dev, prod"`

**Steps to Reproduce:**

See steps in Expected Behavior

**Odd Things:**
Reading a role via `vault read -format=json auth/aws/role/:role` returns a json where the policies are in square brackets as described in https://www.vaultproject.io/api/auth/aws/index.html#read-role.

### PR DESCRIPTION
**Pull request by jefferai**
* Ingress TypeCommaStringSlice
* Read returns a slice
* Default is not added to the saved set of policies, we let core do its
thing

Fixes #3318
Fixes #3323

### CODE REVIEW

**Comment by jefferai** [comment]
Note, see https://github.com/hashicorp/vault/issues/3318 -- I think we shouldn't encode 'default' in, as it will make it harder to support a no-default flag as a future enhancement. We should let the core do the right thing.

File: builtin/credential/cert/path_certs.go [hunk 1]
```diff
@@ -133,7 +133,7 @@ func (b *backend) pathCertRead(
 		Data: map[string]interface{}{
 			"certificate":  cert.Certificate,
 			"display_name": cert.DisplayName,
-			"policies":     strings.Join(cert.Policies, ","),
+			"policies":     cert.Policies,
```
Comment (chrishoffman) [inline builtin/credential/cert/path_certs.go]: Any concern with the behavior change of the return here?  I like this better but this does break compatibility.

File: builtin/credential/ldap/path_groups.go [hunk 2]
```diff
@@ -86,7 +84,7 @@ func (b *backend) pathGroupRead(
 
 	return &logical.Response{
 		Data: map[string]interface{}{
-			"policies": strings.Join(group.Policies, ","),
+			"policies": group.Policies,
```
Comment (chrishoffman) [inline builtin/credential/ldap/path_groups.go]: Same backwards compatibility concerns as above.

File: builtin/credential/ldap/path_users.go [hunk 3]
```diff
@@ -93,7 +93,7 @@ func (b *backend) pathUserRead(
 	return &logical.Response{
 		Data: map[string]interface{}{
 			"groups":   strings.Join(user.Groups, ","),
-			"policies": strings.Join(user.Policies, ","),
+			"policies": user.Policies,
```
Comment (chrishoffman) [inline builtin/credential/ldap/path_users.go]: Same backwards compatibility concerns as above.

Comment (jefferai) [reply builtin/credential/ldap/path_users.go]: Yes, it breaks compatibility. I'm inclined to just make the change though rather than move to another field. (As I mentioned in chat, we'd definitely note this in CHANGES.)

I don't think in most cases these lookup endpoints are used by non-humans (and humans can easily understand it either way), and for anyone trying to feed them from a read into a write, the writes now accept slices so that will still work.
