### PR TITLE
Rearchitect MountTable locking and fix rollback.

### LINKED ISSUE #771: Unmounting "secret/" causes errors in log
If you unmount the default "secret/" store, the log fills with this once a minute:

`2015/11/09 16:07:09 [ERR] rollback: error rolling back secret/: unsupported path`

### PR DESCRIPTION
**Pull request by jefferai**
The rollback manager was using a saved MountTable rather than the
current table, causing it to attempt to rollback unmounted mounts, and
never rollback new mounts.

In fixing this, it became clear that bad things could happen to the
mount table...the table itself could be locked, but the table pointer
(which is what the rollback manager needs) could be modified at any time
without locking. This commit therefore also returns locking to a mutex
outside the table instead of inside, and plumbs RLock/RUnlock through to
the various places that are reading the table but not holding a write
lock.

Both unit tests and race detection pass.

Fixes #771

### CODE REVIEW

**Comment by mitchellh** [comment]
I have one concern on the PR that otherwise looks good: there appears to be no test that tests the original bug being fixed? I see a minor change to the test file, does that actually exercise the bug? (given I didn't run it myself).

**Comment by jefferai** [comment]
@mitchellh With the old approach, the mount entries were static. I could write a test to show that it didn't work, but it was easy to see with a simple `vault server -dev` (simply unmount `secret` and watch the errors roll in) and with simple logical reasoning.

With the new approach, the mounts come from a function. I didn't think of a good way to test this other than simply modifying the mount table that the function returns and then ensuring that we can iterate over it...which doesn't seem like a test of the rollback manager per se.

I'm totally open to ideas...

File: vault/logical_system.go [hunk 1]
```diff
@@ -613,10 +614,13 @@ func (b *SystemBackend) handleMountTuneWrite(
 		}
 
 		if newDefault != nil || newMax != nil {
+			b.Core.mountsLock.Lock()
```
Comment (armon) [inline vault/logical_system.go]: Can we just put a defer after this to catch all the paths?

File: vault/rollback.go [hunk 2]
```diff
@@ -29,7 +29,12 @@ const (
 // is in-flight at any given time within a single seal/unseal phase.
 type RollbackManager struct {
 	logger *log.Logger
-	mounts *MountTable
+
+	// This gives the current mount table, plus a RWMutex that is
+	// locked for reading. It is up to the caller to RUnlock it
+	// when done with the mount table
+	mounts func() (*MountTable, *sync.RWMutex)
```
Comment (armon) [inline vault/rollback.go]: Can we have this function instead just return a slice of mount paths? This way the locking can be done internally and the slice is left to the caller

File: vault/rollback.go [hunk 3]
```diff
@@ -101,12 +106,17 @@ func (m *RollbackManager) run() {
...
 
-	for _, e := range m.mounts.Entries {
+	mounts, mountsLock := m.mounts()
+	mountsLock.RLock()
+	defer mountsLock.RUnlock()
+	if mounts == nil {
+		return
+	}
+
+	for _, e := range mounts.Entries {
```
Comment (armon) [inline vault/rollback.go]: I think we still have the issue of paths that get unmounted are still around or no?

Comment (armon) [inline vault/rollback.go]: Unmounted or remounted

**Comment by armon** [comment]
Locking fixes LGTM, but I think we can simplify the interface of passing in the mount points to the RollbackManager to avoid the locks and MountEntries
