### PR TITLE
UI ensure trailing slash

### LINKED ISSUE #4819: ui: vault path prefixes being prepended to fields
When using the web UI (v0.10.2), and accessing a given sub-path, for example:

https://vault.host.com:8200/ui/vault/secrets/foo/list/bar/

The above will list the fields within `/foo/bar/` within the UI, without issue. E.g:
```
$ vault list foo/bar
Keys
----
baz
```

However, if we go to the following path (if someone types out the URL, or adjusts it manually), and forgets to add the trailing slash, like so:

https://vault.host.com:8200/ui/vault/secrets/foo/list/bar

The following will happen:

image

For some reason, it will interpret `foo` as a search parameter in the search form, as well as it adds the `foo` prefix to all fields, even though that's not the name of the field.

To reproduce, simply create a value `foo/bar/baz`, access the `bar` path within the UI, and remove the trailing slash from the URL. You will see the `foo` prefix being added to all items in the field list.

Expected behavior, is for it to either redirect to include the forward slash, or allow it without the forward slash. The reasoning behind this is that a policy may have access to a sub-path, and not the mount itself, so the user can't natively find their way through the UI, and have to manually type the direct path in the URL.

**Environment:**
* Vault Server Version: 0.10.2
* Vault CLI Version: n/a
* Server Operating System/Architecture: linux amd64

### PR DESCRIPTION
**Pull request by meirish**
This was originally developed to address #4660, but we fixed stripping the trailing slash on the go side. The JS fix is still needed when a user inputs an incorrect path that _does not_ end in a slash. This PR ensures that the secret id ends in a slash if viewing the list route.

Fixes #4819

### CODE REVIEW

File: ui/app/routes/vault/cluster/secrets/backend/list.js [hunk 1]
```diff
@@ -19,12 +19,16 @@ export default Ember.Route.extend({
...
-    const backendModel = this.store.peekRecord('secret-engine', backend);
-    const type = backendModel && backendModel.get('type');
+    let { backend } = this.paramsFor('vault.cluster.secrets.backend');
+    let { secret } = this.paramsFor(this.routeName);
+    let backendModel = this.store.peekRecord('secret-engine', backend);
+    let type = backendModel && backendModel.get('type');
     if (!type || !SUPPORTED_BACKENDS.includes(type)) {
       return this.transitionTo('vault.cluster.secrets');
     }
+    if (this.routeName === 'vault.cluster.secrets.backend.list' && !secret.endsWith('/')) {
```
Comment (alisdair) [inline ui/app/routes/vault/cluster/secrets/backend/list.js]: Why is the `this.routeName` check needed? Are you subclassing this route elsewhere, or is there something else I don't understand here?

Comment (meirish) [reply ui/app/routes/vault/cluster/secrets/backend/list.js]: Yep, you pretty much hit the nail on the head 🔨 - https://github.com/hashicorp/vault/blob/df18871704fe869e9be45b542a6b1eb2fe46c293/ui/app/router.js#L74-L82 at the root the secret is "", but you can also navigate down the tree, and you can't have the same route for both cases, so we have `-root` versions of the secret CRUD routes and `list-root.js` is this file re-exported.
