### PR TITLE
logical/aws: Harden WAL entry creation

### LINKED ISSUE #5190: Vault tries to revoke AWS IAM users that don't exist
**Describe the bug**
When we were looking at our CloudTrail logs, we noticed a large amount of errors being generated by the vault user. It seems that vault tries to revoke an IAM user that doesn't exist every minute, here is the log from CloudTrail:

```
{
    "eventVersion": "1.02",
    "userIdentity": {
      "type": "IAMUser",
      "principalId": "XXXXXXXXXXXXXXXXXXXXX",
      "arn": "arn:aws:iam::our-aws-account-id:user/vault",
      "accountId": "our-aws-account-id",
      "accessKeyId": "XXXXXXXXXXXXXXXXXXXXX",
      "userName": "vault"
    },
    "eventTime": "2018-08-27T10:53:25Z",
    "eventSource": "iam.amazonaws.com",
    "eventName": "ListGroupsForUser",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "xxx.xxx.xxx.xxx",
    "userAgent": "aws-sdk-go/1.12.74 (go1.10.3; linux; amd64)",
    "errorCode": "NoSuchEntityException",
    "errorMessage": "The user with name vault-userpass-aVaultUsername-role-aVaultRoleName-1794 cannot be found.",
    "requestParameters": "{\"userName\": \"vault-userpass-aVaultUsername-role-aVaultRoleName-1794\", \"maxItems\": 1000}",
    "responseElements": "null",
    "requestID": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "eventID": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "eventType": "AwsApiCall",
    "recipientAccountId": "our-aws-account-id"
  }
  ```

We think this happens when Vault fails to create the IAM user in the first place (although I suppose it can also happen if someone removes the IAM user manually). Because we only use STS tokens, we never gave Vault the rights to create IAM users. However when using the interface, clicking on a role immediately creates an IAM user. Vault then tries to revoke this, but fails.

**To Reproduce**
1. Setup Vault with AWS, without giving it IAM permissions to create actual users
2. Create a role for AWS within vault
3. Try to generate a account through the web interface (might also work through CLI)
You'll get this error: 
```Error creating IAM user: AccessDenied: User: arn:aws:iam::our-aws-account-id:user/vault is not authorized to perform: iam:CreateUser on resource: arn:aws:iam::[...]```
4. Afterwards, check the CloudTrail logs and see that Vault tries to revoke the user every minute

**Expected behavior**
Vault acknowledges that the account does not exist (for example by checking the response the IAM API gives) and stops trying to remove the account.

Or alternatively have a way that you can stop Vault from trying to revoke the accounts.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    5
Threshold       3
Version         0.10.3
Cluster Name    vault-cluster-63d461f0
Cluster ID      xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
HA Enabled      true
HA Cluster      https://our-domain
HA Mode         active
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v0.10.3 ('c69ae68faf2bf7fc1d78e3ec62655696a07454c7')
```
* Server Operating System/Architecture:
n/a

Vault server configuration file(s):
n/a

### PR DESCRIPTION
**Pull request by joelthompson**
If AWS IAM user creation failed in any way, the WAL corresponding to the
IAM user would get left around and Vault would try to roll it back.
However, because the user never existed, the rollback failed. Thus, the
WAL would essentially get "stuck" and Vault would continually attempt to
roll it back, failing every time. A similar situation could arise if the
IAM user that Vault created got deleted out of band, or if Vault deleted
it but was unable to write the lease revocation back to storage (e.g., a
storage failure).

This attempts to harden it in two ways. One is by deleting the WAL log
entry if the IAM user creation fails. However, the WAL deletion could
still fail, and this wouldn't help where the user is deleted out of
band, so second, consider the user rolled back if the user just doesn't
exist, under certain circumstances.

Fixes #5190

### CODE REVIEW

File: builtin/logical/aws/path_user.go [hunk 1]
```diff
@@ -130,6 +132,37 @@ func pathUserRollback(ctx context.Context, req *logical.Request, _kind string, d
...
+		//
+		// BEWARE a potential race condition -- where this is called
+		// immediately after a user is created. AWS eventual consistency
+		// might say the user doesn't exist when the user does in fact
+		// exist, and this could cause Vault to forget about the user.
+		// This won't happen if the user creation fails (because the WAL
+		// minimum age is 5 minutes, and AWS eventual consistency is, in
+		// practice, never that long), but it could happen if a lease holder
+		// asks immediately after getting a user to revoke the lease, causing
+		// Vault to leake the secret, which would be a Very Bad Thing to allow.
```
Comment (vishalnayak) [inline builtin/logical/aws/path_user.go]: s/leake/leak

File: builtin/logical/aws/path_user.go [hunk 2]
```diff
@@ -130,6 +132,37 @@ func pathUserRollback(ctx context.Context, req *logical.Request, _kind string, d
...
+		// So we make sure that, if there's an associated lease, it must be at
+		// least 5 minutes old as well.
+		if aerr, ok := err.(awserr.Error); ok {
+			acceptMissingIamUsers := false
+			if req.Secret == nil {
+				// WAL rollback
+				acceptMissingIamUsers = true
+			} else if time.Since(req.Secret.IssueTime) > time.Duration(5*time.Minute) {
```
Comment (vishalnayak) [inline builtin/logical/aws/path_user.go]: It might be better if the `5*time.Minute` here and in https://github.com/hashicorp/vault/blob/master/builtin/logical/aws/backend.go#L48 used constants.

File: builtin/logical/aws/path_user.go [hunk 3]
```diff
@@ -130,6 +132,37 @@ func pathUserRollback(ctx context.Context, req *logical.Request, _kind string, d
...
+		// This won't happen if the user creation fails (because the WAL
+		// minimum age is 5 minutes, and AWS eventual consistency is, in
+		// practice, never that long), but it could happen if a lease holder
+		// asks immediately after getting a user to revoke the lease, causing
+		// Vault to leake the secret, which would be a Very Bad Thing to allow.
+		// So we make sure that, if there's an associated lease, it must be at
+		// least 5 minutes old as well.
+		if aerr, ok := err.(awserr.Error); ok {
+			acceptMissingIamUsers := false
+			if req.Secret == nil {
```
Comment (vishalnayak) [inline builtin/logical/aws/path_user.go]: This `if` and `else if` blocked can be combined by an `||`.

**Comment by chrishoffman** [comment]
Can you back out the expiration manager changes? A bunch of work has been done in here and I am not sure this is necessary.  If it is, can you create a separate PR?

**Comment by chrishoffman** [comment]
Mainly because it is not related to the proposed change, although I could be missing something on why this change is necessary.  We normally only pass the information that is absolutely necessary to the backend and I am not sure IssueDate is required for revoke operations.

File: builtin/logical/aws/path_user.go [hunk 4]
```diff
@@ -130,6 +132,35 @@ func pathUserRollback(ctx context.Context, req *logical.Request, _kind string, d
...
+		// This won't happen if the user creation fails (because the WAL
+		// minimum age is 5 minutes, and AWS eventual consistency is, in
+		// practice, never that long), but it could happen if a lease holder
+		// asks immediately after getting a user to revoke the lease, causing
+		// Vault to leak the secret, which would be a Very Bad Thing to allow.
+		// So we make sure that, if there's an associated lease, it must be at
+		// least 5 minutes old as well.
+		if aerr, ok := err.(awserr.Error); ok {
+			acceptMissingIamUsers := false
+			if req.Secret == nil || time.Since(req.Secret.IssueTime) > time.Duration(minAwsUserRollbackAge) {
```
Comment (joelthompson) [inline builtin/logical/aws/path_user.go]: @chrishoffman -- this line is where I need the expiration manager changes, and the comments above try to explain why.
