### PR TITLE
Ensure values to be encoded in a CRL are in UTC.

### LINKED ISSUE #1727: CRL Time is encoded incorrectly?
I issued three certificates, revoked one and this is the resulting CRL:

```
$ openssl crl -in only_one.crl -text                                                                                                     [08:45:51]
Certificate Revocation List (CRL):
        Version 1 (0x0)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: /CN=walkman
        Last Update: Aug 12 21:36:16 2016 GMT
        Next Update: Aug 15 21:36:16 2016 GMT
        CRL extensions:
            X509v3 Authority Key Identifier:
                keyid:4A:BD:9A:6A:41:4E:98:AD:C7:4D:82:52:4C:7E:72:4C:FE:2E:39:90

Revoked Certificates:
    Serial Number: 22A4769F632AB01EB5AD1DC16B282033EBC5CA2B
        Revocation Date: Aug 12 23:36:16 2016
    Signature Algorithm: sha256WithRSAEncryption
        07:19:b4:ec:e4:f6:98:d9:ea:78:6a:71:6a:70:c6:02:3e:18:
        59:9e:b1:bf:6d:7a:6a:08:2c:df:35:36:8d:b9:dc:67:3f:9a:
        4d:1a:73:8f:bd:c4:ea:89:6a:86:13:02:be:4e:80:81:ab:c5:
        d4:12:91:48:eb:12:7d:99:c7:1c:46:3a:b6:ee:0a:36:6c:f7:
        c1:a4:5a:12:86:03:91:6c:3a:50:8b:ec:89:7c:f5:c3:cd:87:
        d4:f0:5b:a3:42:c9:c3:a7:17:d7:4e:d8:c2:0d:39:c1:6e:61:
        25:dd:1a:aa:7a:1b:4f:91:b8:4e:96:b5:21:8c:d7:0b:75:2c:
        b8:c1:dc:29:e2:43:fd:7c:3c:79:62:69:fc:05:1f:81:50:fe:
        36:a7:31:e7:a5:77:ba:02:52:37:f0:b9:dc:e1:f1:73:d9:26:
        d8:fc:1d:bb:ad:d0:e3:9b:f8:86:52:96:fd:62:ab:c8:33:36:
        c1:e0:fc:dd:0a:3c:7e:d4:98:14:60:bc:61:8f:43:3a:7a:65:
        9d:29:d9:f6:a5:bf:f9:88:57:cf:ee:77:f2:57:41:5d:98:47:
        c0:56:19:3a:4e:d5:62:ef:d2:82:72:c4:44:ba:89:94:96:d9:
        9f:da:bc:90:16:af:52:be:12:ea:7e:47:0e:12:de:ba:39:c8:
        6b:96:71:e2
-----BEGIN X509 CRL-----
MIIBqjCBkzANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDEwd3YWxrbWFuFw0xNjA4
MTIyMTM2MTZaFw0xNjA4MTUyMTM2MTZaMCswKQIUIqR2n2MqsB61rR3BayggM+vF
yisXETE2MDgxMjIzMzYxNiswMjAwoCMwITAfBgNVHSMEGDAWgBRKvZpqQU6YrcdN
glJMfnJM/i45kDANBgkqhkiG9w0BAQsFAAOCAQEABxm07OT2mNnqeGpxanDGAj4Y
WZ6xv216aggs3zU2jbncZz+aTRpzj73E6olqhhMCvk6AgavF1BKRSOsSfZnHHEY6
tu4KNmz3waRaEoYDkWw6UIvsiXz1w82H1PBbo0LJw6cX107Ywg05wW5hJd0aqnob
T5G4Tpa1IYzXC3UsuMHcKeJD/Xw8eWJp/AUfgVD+Nqcx56V3ugJSN/C53OHxc9km
2Pwdu63Q45v4hlKW/WKryDM2weD83Qo8ftSYFGC8YY9DOnplnSnZ9qW/+YhXz+53
8ldBXZhHwFYZOk7VYu/SgnLERLqJlJbZn9q8kBavUr4S6n5HDhLeujnIa5Zx4g==
-----END X509 CRL-----
```

After checking with dumpasn1 tool, the CRL seems to be wrong?
```
$ openssl crl -in only_one.crl -out time.der -outform der
$ dumpasn1 -hh time.der
    <17 11 31 36 30 38 31 32 32 33 33 36 31 36 2B 30 32 30 30>
 98  17:         UTCTime '160812233616+0200'
       :           Error: Time is encoded incorrectly.
       :         }
       :       }
0 warnings, 1 error.
```

For more details: https://github.com/pyca/cryptography/issues/3086

### PR DESCRIPTION
**Pull request by jefferai**
This aligns with the RFC. You might expect Go to ensure this in the CRL generation call, but...it doesn't.

Fixes #1727

### CODE REVIEW

**Comment by jefferai** [comment]
(Assigned to laura/vishal for review)

File: builtin/logical/pki/crl_util.go [hunk 1]
```diff
@@ -151,10 +155,16 @@ func buildCRL(b *backend, req *logical.Request) error {
...
 		}
 
-		revokedCerts = append(revokedCerts, pkix.RevokedCertificate{
+		// NOTE: We have to change this to UTC time because the CRL standard
+		// mandates it but Go will happily encode the CRL without this.
+		newRevCert := pkix.RevokedCertificate{
 			SerialNumber:   revokedCert.SerialNumber,
-			RevocationTime: time.Unix(revInfo.RevocationTime, 0),
-		})
+			RevocationTime: time.Unix(revInfo.RevocationTime, 0).UTC(),
```
Comment (vishalnayak) [inline builtin/logical/pki/crl_util.go]: Will there be a need to distinguish entries that were stored before, in not-UTC?

**Comment by vishalnayak** [comment]
One minor clarification comment, other than that, LGTM!

File: builtin/logical/pki/crl_util.go (hunk 1 above)
Comment (jefferai) [inline builtin/logical/pki/crl_util.go]: The value you get from time.Time.Unix is always relative to UTC. The issue is that time.Unix parses from number of seconds since UTC into a local time, not UTC time. So this is just a conversion.

I didn't need to add the time.Time field but it feels better, with our further experience on the matter, to store a time. Time directly for our internal purposes.

Comment (vishalnayak) [inline builtin/logical/pki/crl_util.go]: Sounds good
