### PR TITLE
Suppress event broker not started log warning

### LINKED ISSUE #19502: Strange Error/Warn message enabling kv secret engine
**Describe the bug**
Gor this message after succesfully enabled secret kv engine from UI:
Mar 10 09:53:44 vault-nodo1 vault[1268]: 2023-03-10T09:53:44.866+0100 [INFO]  core: successful mount: namespace="" path=kvpu/ type=kv version=""
Mar 10 09:53:44 vault-nodo1 vault[1268]: 2023-03-10T09:53:44.967+0100 [WARN]  secrets.kv.kv_67f85f42: Error sending event: error="event broker has not been started"

Is it only a Warming?

**Environment:**
3 Nodes Vault Enterprise Cluster behind Haproxy load balancer
* Vault Server Version :  
* Vault v1.13.0+ent.hsm (d07983ca207de9fd561c24390ee2d84379739a32), built 2023-03-01T11:09:12Z (cgo)
* Server Operating System/Architecture:
 
 Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-67-generic x86_64)
 Linux vault-nodo1 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
The Vault server is a vm running on  on OracleVirtualBox Versione 7.0.6_rpmfusion r15 (running on Fedora 37 Host)

Vault server configuration file(s):

```hcl
hcl
ui = true
disable_mlock = true
license_path = "/etc/vault.d/vault.hclic"

storage "raft" {
    path = "/opt/vault/data"
    node_id = "vault-nodo1"
    retry_join {
     leader_tls_servername   = "vault-nodo1.xxx.it"
     leader_api_addr         = "https://xxx.it:8200"
   }
   retry_join {
     leader_tls_servername   = "vault-nodo2.xxx.it"
     leader_api_addr         = "https://vault-nodo2.xxx.it:8200"
   }
     retry_join {
     leader_tls_servername   = "vault-nodo3.xxx.it"
     leader_api_addr         = "https://vault-nodo3.xxx.it:8200"
   }
}

listener "tcp" {
   address = "vault-nodo1.xxx.it:8200"
   cluster_address = "vault-nodo1.xxx.it:8201"
  tls_cert_file = "/opt/vault/tls/vault-nodo1.xxx.it.pem"
  tls_key_file  = "/opt/vault/tls/vault-nodo1.xxx.it.key"
 # tls_disable_client_certs = true
  # tls_disable = true
}


cluster_addr  = "https://vault-nodo1.xxx.it:8201"
api_addr      = "https://vault.xxx.it"

### PR DESCRIPTION
**Pull request by tomhjp**
Fixes #19502

The other way I considered fixing this was using `errors.Is` and returning a success response if it's the sentinel error. That required moving the sentinel error definition to the sdk, but otherwise felt like much of a muchness. Let me know if you think we can do it more elegantly though.

### CODE REVIEW

File: sdk/plugin/grpc_events.go [hunk 1]
```diff
@@ -37,6 +37,10 @@ type GRPCEventsServer struct {
 }
 
 func (s *GRPCEventsServer) SendEvent(ctx context.Context, req *pb.SendEventRequest) (*pb.Empty, error) {
+	if s.impl == nil {
```
Comment (swenson) [inline sdk/plugin/grpc_events.go:40]: I think it will also be necessary to do this in `sdk/framework/backend.go`, since when the KV plugin is loaded as an internal plugin, it will use the framework method directly and still return the error from there.

Comment (tomhjp) [reply sdk/plugin/grpc_events.go:40]: Good question. FWIW in my testing, this change did suppress the warning log, so although it's a little weird, the builtin KV plugin is hitting this code path.

Currently we return a similar but slightly different error: https://github.com/hashicorp/vault/blob/670c9522a554b78ad47824de11a8344ff9fe88c6/sdk/framework/backend.go#L696-L698

And the KV plugin ignores that error: https://github.com/hashicorp/vault-plugin-secrets-kv/blob/405c5cb0ec328e4c54682c3c6738120408a35221/backend.go#L455-L462

I like the idea that plugins can tell when the events system is disabled, but that doesn't have to be by getting a sentinel error back from the `Send` method. We could add a separate method for that if we find a concrete use for it. I'm kind of torn whether it's best to be consistent by also changing the returned error to be nil, or just leave it be and let plugins decide what they'd like to do with the error. WDYT?

Comment (swenson) [reply sdk/plugin/grpc_events.go:40]: Ah, cool. I think using `ErrNoEvents` as a sentinel is fine to return to signal that the events system is not available.

**Review by swenson — APPROVED** [review]
LGTM
