### PR TITLE
Request forwarding

### LINKED ISSUE #443: Standby nodes should proxy traffic, not issue a redirect
In issue #389, I asked for the ability to set the health check page to return 200 for standby nodes, so that they live in the load balancer and are ready to take over for a failed node as soon as a new election is made.  Thank you for quickly getting that change made.  However, now that .2 is out and I've tried it, I discovered it doesn't actually work they way I need it to.

It looks like Vault standby nodes don't proxy their traffic to the active node, they simply issue a redirect to the client.  That doesn't work, since i have all of my vault nodes behind a load balancer and not directly accessible from outside a private subnet.  Could we consider having Vault proxy instead?  As with my earlier request, what I'm trying to do is reduce the downtime when a node fails.  If only the active node is in the load balancer, Vault has to first detect the failure, elect a new leader, and then a minimum of 2 health checks (Amazon ELB's minimum) have to pass before the new node comes online.

Ultimately I'd still like to see Active/Active be a possibility (#390), but for now proxying instead of redirecting would help.

### PR DESCRIPTION
**Pull request by jefferai**
Closes #443

### CODE REVIEW

File: command/server.go [hunk 1]
```diff
@@ -215,75 +218,92 @@ func (c *ServerCommand) Run(args []string) int {
...
+			c.Ui.Error(fmt.Sprintf("Error parsing redirect address %s: %v", coreConfig.RedirectAddr, err))
 			return 1
 		}
+		host, port, err := net.SplitHostPort(u.Host)
+		nPort, nPortErr := strconv.Atoi(port)
+		if err != nil {
+			// assume it's due to there not being a port specified, in which case
+			// use 443
+			host = u.Host
+			nPort = 443
```
Comment (vishalnayak) [inline command/server.go]: should we set nPortErr to nil here?

File: command/server.go [hunk 2]
```diff
@@ -322,6 +352,35 @@ func (c *ServerCommand) Run(args []string) int {
...
+		if reloadFunc != nil {
+			relSlice := c.ReloadFuncs["listener|"+lnConfig.Type]
+			relSlice = append(relSlice, reloadFunc)
+			c.ReloadFuncs["listener|"+lnConfig.Type] = relSlice
+		}
+
+		if !disableClustering && lnConfig.Type == "tcp" {
+			var addr string
+			var ok bool
+			if addr, ok = lnConfig.Config["cluster_address"]; ok {
```
Comment (vishalnayak) [inline command/server.go]: Should we refer to VAULT_CLUSTER_ADDR also?

File: command/server.go [hunk 3]
```diff
@@ -394,16 +449,55 @@ func (c *ServerCommand) Run(args []string) int {
...
 				return 1
 			}
 		}
 	}
 
+	handler := vaulthttp.Handler(core)
+
+	// This needs to happen before we first unseal, so before we trigger dev
+	// mode if it's set
+	core.SetClusterListenerSetupFunc(vault.WrapListenersForClustering(clusterAddrs, handler, c.logger))
```
Comment (vishalnayak) [inline command/server.go]: Should we verify that the elements of clusterAddrs are parse-able before passing it down?

Comment (vishalnayak) [inline command/server.go]: `c.clusterListenerSetupFunc` will error out eventually. But...

Comment (jefferai) [inline command/server.go]: This doesn't even exist in current code :-)

File: helper/requestutil/forwarded_request.go [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+		return nil, err
+	}
+
+	var fq ForwardedRequest
+	err = jsonutil.DecodeJSON(buf.Bytes(), &fq)
+	if err != nil {
+		return nil, err
+	}
+
+	buf.Reset()
```
Comment (vishalnayak) [inline helper/requestutil/forwarded_request.go]: We could either use the `buf.Close()` here or just delete `buf.Close()`

File: vault/cluster.go [hunk 5]
```diff
@@ -116,3 +248,252 @@ func (c *Core) setupCluster() error {
...
+	c.clusterListenerShutdownCh = make(chan struct{})
+	c.clusterListenerShutdownSuccessCh = make(chan struct{})
+
+	go func() {
+		<-c.clusterListenerShutdownCh
+		c.logger.Printf("[TRACE] core/startClusterListener: shutting down listeners")
+		for _, tlsLn := range tlsLns {
+			tlsLn.Close()
+		}
+		close(c.clusterListenerShutdownSuccessCh)
```
Comment (vishalnayak) [inline vault/cluster.go]: Should we also have a `c.clusterListenerShutdownCh = nil` here?

File: vault/init.go [hunk 6]
```diff
@@ -173,8 +173,13 @@ func (c *Core) Initialize(barrierConfig, recoveryConfig *SealConfig) (*InitResul
 	}()
 
 	// Perform initial setup
+	if err := c.setupCluster(); err != nil {
```
Comment (vishalnayak) [inline vault/init.go]: Do we need a `c.ha` check here?

Comment (jefferai) [inline vault/init.go]: It's actually on purpose; even if HA is off we still want to generate
a cluster-id and persist it. *That said* if HA is off I will have it
skip key/cert generation.
