### PR TITLE
Use auth-saved cert name during renewals to avoid a panic.

### LINKED ISSUE #2749: Empty response on /auth/token/renew-self
Hi,

After we upgraded our Vault to v0.7.2 ('d28dd5a018294562dbc9a18c95554d52b5d12390'), we started to experience some issues. `consul-template` suddenly failed to renew its tokens:
```
2017/05/19 13:26:18.013552 [WARN] (view) vault.token: Put https://active.vault.service.consul:8200/v1/auth/token/renew-self: EOF (retry attempt 1 after "250ms")
```
The problem persisted after a restart of both, vault and consul-template, so I tried to reproduce it using curl and, sadly, succeeded:

```
$ curl --cert $MY_CERT --key $MY_KEY -H "X-Vault-Token: $MY_TOKEN"  -XPOST'https://active.vault.service.consul:8200/v1/auth/token/renew-self'
curl: (52) Empty reply from server
```
I would have expected either a renewed token or an error message instead of the empty reply. Most other features seem to continue working, consul-templates succeeds in fetching credentials during the initial period before it tries to renew the token.

Did I miss any relevant information? I did not see anything suspicious in the changelog.

### PR DESCRIPTION
**Pull request by jefferai**
Fixes #2749

### CODE REVIEW

File: builtin/credential/cert/path_login.go [hunk 1]
```diff
@@ -156,7 +156,12 @@ func (b *backend) verifyCredentials(req *logical.Request, d *framework.FieldData
 	clientCert := connState.PeerCertificates[0]
 
 	// Allow constraining the login request to a single CertEntry
-	certName := d.Get("name").(string)
+	var string certName
```
Comment (phaer) [inline builtin/credential/cert/path_login.go]: Pull requests works fine, after changing the typo `var string certName` to `var certName string`. Thank!
