### PR TITLE
Check if sys view is missing in GRPC sys view

### LINKED ISSUE #17878: panic: runtime error: invalid memory address or nil pointer dereference when register custom secret plugin
I'm writing a custom secret plugin based on built-in pki plugin and another based on transit built-in plugin.
Register plugins is ok with Vault 1.11.3. But now with Vault 1.12 and 1.12.1 I have errors:
```sh
panic: runtime error: invalid memory address or nil pointer dereference
vault    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x12e5e5b]
vault    |
vault    | goroutine 813 [running]:
vault    | github.com/hashicorp/vault/sdk/plugin.(*gRPCSystemViewServer).ReplicationState(0x505dea0?, {0xc00114a420?, 0x4bd306?}, 0x0?)
vault    |      /home/runner/work/vault/vault/sdk/plugin/grpc_system.go:224 +0x1b
vault    | github.com/hashicorp/vault/sdk/plugin/pb._SystemView_ReplicationState_Handler({0x5514040?, 0xc000f40260}, {0x6b5aff8, 0xc00114a3f0}, 0xc00114c1e0, 0x0)
vault    |      /home/runner/work/vault/vault/sdk/plugin/pb/backend_grpc.pb.go:939 +0x170
vault    | google.golang.org/grpc.(*Server).processUnaryRPC(0xc0011ae000, {0x6b702c0, 0xc0011aa340}, 0xc000cb7440, 0xc001190480, 0x9943880, 0x0)
vault    |      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfe
vault    | google.golang.org/grpc.(*Server).handleStream(0xc0011ae000, {0x6b702c0, 0xc0011aa340}, 0xc000cb7440, 0x0)
vault    |      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1620 +0xa2f
vault    | google.golang.org/grpc.(*Server).serveStreams.func1.2()
vault    |      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:922 +0x98
vault    | created by google.golang.org/grpc.(*Server).serveStreams.func1
vault    |      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:920 +0x28a
vault    | Error registering plugin pki: Put "http://0.0.0.0:8200/v1/sys/plugins/catalog/secret/pki": EOFvault exited with code 2
```

### PR DESCRIPTION
**Pull request by swenson**
And return an error instead of panicking.

This situation can occur if a plugin attempts to access the system view during setup when Vault is checking the plugin metadata.

Fixes #17878.

### CODE REVIEW

File: sdk/plugin/grpc_system.go [hunk 1]
```diff
@@ -18,6 +18,8 @@ import (
 	"google.golang.org/grpc/status"
 )
 
+var errMissingSystemView = errors.New("missing system view implementation: this method should not be called during plugin setup")
```
Comment (tomhjp) [inline sdk/plugin/grpc_system.go:21]: nit: Can we provide a bit more of a hint about when they _can_ call the method? I think the `Initialize` function is the first time they should reliably be able to call into the system and storage views.

**Review by tomhjp — COMMENTED** [review]
LGTM, although should we do the same for `GRPCStorageServer` too?

**Comment by tomhjp** [comment]
Also, probably warrants a bug changelog, as plugins shouldn't be able to trigger server panics, even if they do misbehave

File: sdk/plugin/grpc_system.go (hunk 1 above)
Comment (swenson) [reply sdk/plugin/grpc_system.go:21]: :+1:

**Comment by swenson** [comment]
Added the same checks in `GRPCStorageServer`, and added a changelog.

**Review by tomhjp — APPROVED** [review]
LGTM!

**Comment by swenson** [comment]
Thanks!
