### PR TITLE
UI - fix encoding for user-entered paths

### LINKED ISSUE #6282: web UI fails to list secrets when the path contains a #*+[(\ character
#### Describe the bug

the web UI fails to list secrets when a component of the path contains a #*+[(\ character

* **#some** is not properly escaped and is a URL fragment
* ***some** empty list, no secret displayed
* **+some** empty list, no secret displayed
* **[some** empty list, no secret displayed
* **(some** empty list, no secret displayed
* **\\some** is incorrectly translated into /some

#### To Reproduce

Steps to reproduce the behavior, using a live Vault server (not the -dev because the workaround will redirect to the page asking for the token) and the open parenthesis. 
   
* vault kv put 'secret/(some/2' 3=4
* visit http://vaultserver:8200//ui/vault/secrets/secret

* click on the link to **(some**

* the secret (2) is not displayed

#### Expected behavior

The secret is displayed

#### Workaround

* manually replace ( with %28 in the URL

* the secret is displayed (notice the %28 in the page)

#### Environment:

    Vault Server Version Vault v1.0.2
    Vault CLI Version Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')
    Server Operating System/Architecture: Debian GNU/Linux stretch amd64

### PR DESCRIPTION
**Pull request by meirish**
By default ember will encode and decode dynamic route segments for you, but there are several places where we're using star dynamic segments which _don't_ come with this behavior so we need to do that encoding and decoding ourselves.

This is also true in ember data - model ids are encoded when you pass them to ember data's `buildUrl` method. There are several places where we're constructing api URLs via string concatenation, and not properly encoding the user-entered items. 

Additionally, when passing the path into the filter box on the secret list page, we were not escaping the path so that we could create a valid Regex object. This meant that any characters that were valid in Regex pattern matching being present in the paths could potentially cause an error.

This PR changes the app to make sure we're encoding when passing elements to star segment urls, decoding when we're pulling params from those same routes, and properly escaping strings before passing them to the `Regex` constructor in the list-controller mixin.

Fixes #6282 .

### CODE REVIEW

File: ui/app/controllers/vault/cluster/secrets/backend/list.js [hunk 1]
```diff
@@ -4,50 +4,19 @@ import Controller from '@ember/controller';
...
 
   actions: {
-    setFilter(val) {
-      this.set('filter', val);
-    },
-
-    setFilterFocus(bool) {
-      this.set('filterFocused', bool);
-    },
-
```
Comment (johncowen) [inline ui/app/controllers/vault/cluster/secrets/backend/list.js]: Lots of removals here, I guess this is all covered in `ListController` now?

File: ui/app/adapters/secret-v2-version.js [hunk 2]
```diff
@@ -3,13 +3,14 @@ import { isEmpty } from '@ember/utils';
 import { get } from '@ember/object';
 import ApplicationAdapter from './application';
 import DS from 'ember-data';
+import { encodePath } from 'vault/utils/path-encoding-helpers';
 
 export default ApplicationAdapter.extend({
   namespace: 'v1',
   _url(backend, id, infix = 'data') {
-    let url = `${this.buildURL()}/${backend}/${infix}/`;
+    let url = `${this.buildURL()}/${encodePath(backend)}/${infix}/`;
```
Comment (johncowen) [inline ui/app/adapters/secret-v2-version.js]: Ah this was the other possibly user generated value here `infix`. I'm 99.9% sure it's probably hardcoded somewhere else I can see here. But just to triple sanity check with you in case its coming from a user generated value somewhere.

File: ui/app/adapters/secret-engine.js [hunk 3]
```diff
@@ -38,14 +39,14 @@ export default ApplicationAdapter.extend({
...
+      return this.ajax(`/v1/${encodePath(path)}/config/ca`, 'GET');
     }
     return;
   },
 
   queryRecord(store, type, query) {
     if (query.type === 'aws') {
-      return this.ajax(`/v1/${query.backend}/config/lease`, 'GET').then(resp => {
+      return this.ajax(`/v1/${encodePath(query.backend)}/config/lease`, 'GET').then(resp => {
         resp.path = query.backend + '/';
```
Comment (johncowen) [inline ui/app/adapters/secret-engine.js]: Again just a sanity check that this doesn't need encoding here, you encode it on 49 but not on 50

File: ui/app/adapters/role-jwt.js [hunk 4]
```diff
@@ -9,7 +10,7 @@ export default ApplicationAdapter.extend({
     let [path, role] = JSON.parse(id);
 
     let namespace = get(snapshot, 'adapterOptions.namespace');
-    let url = `/v1/auth/${path}/oidc/auth_url`;
+    let url = `/v1/auth/${encodePath(path)}/oidc/auth_url`;
     let redirect_uri = `${window.location.origin}${this.router.urlFor('vault.cluster.oidc-callback', {
       auth_path: path,
```
Comment (johncowen) [inline ui/app/adapters/role-jwt.js]: Little sanity check, line 13 you encode line 15 you don't. 99.9% sure thats ok, but just to check.

File: ui/app/adapters/transit-key.js [hunk 5]
```diff
@@ -47,29 +48,29 @@ export default ApplicationAdapter.extend({
...
     }
     if (action === 'datakey' && param) {
       // datakey action has `wrapped` or `plaintext` as part of the url
-      return `${urlBase}/${param}/${id}`;
+      return `${urlBase}/${param}/${encodePath(id)}`;
     }
     if (action === 'export' && param) {
       let [type, version] = param;
-      const exportBase = `${urlBase}/${type}-key/${id}`;
+      const exportBase = `${urlBase}/${type}-key/${encodePath(id)}`;
```
[the remark this answers is not in the document]
Comment (meirish) [reply ui/app/adapters/transit-key.js]: Yep, the type and action are hard-coded elsewhere in the app, the only thing the user does is name the transit key (which is the id).

Good spot on the array vs string, I'll follow up on that!

Re: `const`/`let` - yeah we need to decide as a team how we want to use this. I personally don't think const adds much most of the time (which is also why it's all over the place across the codebase), but we should decide on a standard and stick to it.

[the remark this answers is not in the document]
Comment (meirish) [reply ui/app/adapters/transit-key.js]: Ok, found the `param` bit - looks like in export it is an array, and datakey it's a string - I created a ticket internally to track that as we have upcoming work in that area which would be a good time to refactor it.

File: ui/app/controllers/vault/cluster/secrets/backend/list.js (hunk 1 above)
Comment (meirish) [reply ui/app/controllers/vault/cluster/secrets/backend/list.js]: Yep! It was previously, we just weren't using the mixin very much.

File: ui/app/utils/args-tokenizer.js [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+    } else if ((c === "'" || c === '"') && argString.indexOf(c, ii + 1) > 0 && !opening) {
+      opening = c;
+    }
+
+    if (!args[i]) args[i] = '';
+    args[i] += c;
+  }
+
+  return args;
+}
```
[the remark this answers is not in the document]
Comment (meirish) [reply ui/app/utils/args-tokenizer.js]: I have some changes I need to push - we went back to yargs-parser - but the change here had to do with handling " and ' in the web console - the tokenizer tries to be smart about where splitting should occur based on quotes and single / double quote break it. I'm thinking maybe we shouldn't support single or double quotes in paths in the web cli, but haven't landed anywhere yet.

The vars are from the source file - https://github.com/yargs/yargs-parser/blob/master/lib/tokenize-arg-string.js

File: ui/app/utils/path-encoding-helpers.js [hunk 7]
```diff
@@ -0,0 +1,14 @@
+import RouteRecognizer from 'route-recognizer';
+
+const {
+  Normalizer: { normalizePath, encodePathSegment },
+} = RouteRecognizer;
```
[the remark this answers is not in the document]
Comment (meirish) [reply ui/app/utils/path-encoding-helpers.js]: https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer/normalizer.ts#L20 has some good comments - I was thinking it'd be nice to have the same semantics as the router. I think for adapter use it's not strictly necessary, but decoded slashes still look nicer.

File: ui/package.json [hunk 8]
```diff
@@ -106,13 +107,14 @@
...
     "qunit-dom": "^0.7.1",
+    "route-recognizer": "^0.3.4",
     "sass-svg-uri": "^1.0.0",
     "string.prototype.endswith": "^0.2.0",
     "string.prototype.startswith": "^0.2.0",
     "text-encoder-lite": "1.0.0",
     "walk-sync": "^0.3.3",
     "xstate": "^3.3.3",
-    "yargs-parser": "^10.0.0"
+    "yargs-parser": "^12.0.0"
```
[the remark this answers is not in the document]
Comment (meirish) [reply ui/package.json]: We tried upgrading first, then pulled in the file we were using - but this has changed in the latest back to 10.

File: ui/tests/acceptance/secrets/backend/kv/secret-test.js [hunk 9]
```diff
@@ -259,4 +259,44 @@ module('Acceptance | secrets/secret/create', function(hooks) {
...
+      '{',
+      '|',
+      '}',
+      '~',
+      '[',
+      '\\',
+      ']',
+      '^',
+      '_',
+    ].map(char => `${char}some`);
```
[the remark this answers is not in the document]
Comment (meirish) [reply ui/tests/acceptance/secrets/backend/kv/secret-test.js]: 😄 - we wanted to recreate the script from the reported issue, and doing it this way meant we got to test the web cli too (and found it buggy) so win, win!

File: ui/app/adapters/secret-v2-version.js (hunk 2 above)
Comment (meirish) [reply ui/app/adapters/secret-v2-version.js]: Yep, it's hardcoded - it'll either be `data` or `metadata` - the apis for v2 have that prefix (infix here because there's /v1/backend_path at the start of all of them).

File: ui/app/adapters/secret-engine.js (hunk 3 above)
Comment (meirish) [reply ui/app/adapters/secret-engine.js]: Yeah we're only encoding when it goes to the server via ajax, and when it goes to the URL for routing - here it's going to be put in ember data for the model so we want the decoded version for display.

File: ui/app/adapters/role-jwt.js (hunk 4 above)
Comment (meirish) [reply ui/app/adapters/role-jwt.js]: Oh yep, urlFor is going to want encoded since it's router-related - thanks!

**Comment by meirish** [comment]
@johncowen Thanks for checking this out! I think I addressed all of the points you raised. The tests here just cover secret stuff as that's where Vault server is most lenient in allowed paths. I dug into the error we saw when I tried to create a transit key named `#foo` and it turns out that many endpoints in vault are more strict wrt characters, so that's disallowed at the server level.

**Comment by johncowen** [comment]
Ah yeah course! Makes sense. Good stuff, anyway thanks for the walkthrough and chat also, good to catch up!

John

**Comment by dupainaulevain** [comment]
@meirish thanks for the fix!
