### PR TITLE
Fix fetching parameters in token store when it's optionally in the URL

### LINKED ISSUE #1354: POST /auth/token/lookup not behaving as expected
The Vault project documentation for tokens lists two requests for calling /auth/token/lookup.  One with the token included in the path (GET) and the other including it in the request body (POST).

The GET method for this path works as documented, but has one downside for our organization; the token in the path is shown in plaintext in the audit log.

The POST method would appear to address this, except it returns the wrong token data.

When making a HTTP request against this endpoint, Vault returns the token data for the token found in the X-Vault-Token header, not the one in the request body.

Example curl command:

> curl -iv -H "X-Vault-Token: &lt;token_1&gt;" \
>     -X POST -d '{"token":"&lt;token_2&gt;"}' \
>     http://localhost:8200/v1/auth/token/lookup
> 

Is this intended?  Is the documentation just out of date?  I also noticed that under the POST subsection it has the Method listed as GET.

Reference: https://www.vaultproject.io/docs/auth/token.html  /auth/token/lookup[/token] section.

### PR DESCRIPTION
**Pull request by jefferai**
Fixes #1354

### CODE REVIEW

File: vault/token_store.go [hunk 1]
```diff
@@ -321,7 +341,7 @@ func NewTokenStore(c *Core, config *logical.BackendConfig) (*TokenStore, error)
 				Fields: map[string]*framework.FieldSchema{
 					"token": &framework.FieldSchema{
```
Comment (vishalnayak) [inline vault/token_store.go]: We can't remove this, is it? Or is this a BC case?

**Comment by vishalnayak** [comment]
Left one minor (optional) comment.
LGTM!

File: vault/token_store.go (hunk 1 above)
Comment (jefferai) [inline vault/token_store.go]: The reason it's there is that the code later queries `FieldData` for that value, and if it's not a declared part of the schema it actually panics. So it's here to satisfy that need, but the function ensures that the value is set to the request's client token value before it's processed.
