### PR TITLE
Redo API locking

### LINKED ISSUE #3435: Multiple Go client instances cannot be created if a custom HTTP client is passed
* Vault Version: Current HEAD
* Go Version: 1.9

**Expected Behavior:**
I should be able to construct multiple Client instances in a Go source code with a custom HTTP client.

**Actual Behavior:**
After creating the first client, no more clients can be created

**Steps to Reproduce:**

Add the following to `api/client_test.go` and run `go test`

```go
func TestClientMultipleInstances(t *testing.T) {
	_, err := NewClient(&Config{
		HttpClient: &http.Client{
			Transport: http.DefaultTransport,
		},
	})
	if err != nil {
		t.Fatal(err)
	}

	// this will fail
	_, err = NewClient(&Config{
		HttpClient: &http.Client{
			Transport: http.DefaultTransport,
		},
	})
	if err != nil {
		t.Fatal(err)
	}
}
```

you should see the following

```
--- FAIL: TestClientMultipleInstances (0.00s)
	client_test.go:66: protocol https already registered
```

**Important Factoids:**

This because of the following code in `NewClient()` that tries to register `https` multiple times:
```
tp := c.HttpClient.Transport.(*http.Transport)
if err := http2.ConfigureTransport(tp); err != nil {
	return nil, err
}
```

Because of the code above, the second call to `NewClient()` returns an error (via `http2.ConfigureTransport(tp)`.

### PR DESCRIPTION
**Pull request by jefferai**
Redo the API client quite a bit to make the behavior of NewClient more
predictable and add locking to make it safer to use with Clone() and if
multiple goroutines for some reason decide to change things.

In a few tests that don't use NewTestCluster, either for legacy or other
reasons, ensure that http2.ConfigureTransport is called.

Fixes #3435

### CODE REVIEW

File: api/client.go [hunk 1]
```diff
@@ -43,18 +43,21 @@ type WrappingLookupFunc func(operation, path string) string
 
 // Config is used to configure the creation of the client.
 type Config struct {
+	modifyLock sync.RWMutex
```
Comment (calvn) [inline api/client.go]: Nitpick here, but can we go for embedding sync.Mutex so that we call `c.Lock()` vs `c.modifyLock.Lock()`?

File: api/client.go [hunk 2]
```diff
@@ -237,10 +266,9 @@ func (c *Config) ReadEnvironment() error {
 	return nil
 }
 
-// Client is the client to the Vault API. Create a client with NewClient. Note:
-// it is not safe to modify client configuration from multiple goroutines at
-// once. Set configuration first, then run requests.
+// Client is the client to the Vault API. Create a client with NewClient.
 type Client struct {
+	modifyLock         sync.RWMutex
```
Comment (calvn) [inline api/client.go]: Same here, consider embedding sync.RWMutex

File: api/client.go [hunk 3]
```diff
@@ -453,6 +508,11 @@ func (c *Client) NewRequest(method, requestPath string) *Request {
 // a Vault server not configured with this client. This is an advanced operation
 // that generally won't need to be called externally.
 func (c *Client) RawRequest(r *Request) (*Response, error) {
+	c.modifyLock.RLock()
+	c.config.modifyLock.RLock()
+	defer c.config.modifyLock.RUnlock()
+	c.modifyLock.RUnlock()
```
Comment (calvn) [inline api/client.go]: I think it wouldn't hurt if we defer here.

File: api/client.go (hunk 1 above)
Comment (jefferai) [reply api/client.go]: I don't want to allow API consumers to toggle the lock...doing it this way makes it unexpired.

Comment (jefferai) [reply api/client.go]: Oops, unexported.

Comment (calvn) [reply api/client.go]: Add that makes sense, nvm then!

File: api/client.go (hunk 3 above)
Comment (jefferai) [reply api/client.go]: Doing so would mean holding the lock for the lifetime of the client request, including redirects and timeouts, even though we no longer need to access anything it's protecting.

Comment (calvn) [reply api/client.go]: You’re right, holding the client lock would be unnecessary.

File: api/client.go [hunk 4]
```diff
@@ -340,63 +339,118 @@ func (c *Client) SetAddress(addr string) error {
...
 }
 
-// Clone creates a copy of this client.
+// Clone creates a new client with the same configuration. Note that the same
+// underlying http.Client is used; modifying the client from more than one
+// goroutine at once may not be safe, so modify the client as needed and then
+// clone.
 func (c *Client) Clone() (*Client, error) {
-	return NewClient(c.config)
+	c.config.modifyLock.RLock()
```
Comment (briankassouf) [inline api/client.go]: Should this also call c.modifyLock.RLock()?

Comment (jefferai) [reply api/client.go]: oops yes, let me add
