### PR TITLE
audit: hash time.Time values in map fields

### LINKED ISSUE #2687: Audit broken in 0.7.1
Since the upgrade from 0.7.0 to 0.7.1 we ran into the following issue:

    client$ VAULT_TOKEN=<redacted> vault token-lookup
    error looking up token: Error making API request.
    
    URL: GET https://vault.example.com:8200/v1/auth/token/lookup-self
    Code: 500. Errors:
    
    * internal error

The Vault daemon reports:

    May 08 15:26:30 vault-101.example.com vault[53455]: 2017/05/08 15:26:30.836345 [ERROR] audit: panic during logging: request_path=auth/token/lookup-self error="reflect: reflect.Value.Set using value obtained using unexported field"
    May 08 15:26:30 vault-101.example.com vault[53455]: 2017/05/08 15:26:30.836397 [ERROR] core: failed to audit response: request_path=auth/token/lookup-self error=panic generating audit log

Using the root token still works:

    server# vault token-lookup | grep '^path'
    path            	auth/token/root

Enabled audit backend:

    server# vault audit-list
    Path   Type  Description  Replication Behavior  Options
file/  file               replicated            file_path=/var/log/vault/audit.log

If we disable audit logging, the 500 for the client disappears:

    server# vault audit-disable file
    Successfully disabled audit backend 'file' if it was enabled
    client$ VAULT_TOKEN=<redacted> vault token-lookup | grep '^path'
    path            	auth/token/create

Also when we enable the syslog backend, the client receives a 500 and the same error is reported by the Vault daemon.

### PR DESCRIPTION
**Pull request by mitchellh**
This enables audit.Hash to hash time.Time values that may exist as
direct fields in the map. This will error (instead of panic) for any
time.Time values that don't occur within map values. For example, this
does not support a time.Time within a slice. If that needs to be
supported then modifications will need to be made.

This also requires an update to reflectwalk (included in this PR). This
is a minimal change that allows SkipEntry to signal to skip an entire
struct. We do this because we don't want to walk any of time.Time since
we handle it directly.

Fixes #2687

### CODE REVIEW

File: audit/hashstructure.go [hunk 1]
```diff
@@ -232,6 +270,7 @@ func (w *hashWalker) Primitive(v reflect.Value) error {
 		mk := w.csData.(reflect.Value)
 		m.SetMapIndex(mk, resultVal)
 	default:
+		println(w.loc)
```
Comment (jefferai) [inline audit/hashstructure.go]: Can you remove this line?

File: audit/hashstructure.go [hunk 2]
```diff
@@ -188,6 +196,36 @@ func (w *hashWalker) SliceElem(i int, elem reflect.Value) error {
...
+	}
+
+	// Override location to be a MapValue. loc is set to None since we
+	// already "entered" the struct. We could do better here by keeping
+	// a stack of locations and checking the last entry.
+	w.loc = reflectwalk.MapValue
+
+	// Walk it as if it were a primitive value with the string value.
+	// This will replace the currenty map value (which is a time.Time).
+	if err := w.Primitive(reflect.ValueOf(v.Interface().(time.Time).String())); err != nil {
```
Comment (jefferai) [inline audit/hashstructure.go]: This puts out a Go-style string -- can you `.Format(time.RFC3339Nano)` it?

Comment (jefferai) [inline audit/hashstructure.go]: (I realize that since it gets hashed it basically doesn't really matter since you're unlikely to try to decode the value, but for consistency...)

**Comment by jefferai** [comment]
Thanks!
