### PR TITLE
Clarify api_addr related errors on VaultPluginTLSProvider

### LINKED ISSUE #3612: Vault plugin tls init error: "no address for the vault found"
**Environment:**

* Vault Version: Vault v0.9.0 ('254d0ab784a2135d05badab044aae462da7de563')
* Operating System/Architecture: MacOS

**Vault Config File:**

```
ui = true

plugin_directory="/Users/cleung/code/tmp/vault_plugins"
listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}

storage "file" {
  path = "/tmp/vault/data"
}
```

**Startup Log Output:**

```
2017/11/27 04:24:21.945330 [DEBUG] plugin: starting plugin: path=/Users/cleung/code/tmp/vault_plugins/vault-secrets-gen args=[/Users/cleung/code/tmp/vault_plugins/vault-secrets-gen]
2017/11/27 04:24:21.948187 [DEBUG] plugin: waiting for RPC address: path=/Users/cleung/code/tmp/vault_plugins/vault-secrets-gen
2017/11/27 04:24:21.954070 [ERROR] plugin.vault-secrets-gen: plugin tls init: error="no address for the vault found"
2017/11/27 04:24:21.955181 [DEBUG] plugin: plugin process exited: path=/Users/cleung/code/tmp/vault_plugins/vault-secrets-gen
2017/11/27 04:24:21.955249 [ERROR] core: failed to run existence check: error=plugin exited before we could connect
```

**Expected Behavior:**

Vault should initialize the plugin backend.

**Actual Behavior:**

Backend fails to initialize due to tls init error:

```
2017/11/27 04:26:12.112126 [DEBUG] plugin: waiting for RPC address: path=/Users/cleung/code/tmp/vault_plugins/vault-secrets-gen
2017/11/27 04:26:12.122844 [ERROR] plugin.vault-secrets-gen: plugin tls init: error="no address for the vault found"
2017/11/27 04:26:12.122923 [DEBUG] plugin: plugin process exited: path=/Users/cleung/code/tmp/vault_plugins/vault-secrets-gen
2017/11/27 04:26:12.123013 [ERROR] rollback: error rolling back: path=gen/ error=plugin exited before we could connect
```

**Steps to Reproduce:**

- Initialize
- Mount plugin backend
- Seal
- Unseal

**Important Factoids:**

**References:**

https://github.com/sethvargo/vault-secrets-gen/issues/2

### PR DESCRIPTION
**Pull request by calvn**
Closes #3612

### CODE REVIEW

File: helper/pluginutil/tls.go [hunk 1]
```diff
@@ -146,19 +146,19 @@ func VaultPluginTLSProvider(apiTLSConfig *api.TLSConfig) func() (*tls.Config, er
 
 		addrRaw := wt.Claims().Get("addr")
 		if addrRaw == nil {
-			return nil, errors.New("decoded token does not contain primary cluster address")
+			return nil, errors.New("decoded token does not contain primary cluster api_address")
```
Comment (jefferai) [inline helper/pluginutil/tls.go]: This error message isn't really good (originally, not due to your change) -- it's not really "primary cluster" it's "active node". But really just, the originating Vault process.

File: website/source/docs/internals/plugins.html.md [hunk 2]
```diff
@@ -32,6 +32,9 @@ plugin process' environment. This token is single use and has a short TTL. Once
 unwrapped, it provides the plugin with a uniquely generated TLS certificate and
 private key for it to use to talk to the original vault process.
 
+The [`api_addr`][api_addr] must be set in order for the plugin process establish
+communication with the Vault server during mount time.
+
```
Comment (jefferai) [inline website/source/docs/internals/plugins.html.md]: Might want a note here (and below) about when this will be set automatically.

File: helper/pluginutil/tls.go [hunk 3]
```diff
@@ -146,19 +146,19 @@ func VaultPluginTLSProvider(apiTLSConfig *api.TLSConfig) func() (*tls.Config, er
 
 		addrRaw := wt.Claims().Get("addr")
 		if addrRaw == nil {
-			return nil, errors.New("decoded token does not contain primary cluster address")
+			return nil, errors.New("decoded token does not contain the active node's api_address")
```
Comment (briankassouf) [inline helper/pluginutil/tls.go]: If we are going to underscore it here it should probably be `api_addr` to match the config value
