### PR TITLE
Auto-join support for IPv6 discovery

### LINKED ISSUE #12323: storage raft retry_join does not support public_v6, incorrectly parses IP addresses as URLs
**Describe the bug**
When retry_join is set to use `addr_type=public_v6`, Vault is unable to parse the IP addresses provided by go-discover. Vault uses url.Parse on [addrs](https://github.com/hashicorp/vault/blob/v1.7.3/vault/raft.go#L958), but these are IP addresses and not URLs. 

This appears to be a mismatch between go-discover's [Addrs method ](https://pkg.go.dev/github.com/hashicorp/go-discover#Discover.Addrs)and Vault's use of the values. go-discover returns IP addresses, not URLs. Attempting to use url.Parse on these values returns interesting edge-cases particularly with IPv6. I constructed a demo of this behavior: https://play.golang.org/p/HgBDYVHdEDX

**To Reproduce**
1. Start vault

**Expected behavior**
Vault discovers and joins other nodes.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Vault v1.7.3 (5d517c864c8f10385bf65627891bc7ef55f5e827)
* Vault CLI Version (retrieve with `vault version`):
Vault v1.7.3 (5d517c864c8f10385bf65627891bc7ef55f5e827)
* Server Operating System/Architecture:
CentOS 7 x86_64

Vault server configuration file(s):

```json
    ...
    "storage": {
        "raft": {
            "node_id": "example",
            "path": "/opt/vault/data",
            "retry_join": [
                {
                    "auto_join": "provider=aws tag_key=vault_discovery tag_value=test addr_type=public_v6",
                    "auto_join_scheme": "https",
                    "leader_client_cert_file": "/opt/vault/tls/tls.crt",
                    "leader_client_key_file": "/opt/vault/tls/tls.key",
                    "leader_tls_servername": "vault-test.com"
                }
            ]
        }
    },
```

**Additional context**

Log excerpt
```
2021-08-13T13:22:18.964Z [INFO]  core: [DEBUG] discover: Using provider "aws"
2021-08-13T13:22:18.964Z [INFO]  core: [DEBUG] discover-aws: Using region= tag_key=vault_discovery tag_value=key addr_type=public_v6
2021-08-13T13:22:18.964Z [INFO]  core: [DEBUG] discover-aws: No static credentials
2021-08-13T13:22:18.964Z [INFO]  core: [DEBUG] discover-aws: Using environment variables, shared credentials or instance role
2021-08-13T13:22:18.964Z [INFO]  core: [INFO] discover-aws: Region not provided. Looking up region in metadata...
2021-08-13T13:22:18.966Z [INFO]  core: [INFO] discover-aws: Region is us-east-1
2021-08-13T13:22:18.966Z [INFO]  core: [DEBUG] discover-aws: Creating session...
2021-08-13T13:22:18.966Z [INFO]  core: [INFO] discover-aws: Filter instances with vault_discovery=key
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Found 5 reservations
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Reservation r-073c85432ce0bbbde has 1 instances
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Found instance i-0b10b0923b9f22ca8
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Instance i-0b10b0923b9f22ca8 has 1 network interfaces
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Checking NetworInterfaceId eni-050ada1ed0547f204 on Instance i-0b10b0923b9f22ca8
2021-08-13T13:22:19.022Z [INFO]  core: [INFO] discover-aws: Instance i-0b10b0923b9f22ca8 has IPv6 dead:beef:fee1:000d:29bb:49d6:d459:8e90 on NetworkInterfaceId eni-050ada1ed0547f204
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Reservation r-0d0226ca62b2d27ec has 1 instances
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Found instance i-02fdf7f83cd99f6f2
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Instance i-02fdf7f83cd99f6f2 has 1 network interfaces
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Checking NetworInterfaceId eni-0c31e32c5791965cb on Instance i-02fdf7f83cd99f6f2
2021-08-13T13:22:19.022Z [INFO]  core: [INFO] discover-aws: Instance i-02fdf7f83cd99f6f2 has IPv6 dead:beef:fee1:000d:655c:d793:73b7:2822 on NetworkInterfaceId eni-0c31e32c5791965cb
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Reservation r-0ce21babecae77bb5 has 1 instances
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Found instance i-04031366838966b7d
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Instance i-04031366838966b7d has 1 network interfaces
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Checking NetworInterfaceId eni-0d76d634d410cd744 on Instance i-04031366838966b7d
2021-08-13T13:22:19.022Z [INFO]  core: [INFO] discover-aws: Instance i-04031366838966b7d has IPv6 dead:beef:fee1:000e:3e7c:4e31:bf61:f442 on NetworkInterfaceId eni-0d76d634d410cd744
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Reservation r-0d9cd8d490dcbba11 has 1 instances
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Found instance i-00c61eabef684c0b6
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Instance i-00c61eabef684c0b6 has 1 network interfaces
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Checking NetworInterfaceId eni-063e9feaa9c2fe84f on Instance i-00c61eabef684c0b6
2021-08-13T13:22:19.022Z [INFO]  core: [INFO] discover-aws: Instance i-00c61eabef684c0b6 has IPv6 dead:beef:fee1:000f:859c:9ee9:c55d:1ffe on NetworkInterfaceId eni-063e9feaa9c2fe84f
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Reservation r-08b05b70d2fb1e8fc has 1 instances
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Found instance i-01e16cef7618985de
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Instance i-01e16cef7618985de has 1 network interfaces
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Checking NetworInterfaceId eni-0cd647c8d05bba03e on Instance i-01e16cef7618985de
2021-08-13T13:22:19.022Z [INFO]  core: [INFO] discover-aws: Instance i-01e16cef7618985de has IPv6 dead:beef:fee1:000f:ce2b:1703:3cac:1b94 on NetworkInterfaceId eni-0cd647c8d05bba03e
2021-08-13T13:22:19.022Z [INFO]  core: [DEBUG] discover-aws: Found ip addresses: [dead:beef:fee1:000d:29bb:49d6:d459:8e90 dead:beef:fee1:000d:655c:d793:73b7:2822 dead:beef:fee1:000e:3e7c:4e31:bf61:f442 dead:beef:fee1:000f:859c:9ee9:c55d:1ffe dead:beef:fee1:000f:ce2b:1703:3cac:1b94]
2021-08-13T13:22:19.022Z [ERROR] core: failed to parse discovered address: error="parse "dead:beef:fee1:000d:29bb:49d6:d459:8e90": first path segment in URL cannot contain colon"
2021-08-13T13:22:19.022Z [ERROR] core: failed to parse discovered address: error="parse "dead:beef:fee1:000d:655c:d793:73b7:2822": first path segment in URL cannot contain colon"
2021-08-13T13:22:19.022Z [ERROR] core: failed to parse discovered address: error="parse "dead:beef:fee1:000e:3e7c:4e31:bf61:f442": first path segment in URL cannot contain colon"
2021-08-13T13:22:19.022Z [ERROR] core: failed to parse discovered address: error="parse "dead:beef:fee1:000f:859c:9ee9:c55d:1ffe": first path segment in URL cannot contain colon"
2021-08-13T13:22:19.022Z [ERROR] core: failed to parse discovered address: error="parse "dead:beef:fee1:000f:ce2b:1703:3cac:1b94": first path segment in URL cannot contain colon"
2021-08-13T13:22:19.022Z [ERROR] core: failed to retry join raft cluster: retry=2s
```
Related issue:
- #9531

### PR DESCRIPTION
**Pull request by dekimsey**
The go-discover library returns IP addresses and not URLs. It just so
happens net.URL parses "127.0.0.1", which isn't a valid URL.

Instead, we construct the URL ourselves. Being careful to check if it's
an ipv6 address and making sure it's in explicit form if so.

Fixes #12323

### CODE REVIEW

**Comment by pmmukh** [comment]
The PR looks pretty great! One thing, could you maybe try to add a test similar to this https://github.com/hashicorp/vault/blob/main/vault/external_tests/raft/raft_test.go#L129, that does the same but for ipv6 addresses ? It's probably gonna be fairly tricky, I can't exactly tell how much, but a test to show this change works would be nice i think.

**Comment by dekimsey** [comment]
I would be happy to try. I wanted to add a test when I wrote the PR up, but I couldn't figure out how to do that. I didn't see this area of the codebase though, so I'll give it a whirl!

**Comment by pmmukh** [comment]
sounds great, and thanks!

**Comment by ncabatoff** [comment]
The test `TestRaft_RetryAutoJoin` is of questionable value, because it doesn't actually exercise autojoin.  In fact, if you remove the `AutoJoin` field from the LeaderJoinInfo struct, or mangle it to be invalid go-discover syntax, the test doesn't fail, so I'm kind of inclined to remove it if we can't improve it.

Sadly we don't currently have a good way of running our automated CI tests with access to AWS, so it may well be that there's no good way to test this change other than manually.

**Comment by pmmukh** [comment]
aha gotcha, thanks for the clarification @ncabatoff ! In that case, please feel free to ignore the request for a test addition @dekimsey , once I've validated the fix works on my end, will merge this in.

File: vault/raft.go [hunk 1]
```diff
@@ -947,39 +947,28 @@ func (c *Core) JoinRaftCluster(ctx context.Context, leaderInfos []*raft.LeaderJo
 				}
 
 			case leaderInfo.AutoJoin != "":
+				// go-discover returns IPs
 				addrs, err := disco.Addrs(leaderInfo.AutoJoin, c.logger.StandardLogger(nil))
```
Comment (dekimsey) [inline vault/raft.go:951]: Minor tweak, should I just rename `addrs` to `ips` to make this more obvious for future maintainers? Or just leave it as is to mimic disco's naming?

Comment (pmmukh) [reply vault/raft.go:951]: ah good point, I agree that addrs is not clear on what the variable is and a rename might be nice, how does `clusterIPs` sound ?

File: vault/raft.go [hunk 2]
```diff
@@ -947,39 +947,28 @@ func (c *Core) JoinRaftCluster(ctx context.Context, leaderInfos []*raft.LeaderJo
...
-
-					if u.Scheme == "" {
-						scheme := leaderInfo.AutoJoinScheme
-						if scheme == "" {
-							// default to HTTPS when no scheme is provided
-							scheme = "https"
-						}
-
-						addr = fmt.Sprintf("%s://%s", scheme, addr)
+					if strings.Count(addr, ":") != 0 {
```
Comment (dekimsey) [inline vault/raft.go:966]: There's an [SO post](https://stackoverflow.com/questions/22751035/golang-distinguish-ipv4-ipv6) that seems to indicate to correctly validate IPv6 vs IPv4 addresses we should test for `>=2` as an IPv4 address could contain a port. I'm not sure if it's worth being pedantic about the test here since discovery's API states it returns IPs. But since it's name is `Addrs` ... I can see a future change in the library breaking this in one direction or another.

I don't know how defensive you'd like to write these bits.

File: vault/raft.go [hunk 3]
```diff
@@ -947,39 +947,28 @@ func (c *Core) JoinRaftCluster(ctx context.Context, leaderInfos []*raft.LeaderJo
...
+						// ipv6, make it explicit
```
Comment (pmmukh) [inline vault/raft.go:967]: Could you make this comment a little bit more descriptive also please ?

File: vault/raft.go (hunk 1 above)
Comment (dekimsey) [reply vault/raft.go:951]: Sure thing!

File: vault/raft.go (hunk 2 above)
Comment (pmmukh) [reply vault/raft.go:966]: Hmm, I think I'd honestly be fine with either, cause if go-discover starts returning ips with ports, then `u := fmt.Sprintf("%s://%s:%d", scheme, addr, port)` would also break. That being said, I'd still vote for `>=2` since that seems more correct.

Comment (pmmukh) [reply vault/raft.go:966]: Maybe explicitly call out this assumption of purely IP addresses sans scheme and ports in the comment above the `disco.Addrs` call, for future reference ? Long as we have that documented, and an upgrade in go-discover version breaks that assumption, I think we should be fine.

**Review by pmmukh — APPROVED** [review]
