### PR TITLE
Properly check for policy equivalency during renewal.

### LINKED ISSUE #1256: inconsistent logic between login and auth-renew
flow that causes problems:

you have a token that is associated with no policies according to its credential backend, after login.

the code in core.handleLoginRequest adds the "default" policy:
			// Add the default policy
			policyMap["default"] = true

later the expiration manager does RegisterAuth.
now you try to renew the token, and reach auth-renew. once again, your credential backend returns that there are no policies for it. 
the auth from cache, however, contains the default policy. 
the policies don't match.

in general, most credential backends will throw an exception here, because they don't know someone changed the policies behind their backs.

### PR DESCRIPTION
**Pull request by jefferai**
This introduces a function that compares two string policy sets while
ignoring the presence of "default" (since it's added by core, not the
backend), and ensuring that ordering and/or duplication are not failure
conditions.

Fixes #1256

### CODE REVIEW

File: helper/policies/policies.go [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+	}
+	sort.Strings(sortedA)
+	sort.Strings(sortedB)
+
+	// Finally, compare
+	if len(sortedA) != len(sortedB) {
+		return false
+	}
+
+	for i := range a {
```
Comment (vishalnayak) [inline helper/policies/policies.go]: If `a` contained `default` len(a) > len(sortedA).
So, I was thinking if this can go out of bounds?

**Comment by vishalnayak** [comment]
Just one comment. Other than that LGTM! :ship:
