### PR TITLE
Make the error and http code clearer when supplying wrong unseal key

### LINKED ISSUE #17792: unseal with wrong key returns HTTP 500 instead of 400 (again?)
**Describe the bug**

Attempting to unseal with an incorrect but valid key (ie. old key) returns a 500 instead of a 400.

**To Reproduce**
1. `vault server -dev`
2. `VAULT_ADDR=http://localhost:8200 vault operator seal`
3. `VAULT_ADDR=http://localhost:8200 vault operator unseal` and pass in an invalid token.

```
❯ ./vault server -dev
==> Vault server configuration:

             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Go Version: go1.19.2
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: inmem
                 Version: Vault v1.12.1, built 2022-10-27T12:32:05Z
             Version Sha: e34f8a14fb7a88af4640b09f3ddbb5646b946d9c

==> Vault server started! Log data will stream in below:
...
```

```
❯ VAULT_ADDR=http://localhost:8200 ./vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.12.1
Build Date      2022-10-27T12:32:05Z
Storage Type    inmem
Cluster Name    vault-cluster-7eb7d897
Cluster ID      1ff6d010-8f4d-d22b-081d-6eb6542bcb5c
HA Enabled      false

❯ VAULT_ADDR=http://localhost:8200 ./vault operator seal
Success! Vault is sealed.

❯ VAULT_ADDR=http://localhost:8200 ./vault operator unseal
Unseal Key (will be hidden): <ENTER INCORRECT KEY>
Error unsealing: Error making API request.

URL: PUT http://localhost:8200/v1/sys/unseal
Code: 500. Errors:

* unable to retrieve stored keys: failed to decrypt keys from storage: cipher: message authentication failed

❯ VAULT_ADDR=http://localhost:8200 ./vault operator unseal
Unseal Key (will be hidden): <ENTER CORRECT KEY>
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.12.1
Build Date      2022-10-27T12:32:05Z
Storage Type    inmem
Cluster Name    vault-cluster-7eb7d897
Cluster ID      1ff6d010-8f4d-d22b-081d-6eb6542bcb5c
HA Enabled      false
```

**Expected behavior**
The error returns is a 400 error, clearly indicating a client/request issue and not a server error.

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```
❯ VAULT_ADDR=http://localhost:8200 ./vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.12.1
Build Date      2022-10-27T12:32:05Z
Storage Type    inmem
Cluster Name    vault-cluster-7eb7d897
Cluster ID      1ff6d010-8f4d-d22b-081d-6eb6542bcb5c
HA Enabled      false
```

* Vault CLI Version (retrieve with `vault version`):

```
❯ ./vault version
Vault v1.12.1 (e34f8a14fb7a88af4640b09f3ddbb5646b946d9c), built 2022-10-27T12:32:05Z
```

* Server Operating System/Architecture:

Vault server configuration file(s):

N/A (default in-memory database with no config)

**Additional context**
We encountered this on an update from 1.10.3 -> 1.12.1. I confirmed issue is present on both versions.

Looks like this might be a regression? This was previously an issue and fixed in #8425.

### PR DESCRIPTION
**Pull request by nsimons**
The error message inspection is the same as used elsewhere in the code (vault/barrier_aes_gcm.go).
ErrInvalidKey is already handled as a http 400 response in http/sys_seal.go, so we can simply use it in vault/seal.go to get http 400.

Regarding the error message, omitting the "message authentication failed" part, as it is printed to the end user.

Fixes #17792

### CODE REVIEW

**Comment by hghaf099** [comment]
@nsimons Thanks for submitting this PR. Copying my response from the linked issue: 
I just checked the response error code going back to Vault 1.8, and we have always returned 500 error code if the unseal key is a properly b64 encoded key, however, it is invalid. On the other hand, providing an improper key, like unseal-key=1, to the unseal API will return the following though:
```
Error unsealing: Error making API request.

URL: PUT http://localhost:8200/v1/sys/unseal
Code: 400. Errors:

* 'key' must be a valid hex or base64 string
```
Note that changing this now would be considered backwards incompatible. I am going to close this ticket for now. Please reopen this issue or open a new one for further discussions.

**Comment by hghaf099** [comment]
@nsimons Thanks for contributing to Vault. We discussed the issue internally, and we would like to get the issue fixed. Would you please add a test (preferably a table test) to iterate through various cases to make sure the unseal behaviour is consistent? It would be good to see the same error code for all cases.

**Comment by nsimons** [comment]
Thanks for the guidance! Table test added, with some unseal cases. Is this more or less what you were after?

The test uses single key shard threshold so that we get the errors out. With higher threshold the invalid keys are quite often "blindly" accepted (HTTP 200) and the unseal mechanism waits for next key shard. But I guess this is by design.

Found one other return branch where it would make sense to have HTTP 400. The case is where key length is within the correct range, but the underlying AES cipher requires the length to be even. Two of the test cases tests for uneven byte length.

File: vault/seal.go [hunk 1]
```diff
@@ -484,6 +485,9 @@ func readStoredKeys(ctx context.Context, storage physical.Backend, encryptor *se
 
 	pt, err := encryptor.Decrypt(ctx, blobInfo, nil)
 	if err != nil {
+		if strings.Contains(err.Error(), "message authentication failed") {
+			return nil, &ErrInvalidKey{Reason: "failed to decrypt keys from storage"}
```
Comment (hghaf099) [inline vault/seal.go:489]: What do you think about including the error in the failed reason?

Comment (nsimons) [reply vault/seal.go:489]: To me the 'message authentication failed' part does not add any value. But to other maybe it does? I'm fine either way.
As a reminder, this is how the different options now look. Let me know which one is preferable:

Main branch:

> Error unsealing: Error making API request.
>
> URL: PUT http://127.0.0.1:8200/v1/sys/unseal
> Code: 500. Errors:
>
> * unable to retrieve stored keys: failed to decrypt keys from storage: cipher: message authentication failed

Current patch set:

>Error unsealing: Error making API request.
>
>URL: PUT http://127.0.0.1:8200/v1/sys/unseal
>Code: 400. Errors:
>
>* unable to retrieve stored keys: invalid key: failed to decrypt keys from storage

If we add the error in the reason:
>Error unsealing: Error making API request.
>
>URL: PUT http://127.0.0.1:8200/v1/sys/unseal
>Code: 400. Errors:
>
>* unable to retrieve stored keys: invalid key: failed to decrypt keys from storage: cipher: message authentication failed

File: http/sys_seal_test.go [hunk 2]
```diff
@@ -156,15 +160,93 @@ func TestSysUnseal(t *testing.T) {
...
+		// other key tests
+		{
+			"empty key",
+			"",
+			http.Response{StatusCode: 400},
+		},
+		{
+			"key with bad format",
+			"ThisKeyIsNeitherB64NorHex",
+			http.Response{StatusCode: 400},
```
[the remark this answers is not in the document]
Comment (nsimons) [reply http/sys_seal_test.go]: Fixed

File: vault/seal.go (hunk 1 above)
Comment (hghaf099) [reply vault/seal.go:489]: Thanks for providing example outputs. The reason I asked for including the error is that there could be other code paths that fail. Then two failures would have similar prefix of `unable to retrieve stored keys: invalid key: failed to decrypt keys from storage`. Adding the error would differentiate a bit as to what happened.

**Comment by hghaf099** [comment]
Thanks for working on this issue. 
A couple of additional tests would be good to be added. One is testing at least another seal type. Second, testing unseal having multipart keys. I was able to trigger a couple of 500 error codes which were returned from [here](https://github.com/hashicorp/vault/blob/c73a6a4a9e5d5b4e27a51102c8243351d40f1386/vault/core.go#LL1558C2-L1558C2) and [here](https://github.com/hashicorp/vault/blob/c73a6a4a9e5d5b4e27a51102c8243351d40f1386/vault/seal_autoseal.go#L395). The latter was found while configuring GCP seal, and unsealing with valid unseal keys from another cluster.

File: vault/seal.go (hunk 1 above)
Comment (nsimons) [reply vault/seal.go]: Yeah, makes sense. I added the error.

**Comment by nsimons** [comment]
Thanks! I added test cases for multi key-shards and AutoUnseal seal config. The two code locations that you found are hit by those test cases.

**Review by raskchanky — APPROVED** [review]
Looks good! Thanks for the contribution @nsimons
