### PR TITLE
VAULT-30877: Repopulate AWS static creds queue in initialize

### LINKED ISSUE #21935: Bug: HA cluster failover breaks AWS static role rotation
**Describe the bug**

AWS Static Role rotation stops when active node moves within a HA cluster

**To Reproduce**

1. Configure a three-node HA Vault cluster with Raft storage backend.
2. Configure AWS secrets engine with root user credentials.
3. Configure an AWS static-role with rotation period (e.g. 5m).
   `vault write aws/static-roles/foo username=foo rotation_period=300`
4. Confirm static role credentials are returned correctly and rotated according to the defined rotation period.
   `vault read aws/static-creds/foo && sleep 310 && vault read aws/static-creds/foo`
5. Force active node change.

**Expected behavior**

Static role credentials continue to be rotated according to the configured rotation period.

**Actual behavior**

Static role credentials completely stop being rotated.

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.14.0
* Vault CLI Version (retrieve with `vault version`): v1.14.0
* Server Operating System/Architecture: Debian 12 / amd64

Vault server configuration file(s):

```hcl
cluster_name = "vault"

api_addr = "https://vault.example.com:443"

# Listener: https://www.vaultproject.io/docs/configuration/listener/tcp
listener "tcp" {
  address = "0.0.0.0:8200"

  tls_cert_file   = "/etc/vault.d/vault.example.com.crt"
  tls_key_file    = "/etc/vault.d/vault.example.com.key"
  tls_min_version = "tls13"

  tls_disable_client_certs = "true"

  x_forwarded_for_authorized_addrs = ["10.12.0.0/24", "10.13.0.0/24"]
}

# UI: https://www.vaultproject.io/docs/configuration/ui/index.html
ui = true

cluster_addr = "https://vault-3.example.com:8201"

storage "raft" {
  path = "/opt/vault/"
  node_id = "vault-3"

  leader_ca_cert_file = "/etc/vault.d/raft_ca.crt"
  leader_client_cert_file = "/etc/vault.d/vault-3_raft.crt"
  leader_client_key_file = "/etc/vault.d/vault-3_raft.key"

  performance_multiplier = 1

  retry_join {
    leader_api_addr = "https://vault-1.example.com:8200"
  }
  retry_join {
    leader_api_addr = "https://vault-2.example.com:8200"
  }
}

log_level = "info"

plugin_directory = "/usr/local/lib/vault"
```

### PR DESCRIPTION
**Pull request by miagilepner**
### Description
Closes #21935 

Use the initialize function to re-populate the rotation queue on an active node. Store the credential's expiration value in storage and update it when it changes.

### TODO only if you're a HashiCorp employee
- [x] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport  
  to N, N-1, and N-2, using the `backport/ent/x.x.x+ent` labels. If this PR is in the CE repo, you should only backport to N, using the `backport/x.x.x` label, not the enterprise labels.
    - [ ] If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts-vault-enterprise-version) of Vault. To ensure this, use **all** available enterprise labels.
- [ ] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
  of a public function, even if that change is in a CE file, _double check_ that
  applying the patch for this PR to the ENT repo and running tests doesn't
  break any tests. Sometimes ENT only tests rely on public functions in CE
  files.
- [x] **Jira:** If this change has an associated Jira, it's referenced either
  in the PR description, commit message, or branch name.
- [ ] **RFC:** If this change has an associated RFC, please link it in the description.
- [ ] **ENT PR:** If this change has an associated ENT PR, please link it in the
  description. Also, make sure the changelog is in this PR, _not_ in your ENT PR.

### CODE REVIEW

File: builtin/logical/aws/rotation_test.go [hunk 1]
```diff
@@ -437,3 +448,135 @@ func TestRequeueOnError(t *testing.T) {
...
+	role3Secret := getSecret(client, "role3")
+
+	verifySecretsRotated := func(c *api.Client, originalRole1Secret, originalRole2Secret, originalRole3Secret string) (updatedRole1Secret, updatedRole2Secret string) {
+		testhelpers.RetryUntil(t, 5*time.Second, func() error {
+			// verify that both secrets with a low rotation period get rotated
+			updatedRole1Secret = getSecret(c, "role1")
+			updatedRole2Secret = getSecret(c, "role2")
+
+			if originalRole1Secret == updatedRole1Secret && originalRole2Secret == updatedRole2Secret {
+				return fmt.Errorf("secrets haven't been rotated")
```
Comment (fairclothjm) [inline builtin/logical/aws/rotation_test.go:560]: nit: Is there a way to make this error point to the test file? Instead of the testhelpers.go file:

```
    testhelpers.go:726: did not complete before deadline, err: secrets haven't been rotated
```

**Review by fairclothjm — APPROVED** [review]
LGTM! Thanks @miagilepner for picking this up!

**Comment by fairclothjm** [comment]
I was testing this today and after stopping and restarting Vault (with vcm) I am getting an error:

```
2024-10-30T16:38:50.504-0500 [ERROR] secrets.aws.aws_25fb669c: failed to create credential, re-queueing:
  error=
  | iam user didn't exist, or username/userid didn't match: unable to validate username "demo-jmfaircloth@hashicorp.com": NoCredentialProviders: no valid providers in chain. Deprecated.
  | \tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors

2024-10-30T16:38:50.504-0500 [ERROR] rollback: error rolling back: path=aws/
  error=
  | 1 error occurred:
  | \t* error(s) occurred while rotating expired static credentials: 1 error occurred:
  | \t* iam user didn't exist, or username/userid didn't match: unable to validate username "demo-jmfaircloth@hashicorp.com": NoCredentialProviders: no valid providers in chain. Deprecated.
  | \tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors
  ```

I am not sure if this is just my setup though.

**Comment by miagilepner** [comment]
@fairclothjm interesting, how are you setting this up? I tested it now with vcm using:
```bash
$ vault write aws/config/root \
  access_key=<redacted> \
  secret_key=<redacted>     # this is an IAM user with username demo-mia.epner@hashicorp.com 

$ vault write aws/static-roles/test-role \
  username=demo-mia.epner@hashicorp.com-static \
  rotation_period=1m        # this is a separate IAM user 
```

I didn't see any errors in the server logs from the rollbacks.

File: builtin/logical/aws/rotation_test.go (hunk 1 above)
Comment (miagilepner) [reply builtin/logical/aws/rotation_test.go:560]: That's a good idea! I added a t.Helper() to the testhelpers function, so now we see:

```
    rotation_test.go:554: did not complete before deadline, err: secrets haven't been rotated

```

**Comment by fairclothjm** [comment]
@miagilepner Thanks, I was using the same user for the vault admin and static user. 😅 Now I am working through a policy issue with my vault admin user.

**Comment by fairclothjm** [comment]
@miagilepner I got it working. Apparently the permission boundary I am using requires a certain naming convention to function properly.
