### PR TITLE
Fix automatic token set for plugin unwrap requests

### LINKED ISSUE #7176: Using $VAULT_TOKEN environment variable in transit unseal as suggested by docs breaks custom auth plugins
**Description**
The docs in transit unseal https://www.vaultproject.io/docs/configuration/seal/transit.html recommends that using the environment variable $VAULT_TOKEN to pass the token used to unseal Vault.

However, if you do that, custom auth plugins get broken because $VAULT_TOKEN is passed into the plugin process --and you end up with cryptic errors when trying to unwrap because the plugin process somehow is using the $VAULT_TOKEN which is a token to access the transit engine for unseal, -- not the token to get the secrets so the plugin can communicate to vault.

> 
> plugin tls init: error="error during token unwrap request: Error making API request.
>  
> URL: PUT http://127.0.0.1:8200/v1/sys/wrapping/unwrap
> Code: 403. Errors:
>  
> * permission denied" timestamp=2019-07-23T17:59:27.227-0700

It looks similar to the error mentioned in this thread.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/twO5nK-40nc/skGKvvsHDAAJ    and this github issue
https://github.com/hashicorp/vault/issues/4630

**Steps to reproduce the behavior:**
1.  Setup Vault to use transit unseal, pass in token using environment variable VAULT_TOKEN
2. Try to enable a custom auth plugin
3. See error

**Expected behavior**
It should be possible to pass the Vault token for transit using environment variable AND use custom auth plugin.

**Version it occured on**
Vault 1.1.2

Or else it should be documented combination does not work

### PR DESCRIPTION
**Pull request by michelvocks**
Inspired by https://github.com/hashicorp/vault/pull/8056 `NewClient` automatically sets the token for the client even tho we don't need a token to send a `sys/wrapping/unwrap`-request.

Fixes #7176

### CODE REVIEW

**Comment by calvn** [comment]
I think it there are scenarios where we would still want to provide a token for the unwrap request, such as cases where a different token has permission to access that particular cubbyhole, for auditing purposes, or reducing the use count of the request token.

**Comment by briankassouf** [comment]
Did you have `VAULT_TOKEN` env set? I think this is fine since it's in the context of a plugin, not all unwrap requests.

**Comment by calvn** [comment]
I totally overlooked that this was specific to plugins..

**Comment by michelvocks** [comment]
> I think it there are scenarios where we would still want to provide a token for the unwrap request, such as cases where a different token has permission to access that particular cubbyhole, for auditing purposes, or reducing the use count of the request token.

@briankassouf is right. This is only for plugins and I should have mentioned that in my initial description.

File: api/plugin_helpers.go [hunk 1]
```diff
@@ -118,6 +118,9 @@ func VaultPluginTLSProvider(apiTLSConfig *TLSConfig) func() (*tls.Config, error)
 			return nil, errwrap.Wrapf("error during api client creation: {{err}}", err)
 		}
 
+		// Reset token value to make sure nothing has been set by default
+		client.SetToken("")
```
Comment (catsby) [inline api/plugin_helpers.go]: There's a `ClearToken()` method, should we use that?

- https://github.com/hashicorp/vault/blob/ca83be21b401b0ff35f41ae5b75f4650e5319770/api/client.go#L598

Comment (michelvocks) [reply api/plugin_helpers.go]: Ah yes. Good catch!

**Comment by voiprodrigo** [comment]
Hello. Can this fix be reviewed? I faced the exact issue described in #7176 with Vault 1.6.1.
