### PR TITLE
approle: Make invalid role_id a 400 error instead of 500

### LINKED ISSUE #4451: Error 500 on login with approle auth backend and invalid role_id
**Environment:**

* Vault Version: 0.10.0
* Operating System/Architecture: docker image vault:0.10.0

**Expected Behavior:**

When trying to login with an unknown role_id, we should have a nice error message like today and a 403 http status code.

**Actual Behavior:**

We have a 500 status code

example:
```
Status: 500 ; Body: {"errors":["failed to validate credentials: invalid role_id \"__nope__\""]}
```

**Steps to Reproduce:**

```
echo 'listener "tcp" {
  address = "0.0.0.0:8201"
  tls_disable = 1
}' > /tmp/vault-500-approle.hcl

docker run -e VAULT_ADDR=http://127.0.0.1:8201 -v /tmp/vault-500-approle.hcl:/tmp/vault-500-approle.hcl -d --rm --name=vault-500-approle vault:0.10.0 vault server -dev -dev-root-token-id=root -config=/tmp/vault-500-approle.hcl
docker exec vault-500-approle sh -c 'vault login root && vault auth enable approle'
curl -w "Response: %{http_code}" -X POST "http://$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' vault-500-approle):8201/v1/auth/approle/login" --data '{"role_id":"__nope__","secret_id":"__nope__"}'
docker stop vault-500-approle
```

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #4451

### CODE REVIEW

File: builtin/credential/approle/validation.go [hunk 1]
```diff
@@ -68,48 +68,34 @@ type secretIDAccessorStorageEntry struct {
 	SecretIDHMAC string `json:"secret_id_hmac" structs:"secret_id_hmac" mapstructure:"secret_id_hmac"`
 }
 
-// Checks if the Role represented by the RoleID still exists
-func (b *backend) validateRoleID(ctx context.Context, s logical.Storage, roleID string) (*roleStorageEntry, string, error) {
+// Validates the supplied RoleID and SecretID
+func (b *backend) validateCredentials(ctx context.Context, req *logical.Request, data *framework.FieldData) (*roleStorageEntry, string, map[string]string, string, error, error) {
```
Comment (kalafut) [inline builtin/credential/approle/validation.go]: Consider naming the return parameters. The list is long, many are strings, and much of the usage is `nil, "",...` which makes it hard to infer what they even are.

File: builtin/credential/approle/validation.go [hunk 2]
```diff
@@ -152,7 +138,7 @@ func (b *backend) validateCredentials(ctx context.Context, req *logical.Request,
 		}
 	}
 
-	return role, roleName, metadata, secretID, nil, nil
+	return role, roleIDIndex.Name, metadata, secretID, nil, nil
```
Comment (kalafut) [inline builtin/credential/approle/validation.go]: Why do we return `secretID`? The only caller doesn't even use it.

Comment (vishalnayak) [reply builtin/credential/approle/validation.go]: I removed the function as it had a single caller.

File: builtin/credential/approle/path_login.go [hunk 3]
```diff
@@ -51,14 +53,186 @@ func (b *backend) pathLoginUpdateAliasLookahead(ctx context.Context, req *logica
...
+	}
+	if roleIDIndex == nil {
+		return logical.ErrorResponse(fmt.Sprintf("invalid role_id %q", roleID)), nil
+	}
+
+	roleName := roleIDIndex.Name
+
+	roleLock := b.roleLock(roleName)
+	roleLock.RLock()
+	defer roleLock.RUnlock()
```
Comment (jefferai) [inline builtin/credential/approle/path_login.go]: Do you actually need the lock after the roleEntry call? If not, can you just manually unlock instead of deferring until the end? That way you're not holding on to the role lock while also contending for the read/write locks for the secret ID.

File: builtin/credential/approle/path_login.go [hunk 4]
```diff
@@ -51,14 +53,186 @@ func (b *backend) pathLoginUpdateAliasLookahead(ctx context.Context, req *logica
...
+		if err != nil {
+			return nil, errwrap.Wrapf("failed to create HMAC of role_name: {{err}}", err)
+		}
+
+		entryIndex := fmt.Sprintf("%s%s/%s", role.SecretIDPrefix, roleNameHMAC, secretIDHMAC)
+
+		secretIDLock := b.secretIDLock(secretIDHMAC)
+		secretIDLock.RLock()
+		secretIDUnlockFunc := secretIDLock.RUnlock
+		defer func() {
```
Comment (jefferai) [inline builtin/credential/approle/path_login.go]: Honestly, I'd prefer if you didn't do this.  In the two return scenarios below you could just unlock manually. Then when you're in the switch, in the first case you know it'll stay a read lock and you can immediately defer the RUnlock; in the second case you know you'll need to switch it so you can runlock, lock, immediately defer the write lock.
