### PR TITLE
UI - token expiration calculation

### LINKED ISSUE #5390: Periodic AppRole tokens can be considered expired by the UI while still valid
**Describe the bug**

Periodic AppRole tokens can be considered expired by the UI while still able to renew themselves and access secrets.

**To Reproduce**
Scripted - https://gist.github.com/Ubeek/88334ce6cf4486cdfa48eb1fcd700b61

Manual steps to reproduce the behavior:
1) Launch dev vault server
2) Enable approle auth
3) Create a policy granting read/write to an arbitrary path (e.g. secret/approle_test) and populate it with a secret
4) Create an approle with a token TTL and period of 60 seconds, and a Max Token TTL of 0
5) Attach the above policy to the approle
6) Login with the Approle
7) Renew the approle every 30 seconds for 2 minutes
8) Attempt to read the arbitrary secret from above, this should work
9) Attempt to login to the Vault UI, this should present an error stating 'Your auth token expired on \<DATETIME\>. You will need to re-authenticate.'

**Expected behavior**

It is expected that if the token is valid for use on the CLI or via API, that it would also be valid for use with the UI.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.3 - 0.11.1
* Vault CLI Version (retrieve with `vault version`): 0.10.3 - 0.11.1
* Server Operating System/Architecture: CentOS 7 64bit, Ubuntu 16.04 & Windows 10

### PR DESCRIPTION
**Pull request by meirish**
The UI was calculating the expiration of the vault token incorrectly - this changes it to use either the `lease_duration` or the `ttl` when calculating the expiration.

Fixes #5390

Also fixes a visual glitch that was introduced in the 3.4 upgrade where you'd see both the logged in and logged out nav briefly when authenticating.

### CODE REVIEW

File: ui/app/services/auth.js [hunk 1]
```diff
@@ -95,18 +99,15 @@ export default Service.extend({
...
+    let now = this.now();
+    const ttl = resp.ttl || resp.lease_duration;
+    const tokenExpirationEpoch = now + ttl * 1e3;
+    this.set('expirationCalcTS', now);
+    return {
+      ttl,
       tokenExpirationEpoch,
-      leaseMilli,
     };
-    this.set('expirationCalcTS', Date.now());
```
Comment (madalynrose) [inline ui/app/services/auth.js]: We don't set this anymore now? Do we just calculate the expiration on the fly every time now?

Comment (meirish) [reply ui/app/services/auth.js]: Still there, just got moved up: https://github.com/hashicorp/vault/pull/5435/files/d153810d3491a11942fcd1fc62ee7dd97845d0ff#diff-10502f4cc8e730c6150cac0331e18b9bR106

Comment (madalynrose) [reply ui/app/services/auth.js]: aha!
