### PR TITLE
Fix #5973 on windows by disregarding errors when querying legacy cert path

### LINKED ISSUE #5973: Vault 1.0 - PKI - Read Certificate Broken on Filesystem Storage Backend on Windows Server 2012R2
**Describe the bug**
When using the PKI Engine with the Filesystem Storage Backend on Windows Server 2012R2 users are unable READ certificates after creation. However, users are still able to generate new certificates and are able to obtain the certificate at the time of generation.

Attempting to access a certificate after generation results in the following error message:

```
{
    "errors": [
        "error fetching certificate 46:ca:33:a2:53:d4:cc:86:ea:b5:3c:70:be:0b:f8:fb:83:2c:13:cd: open C:\\vault\\data\\logical\\06cc3646-6183-4192-e971-9c65b02c6049\\revoked\\_46:ca:33:a2:53:d4:cc:86:ea:b5:3c:70:be:0b:f8:fb:83:2c:13:cd: The filename, directory name, or volume label syntax is incorrect."
    ]
}
```

Upon inspecting the server it appears that the revoked directory is missing from the path. This is unusual for two reasons.

1. I assume VAULT is supposed to create these directories. This doesn't appear to be occuring.
2. The certificate has not been revoked - why is this folder necessary?

Server output:

```
    Directory: C:\Vault\Data\Logical\06cc3646-6183-4192-e971-9c65b02c6049


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/17/2018  11:18 AM                certs
d-----       12/17/2018  10:52 AM                config
d-----       12/17/2018  11:00 AM                role
-a----       12/17/2018  11:13 AM           1329 _ca
-a----       12/17/2018  11:13 AM            617 _crl
-a----       12/18/2018   9:17 AM            265 _urls
```

An additional difference I have noted:
The certificates stored in the `certs` directory above use dashes `-` instead of colons `:` in the filename. Perhaps this is an additional difference that's causing breakage?

**To Reproduce**
1. Install VAULT with the Filesystem Storage Backend on Windows Server 2012R2
2. Follow the guide here - https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine and stop after `STEP 4 - Request Certificates.`
3. Attempt to READ the certificate that we created - https://www.vaultproject.io/api/secret/pki/index.html#read-certificate

**Expected behavior**
The certificate in PEM formatting in the certificate key of the JSON object is returned.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Version         1.0.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.0.0 ('c19cef14891751a23eaa9b41fd456d1f99e7e856')
* Server Operating System/Architecture: Windows Server 2012R2 Datacenter

Vault server configuration file(s):

```ui = true

storage "file" {
  path    = "C:/vault/data"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 0
 tls_cert_file = "C:/vault/cert/**********.cert.pem"
 tls_key_file = "C:/vault/cert/**********.key.pem"
 tls_client_ca_file = "C:/vault/cert/ca-chain.cert.pem"
 tls_min_version = "tls12"
 tls_disable_client_certs = 1
}

```

**Additional context**

### PR DESCRIPTION
**Pull request by ncabatoff**
@jefferai suggested either disregarding the error here or skipping the legacy query when on windows; I chose to do the former as it seemed a smaller change.

### CODE REVIEW

File: builtin/logical/pki/cert_util.go [hunk 1]
```diff
@@ -262,11 +262,9 @@ func fetchCertBySerial(ctx context.Context, req *logical.Request, prefix, serial
 		return nil, nil
 	}
 
-	// Retrieve the old-style path
-	certEntry, err = req.Storage.Get(ctx, legacyPath)
-	if err != nil {
-		return nil, errutil.InternalError{Err: fmt.Sprintf("error fetching certificate %s: %s", serial, err)}
-	}
+	// Retrieve the old-style path.  We disregard errors here because they always manifest on windows, and thus the initial
+	// check for a revoked cert fails would return an error when the cert isn't revoked, preventing the happy path from working.
```
Comment (briankassouf) [inline builtin/logical/pki/cert_util.go]: Could you wrap your comments at a 80 width?

Comment (ncabatoff) [reply builtin/logical/pki/cert_util.go]: Done.
