### PR TITLE
Avoid unseal failure if plugin backends fail to setup during postUnseal

### LINKED ISSUE #3602: Cannot unseal vault with wrong plugin checksum
This issue is probably related to #3241, but covers another failure mode.
When having a vault plugin mounted, if the checksum set in `sys/plugins/catalog/stuff` is wrong, vault cannot be unsealed, and thus, the offending mount cannot be removed, essentially bricking the vault database. The unsealing fails with the following log: 
```
2017/11/20 15:53:41.048250 [INFO ] core: vault is unsealed
2017/11/20 15:53:41.050187 [INFO ] core: post-unseal setup starting
2017/11/20 15:53:41.052123 [INFO ] core: loaded wrapping token key
2017/11/20 15:53:41.052161 [INFO ] core: successfully setup plugin catalog: plugin-directory=/vault/plugins
2017/11/20 15:53:41.055848 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/11/20 15:53:41.056002 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/11/20 15:53:41.056228 [INFO ] core: successfully mounted backend: type=identity path=identity/
2017/11/20 15:53:41.111671 [ERROR] core: failed to create mount entry: path=somepath/ error=checksums did not match
2017/11/20 15:53:41.111731 [INFO ] core: pre-seal teardown starting
2017/11/20 15:53:41.111783 [INFO ] core: cluster listeners not running
2017/11/20 15:53:41.111869 [INFO ] core: pre-seal teardown complete
2017/11/20 15:53:41.111916 [ERROR] core: post-unseal setup failed: error=failed to setup mount table
2017/11/20 15:53:41.111941 [WARN ] core: vault is sealed
```

**Expected Behavior:**
Vault should unseal with a warnign and leave the offending mount inacessible. It should be possible to update the checksum and/or remove the mount.

### PR DESCRIPTION
**Pull request by calvn**
Fixes #3602

### CODE REVIEW

File: vault/auth.go [hunk 1]
```diff
@@ -460,10 +459,11 @@ func (c *Core) setupCredentials() error {
...
 			c.logger.Error("core: failed to create credential entry", "path", entry.Path, "error", err)
-			if errwrap.Contains(err, ErrPluginNotFound.Error()) && entry.Type == "plugin" {
-				// If we encounter an error instantiating the backend due to it being missing from the catalog,
-				// skip backend initialization but register the entry to the mount table to preserve storage
-				// and path.
+			if entry.Type == "plugin" {
+				// If we encounter an error instantiating the backend due to an error,
+				// skip backend initialization but register the entry to the mount table
+				// to preserve storage and path.
+				c.logger.Warn("core: skipping plugin-based credential entry", "path", entry.Path)
```
Comment (briankassouf) [inline vault/auth.go]: Can we output the error here so the user knows why it failed (plugin missing, bad SHA, etc.), and the same for mounts?

Comment (calvn) [reply vault/auth.go]: The error is printed out up top in https://github.com/hashicorp/vault/pull/3686/files#diff-444ea30b36f7a95d6672fd6fd9b7a87cR461.

Comment (jefferai) [reply vault/auth.go]: Pfft, _obviously_ @bk, _**duh**_

Comment (briankassouf) [reply vault/auth.go]: Ha, I even looked there and thought "Oh, it's only printing out the path", missed the error somehow :)
