### PR TITLE
Postgres: Correct parsing of multiline statements

### LINKED ISSUE #6098: Vault splits PostgreSQL policies on literal semicolons, breaking block statement
This is propably a regression, a similar issue was already fixed: #1619

I have the following json document to define a PostgreSQL database role:

```{
  "db_name": "${DBNAME}",
  "creation_statements": ["CREATE USER \"{{name}}\" WITH ENCRYPTED PASSWORD '{{password}}'",
                          "GRANT ALL PRIVILEGES ON DATABASE ${DBNAME} TO \"{{name}}\"",
                          "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO \"{{name}}\"",
                          "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO \"{{name}}\"",
                          "GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA PUBLIC TO \"{{name}}\"",
                          "DO \$\$BEGIN
                               FOR r IN
                               select 'ALTER TABLE \"' || table_schema || '\".\"' || table_name || '\" OWNER TO ' ||  \"{{name}}\" || ';' as a from information_schema.tables where table_schema = \"public\"
                               union all
                               select 'ALTER TABLE \"' || sequence_schema || '\".\"' || sequence_name || '\" OWNER TO ' ||  \"{{name}}\" || ';' as a from information_schema.sequences where sequence_schema = \"public\"
                               union all
                               select 'ALTER TABLE \"' || table_schema || '\".\"' || table_name || '\" OWNER TO ' ||  \"{{name}}\" || ';' as a from information_schema.views where table_schema = \"public\"
                               union all
                               select 'ALTER FUNCTION \"'||nsp.nspname||'\".\"'||p.proname||'\"('||pg_get_function_identity_arguments(p.oid)||') OWNER TO ' ||  \"{{name}}\" || ';' as a from pg_proc p join pg_namespace nsp ON p.pronamespace = nsp.oid where nsp.nspname = \"public\"
                               union all
                               select 'ALTER SCHEMA \"' || \"public\" || '\" OWNER TO ' ||  \"{{name}}\" union all select 'ALTER DATABASE \"' || ${DBNAME} || '\" OWNER TO ' ||  \"{{name}}\";
                               LOOP EXECUTE
                                    r.a;
                               END LOOP;
                           END\$\$;"],
  "default_ttl": "24h",
  "max_ttl": "24h"
}
```

The role is created, upon usage the database throws the following error:

unterminated dollar-quoted string at or near "$$BEGIN                               FOR r IN                               select 'ALTER TABLE "' || table_schema || '"."' || table_name || '" OWNER TO ' ||  "v-kubernet-keycloak-3E77ZGEvrwP01jtttfMj-1548335922" || '" at character 4

Seems as if vault splits the block statement into several statements on each semicolon, which is not good for block statements obviously.

The same behaviour was mentioned in #1619 and presumably fixed, but as far as i know that was the PostgreSQL module back then while I'm working with the database module (using vault 1.0)

### PR DESCRIPTION
**Pull request by tyrannosaurus-becks**
Fixes #6098 

Postgres was splitting statements on a semicolon. This would be fine normally, but sometimes people do send statements with semicolons that need to be parsed as a single query.

Example:
```
// User sends:
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='my_role') THEN CREATE ROLE my_role; END IF; END $$

// In the current state, Postgres executes the first piece as an independent piece
// causing a syntax error: 
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='my_role') THEN CREATE ROLE my_role

// After this PR, it will be sent as the original syntax:
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='my_role') THEN CREATE ROLE my_role; END IF; END $$
```

### CODE REVIEW

File: plugins/database/postgresql/postgresql.go [hunk 1]
```diff
@@ -206,6 +206,22 @@ func (p *PostgreSQL) CreateUser(ctx context.Context, statements dbplugin.Stateme
 
 	// Execute each query
 	for _, stmt := range statements.Creation {
+		// A postgres query may have multi lines, and if so, it will include the word
+		// "END". For example, this statement should be run as one transaction:
+		// "DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='my_role') THEN CREATE ROLE my_role; END IF; END $$"
+		if strings.Contains(stmt, "END") {
```
Comment (ncabatoff) [inline plugins/database/postgresql/postgresql.go]: What if the string "END" occurs naturally within the string, e.g. `APPEND`?  I feel like to make this safe we'd need to at least match only exact words, and ideally exclude anything within quoted delimiters.

Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql.go]: Ah, great point. I will change that.

Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql.go]: This feedback is incorporated in https://github.com/hashicorp/vault/pull/8512/commits/c80d37c5ae9d840d2c1f9704c8132f52defefb19 and test cases are added to verify the underlying logic.

File: plugins/database/postgresql/postgresql.go [hunk 2]
```diff
@@ -501,3 +516,48 @@ func (p *PostgreSQL) RotateRootCredentials(ctx context.Context, statements []str
...
+
+// extractQuotedStrings extracts 0 or many substrings
+// that have been single- or double-quoted. Ex:
+// `"Hello", silly 'elephant' from the "zoo".`
+// returns [ `"Hello"`, `'elephant'`, `"zoo"` ]
+func extractQuotedStrings(s string) ([]string, error) {
+	var result []string
+
+	// Find all double-quoted sub-strings.
+	reg, err := regexp.Compile(`"(.*?)"`)
```
Comment (ncabatoff) [inline plugins/database/postgresql/postgresql.go]: Why not include the delimiters inside the parens so they count as part of the match?  That way you won't inadvertently mangle the statement if it contains something like `"role"`.

**Comment by ncabatoff** [comment]
I wonder if it would make more sense to define a multiline string as one starting with `DO `.  That's AFAIK the only way to begin a multi-line statement.  And although dollar quoting is recommended for the body of the anonymous DO function, it's not required, so in theory they could put a multi-line statement within single quotes I think.

File: plugins/database/postgresql/postgresql.go (hunk 2 above)
Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql.go]: Sure, addressed in https://github.com/hashicorp/vault/pull/8512/commits/59979df86837a536a29dc470d8b5e6f62a0a475b

**Comment by tyrannosaurus-becks** [comment]
Hi @ncabatoff ! Thanks for the review! :-)

Regarding this:

>I wonder if it would make more sense to define a multiline string as one starting with DO . That's AFAIK the only way to begin a multi-line statement. And although dollar quoting is recommended for the body of the anonymous DO function, it's not required, so in theory they could put a multi-line statement within single quotes I think.

I did some poking around and it looks like [it would be possible](https://www.postgresql.org/docs/9.2/plpgsql-structure.html) for multiline statements to not include DO.

**Comment by ncabatoff** [comment]
> I did some poking around and it looks like [it would be possible](https://www.postgresql.org/docs/9.2/plpgsql-structure.html) for multiline statements to not include DO.

Hmm, you're right.  I was making the assumption that they wouldn't be issuing DDL statements because that would be weird, but people do weird stuff all the time...

File: plugins/database/postgresql/postgresql.go [hunk 3]
```diff
@@ -501,3 +516,48 @@ func (p *PostgreSQL) RotateRootCredentials(ctx context.Context, statements []str
...
+	}
+	stmtWithoutLiterals := stmt
+	for _, literal := range literals {
+		stmtWithoutLiterals = strings.Replace(stmt, literal, "", -1)
+	}
+	// Now look for the word "END" specifically. This will miss any
+	// representations of END that aren't surrounded by spaces, but
+	// it should be easy to deal with. This approach was chosen to
+	// avoid accidently matching with unintended words like "APPEND".
+	return strings.Contains(stmtWithoutLiterals, " END ")
```
Comment (ncabatoff) [inline plugins/database/postgresql/postgresql.go]: You could use a regexp to look for only END surrounded by word boundaries, i.e. `\bEND\b`.

File: plugins/database/postgresql/postgresql.go [hunk 4]
```diff
@@ -501,3 +516,48 @@ func (p *PostgreSQL) RotateRootCredentials(ctx context.Context, statements []str
...
+
+// extractQuotedStrings extracts 0 or many substrings
+// that have been single- or double-quoted. Ex:
+// `"Hello", silly 'elephant' from the "zoo".`
+// returns [ `"Hello"`, `'elephant'`, `"zoo"` ]
+func extractQuotedStrings(s string) ([]string, error) {
+	var result []string
+
+	// Find all double-quoted sub-strings.
+	reg, err := regexp.Compile(`(".*?")`)
```
Comment (calvn) [inline plugins/database/postgresql/postgresql.go]: Can we pull this, and the regex below, out to be a global var to avoid calling `regex.Compile` every time this gets called (and possibly use `regex.MustCompile` so we error on build instead)?

Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql.go]: Sure, will do.

File: plugins/database/postgresql/postgresql.go (hunk 3 above)
Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql.go]: Ah! I wasn't aware of that, thanks! Will do.

File: plugins/database/postgresql/postgresql.go (hunk 4 above)
Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql.go]: Done in https://github.com/hashicorp/vault/pull/8512/commits/645789ba3e570f403a8a33424a70468a34ed4db8

File: plugins/database/postgresql/postgresql.go (hunk 3 above)
Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql.go]: Done in https://github.com/hashicorp/vault/pull/8512/commits/645789ba3e570f403a8a33424a70468a34ed4db8

File: plugins/database/postgresql/postgresql_test.go [hunk 5]
```diff
@@ -156,6 +156,12 @@ func TestPostgreSQL_CreateUser(t *testing.T) {
 				GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO "{{username}}";`,
 			},
 		},
+		"reproduce https://github.com/hashicorp/vault/issues/6098": {
+			createStmts: []string{
+				// NOTE: "rolname" in the following line is not a typo.
+				"DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='my_role') THEN CREATE ROLE my_role; END IF; END $$",
```
Comment (briankassouf) [inline plugins/database/postgresql/postgresql_test.go]: Could you template this entry so we can make sure everything around replacing usenames/passwords work ok?

Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql_test.go]: This is added in https://github.com/hashicorp/vault/pull/8512/commits/5a3dbbb87c2508fcd48f0aac426894d0331f128a

Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql_test.go]: Also, there are a bunch of existing tests in this file that cover templated fields.

File: plugins/database/postgresql/postgresql_test.go [hunk 6]
```diff
@@ -155,6 +159,22 @@ func TestPostgreSQL_CreateUser(t *testing.T) {
 				GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{username}}";
 				GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO "{{username}}";`,
 			},
+			shouldTestCredsExist: true,
+		},
+		"reproduce https://github.com/hashicorp/vault/issues/6098": {
```
Comment (calvn) [inline plugins/database/postgresql/postgresql_test.go]: Small nit, this might look odd in test results, maybe something like `"reproduce GH-6098"` along with a commented link?

File: plugins/database/postgresql/postgresql_test.go [hunk 7]
```diff
@@ -657,3 +682,81 @@ func createTestPGUser(t *testing.T, connURL string, username, password, query st
...
+		Expected bool
+	}
+
+	testCases := map[string]*testCase{
+		"issue 6098 repro": {
+			Input:    `DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='my_role') THEN CREATE ROLE my_role; END IF; END $$`,
+			Expected: true,
+		},
+		"multiline with template fields": {
+			Input:    `DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname=\"{{name}}\") THEN CREATE ROLE {{name}}; END IF; END $$`,
```
Comment (calvn) [inline plugins/database/postgresql/postgresql_test.go]: Should we still be escaping double-quotes even with backticks? Same down below for `"docs example"` and `"templated field"`.

Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql_test.go]: I was just trying to be cruel to the code in the tests to make sure it still worked as expected.

File: plugins/database/postgresql/postgresql_test.go (hunk 6 above)
Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql_test.go]: Updated in https://github.com/hashicorp/vault/pull/8512/commits/ad56d0fae9c77c5c00907c9f224907e84f1f865a

File: plugins/database/postgresql/postgresql_test.go (hunk 7 above)
Comment (tyrannosaurus-becks) [reply plugins/database/postgresql/postgresql_test.go]: Stripped them out in https://github.com/hashicorp/vault/pull/8512/commits/405465fed2cb85612d78bc7033d99c581f4e117b

**Comment by Legogris** [comment]
Looking in the [changelog](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md), it seems this has not been released yet? Was it simply omitted from the changelog or is it yet to be released?

(Encountering the same issue in 1.5.0)

**Comment by ncabatoff** [comment]
> Looking in the [changelog](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md), it seems this has not been released yet? Was it simply omitted from the changelog or is it yet to be released?
> 
> (Encountering the same issue in 1.5.0)

Sorry, we missed adding it to the 1.5.0 changelog (I just added it there now.).  Please open a new issue if you're still having problems of this sort with 1.5.0.
