### PR TITLE
Fix Agent handling of gzipped responses

### LINKED ISSUE #6606: Reading secrets thru Vault Agent with gzip encoding between Vault agent and Vault server
**Describe the bug**
Configured the vault agent and when try accessing data thru it, the error is
```
2019-04-18T08:24:27.677Z [INFO]  cache: received request: path=<redacted> method=GET
2019-04-18T08:24:27.677Z [DEBUG] cache.leasecache: forwarding request: path=<redacted> method=GET
2019-04-18T08:24:27.766Z [INFO]  cache.apiproxy: forwarding request: path=<redacted> method=GET
2019-04-18T08:24:27.771Z [ERROR] cache.leasecache: failed to parse response as secret: error="invalid character '\x1f' looking for beginning of value"
```
Executing the query with Curl works, so it's clearly not a problem of permissions

**To Reproduce**
1. Run `vault kv put secret/test foo=bar` directly to vault without passing thru the agent
2. Run `vault read secret/data/test` with `export VAULT_AGENT_ADDR=http://127.0.0.1:8100`
3. See error

**Expected behavior**
See the content of the secret

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    5
Threshold                3
Version                  1.1.1
Cluster Name             acceptance
Cluster ID               ------
HA Enabled               true
HA Cluster               https://10.244.78.109:8201
HA Mode                  active
```
* Vault CLI Version (retrieve with `vault version`):
`Vault v1.1.1 ('a3dcd63451cf6da1d04928b601bbe9748d53842e')`
* Server Operating System/Architecture:
Kubernetes 1.12.4, CoreOS, Docker 18.06.

**Additional context**
This is due to gzip encoding done by the ingress-nginx in front of Vault Server. If I send the vault agent directly to Vault server this issue is not present

This likely applies to all installation with LB with HTTPS termination in front of Vault

Found the problem with tcpdump. Vault Agent is trying to parse a secret (`command/agent/lease_cache.go` L239) as it was in plain test but the body is coming with gzip encoding. In the Vault cli this case is handled, but it's not in the proxier resp.Body. I'd like to fix this, I just need some pointer

### PR DESCRIPTION
**Pull request by kalafut**
Fixes #6606

### CODE REVIEW

File: command/agent/cache/api_proxy.go [hunk 1]
```diff
@@ -36,7 +37,16 @@ func (ap *APIProxy) Send(ctx context.Context, req *SendRequest) (*SendResponse,
...
 	}
 	client.SetToken(req.Token)
-	client.SetHeaders(req.Request.Header)
+
+	// http.Transport will transparently request gzip and decompress the response, but only if
+	// the client doesn't manually set the header (in which case the client has to handle
+	// the decompression. If gzip has already been set, remove it to avoid triggering the manual
+	// handling requirement.
+	h := clone(req.Request.Header)
+	if h.Get("Accept-Encoding") == "gzip" {
```
Comment (calvn) [inline command/agent/cache/api_proxy.go]: `h.Get` would only access the first value if multiple are provided so it would fail to check against something like `Accept-Encoding: compress, gzip`. We might what to access the map directly and ok check it instead.

Comment (kalafut) [reply command/agent/cache/api_proxy.go]: Yeah. Plus we'd only want to remove `gzip`, not other encodings. I'll update it.

File: command/agent/cache/api_proxy.go [hunk 2]
```diff
@@ -36,7 +38,16 @@ func (ap *APIProxy) Send(ctx context.Context, req *SendRequest) (*SendResponse,
 		return nil, err
 	}
 	client.SetToken(req.Token)
-	client.SetHeaders(req.Request.Header)
+
+	// http.Transport will transparently request gzip and decompress the response, but only if
+	// the client doesn't manually set the header (in which case the client has to handle
+	// the decompression. If gzip has already been set, remove it to avoid triggering the manual
+	// handling requirement.
+	h := clone(req.Request.Header)
```
Comment (jefferai) [inline command/agent/cache/api_proxy.go]: Why clone?

Why not use the Header built-in functions to handle removal?

Comment (kalafut) [reply command/agent/cache/api_proxy.go]: `clone` b/c I didn't think this Send function should mutate the caller's request object. If that's not an issue, then we can get rid of it.

Is there a built-in to remove just a single value? https://golang.org/pkg/net/http/#Header.Del will delete all values.

Comment (jefferai) [reply command/agent/cache/api_proxy.go]: Unless the request object is being used for some other purpose down the wire I think it's fine to mutate it. I would think once it gets to this point it won't be further modified and we don't log request headers (or if we do it's before this, I would expect).

I would assume you'd have the same problem with `deflate` or any other encoding so I imagine you should remove them all. You could first cache them if you wanted to then use it to decide how to respond to the client, which is not a bad option, since the client is telling the cache what it will accept. But in that case you'd probably want to cache them all, not remove gzip and then cache the rest.

Comment (kalafut) [reply command/agent/cache/api_proxy.go]: `gzip` is a special case because the Go std library transparently adds it depending on headers being set. Nonetheless, I think it's probably fine to just unconditionally remove the `Accept-Encoding` header on the request object. We're not giving up gzip to Vault since the agent's Transport will add it in anyway. I think caching can be deferred until we need to actually reprocess the response (which seems unlikely, since we don't and probably shouldn't compress Vault data responses).

**Comment by gitirabassi** [comment]
Thanks @kalafut and @briankassouf
