### PR TITLE
UI cluster unseal bug

### LINKED ISSUE #20644: Can't init 1.13.2 with awskms
When running vault init with the web UI on a new install of 1.13.2 errors with "* parameters secret_shares,secret_threshold not applicable to seal type awskms". 

Environment:

Vault Server Version (retrieve with vault status): 1.13.2

Vault server configuration file(s):

ui = true
disable_mlock = true

cluster_addr = "https://...:8201"
api_addr = "https://...:8200"
listener "tcp" {
  address            = "0.0.0.0:8200"
  tls_disable        = false
  tls_cert_file      = "/opt/vault/tls/certificates/....crt"
  tls_key_file       = "/opt/vault/tls/certificates/....key"
  tls_disable_client_certs = true
}

plugin_directory = "/opt/vault/plugins"

seal "awskms" {
  region     = "us-east-1"
  kms_key_id = "arn:aws:kms:us-east-1..."
}

### PR DESCRIPTION
**Pull request by zofskeez**
It was discovered that the `secret_shares` and `secret_threshold` properties are no longer allowed to be passed when unsealing a cloud seal type cluster. These properties were being passed in the UI causing the unseal to fail. Removing these properties from the payload for seal types other than `shamir` allows the cluster to be unsealed as expected. 

Error before fix:
image

After fix:

https://github.com/hashicorp/vault/assets/24611656/e7270e83-8d94-41b5-ad59-750973c76b84

Resolves #20644

### CODE REVIEW

**Review by hellobontempo — APPROVED** [review]
Nice job tracking this down! 🕵️ And lovely test coverage ⭐

File: ui/app/controllers/vault/cluster/init.js [hunk 1]
```diff
@@ -48,13 +48,15 @@ export default Controller.extend(DEFAULTS, {
         if (isCloudSeal) {
           data.stored_shares = 1;
           data.recovery_shares = shares;
+          delete data.secret_shares; // API will throw an error if secret_shares is passed for seal types other than shamir (transit, AWSKMS etc.)
```
Comment (Monkeychip) [inline ui/app/controllers/vault/cluster/init.js:51]: are we getting data from openAPI, if so why is this data on there if the API no longer accepts it?

Comment (zofskeez) [reply ui/app/controllers/vault/cluster/init.js:51]: No these properties all map to the form inputs but only some are used based on the seal type.
