### PR TITLE
Fixed ignored empty value set on token role update call

### LINKED ISSUE #6296: Updating Token Roles Fields have surprising behaviour
When [updating](https://www.vaultproject.io/api/auth/token/index.html#create-update-token-role) a token role, I notice a couple of behaviour that is surprising to me. I noticed this while trying to update the relevant resource in the [Vault Terraform provider](https://github.com/terraform-providers/terraform-provider-vault/pull/317). 

Consider an existing Token Role with the following JSON returned from Vault:

```json
{
    "request_id": "d2640082-8cab-aaf3-0e65-78941e6f03b9",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "allowed_policies": [
            "dev",
            "test"
        ],
        "bound_cidrs": [
            "0.0.0.0/0"
        ],
        "disallowed_policies": [
            "default"
        ],
        "explicit_max_ttl": 115200,
        "name": "test-role-updated-7797248494769930569",
        "orphan": true,
        "path_suffix": "parth-suffix",
        "period": 86400,
        "renewable": false,
        "token_type": "default-batch"
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}
```

When I submit the following Request:

```
---[ REQUEST ]---------------------------------------
PUT /v1/auth/token/roles/test-role-updated-7797248494769930569 HTTP/1.1
Host: 127.0.0.1:8200
User-Agent: Go-http-client/1.1
Content-Length: 181
X-Vault-Token: s.TOKEN-REDACTED
Accept-Encoding: gzip
```

```json
{
    "allowed_policies": [],
    "bound_cidrs": [],
    "disallowed_policies": [],
    "explicit_max_ttl": "0",
    "orphan": false,
    "path_suffix": "",
    "period": "0",
    "renewable": true,
    "token_type": "default-service"
}
```

Vault returns the following response when we read the token role:

```json
{
    "request_id": "e01abe9b-a4d4-2075-a6fd-ac0c55bd5403",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "allowed_policies": [],
        "bound_cidrs": [
            "0.0.0.0/0"
        ],
        "disallowed_policies": [],
        "explicit_max_ttl": 0,
        "name": "test-role-updated-7797248494769930569",
        "orphan": false,
        "path_suffix": "parth-suffix",
        "period": 0,
        "renewable": true,
        "token_type": "default-service"
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}
```

Of note:

- `path_suffix` and  `bound_cidrs` are not "unset" to an empty string and empty list respectively.
- If I missed out any of the fields (say `allowed_policies`) during the update, the corresponding field is not reset to the default value in Vault (in this case `[]`). I'm not sure if this is an expected behaviour or if this is a bug.

**Expected behavior**
- `path_suffix` and  `bound_cidrs` to be set correctly when updating
- Missing fields during update should be reset to default values 

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault v1.0.3 ('85909e3373aa743c34a6a0ab59131f61fd9e8e43')

* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: Linux AMD64

**Additional Information**

- Terraform provider test code: https://github.com/lawliet89/terraform-provider-vault/blob/token-role-set/vault/resource_token_auth_backend_role_test.go
- [Test log](https://github.com/hashicorp/vault/files/2908283/test.log) with requests/response from Vault

### PR DESCRIPTION
**Pull request by michelvocks**
Fixes #6296

### CODE REVIEW

File: vault/token_store.go [hunk 1]
```diff
@@ -3061,15 +3063,13 @@ func (ts *TokenStore) tokenStoreRoleCreateUpdate(ctx context.Context, req *logic
...
 		pathSuffix := pathSuffixInt.(string)
-		if pathSuffix != "" {
-			matched := pathSuffixSanitize.MatchString(pathSuffix)
-			if !matched {
-				return logical.ErrorResponse(fmt.Sprintf(
-					"given role path suffix contains invalid characters; must match %s",
-					pathSuffixSanitize.String())), nil
-			}
-			entry.PathSuffix = pathSuffix
+		matched := pathSuffixSanitize.MatchString(pathSuffix)
```
Comment (jefferai) [inline vault/token_store.go]: I think the logic would be a little cleaner to follow here if you used a switch so that the base case of `""` is handled up front, but it's not a big deal.

**Comment by jefferai** [comment]
Looks good -- there is/are a/some token store role tests that test out role CRUD operations, it would be good to update those tests to ensure correct behavior (so that we'll also detect regressions).

File: vault/token_store.go (hunk 1 above)
Comment (michelvocks) [reply vault/token_store.go]: Thanks. You are right, it's not really clean.

**Comment by jefferai** [comment]
LGTM!
