### PR TITLE
Fix removing secondary index from exp manager.

### LINKED ISSUE #749: ExpirationManager Revoke doesn't delete secondary index
https://github.com/hashicorp/vault/blob/master/vault/expiration.go#L198

I set a low TTL of 3 minutes for my auth/app-id backend, but noticed that the secondary indices created in sys/expire/token/ weren't being deleted even though leases were expiring as expected.

I think this should be `removeIndexByToken` rather than `indexByToken`

### PR DESCRIPTION
**Pull request by jefferai**
Due to a typo, revoking ensures that index entries are created rather
than removed. This adds a failing, then fixed test case (and helper
function) to ensure that index entries are properly removed on revoke.

Fixes #749

### CODE REVIEW

File: vault/expiration.go [hunk 1]
```diff
@@ -579,6 +579,16 @@ func (m *ExpirationManager) indexByToken(token, leaseID string) error {
 	return nil
 }
 
+// indexByToken looks up the secondary index from the token to a lease entry
+func (m *ExpirationManager) indexByToken(token, leaseID string) (*logical.StorageEntry, error) {
```
Comment (armon) [inline vault/expiration.go]: Are there any callers of this left?

**Comment by armon** [comment]
LGTM
