### PR TITLE
VAULT-13061: Fix mount path discrepancy in activity log

### LINKED ISSUE #18814: `sys/internal/counters/activity` APIs are inconsistent about rendering activity log info with invalid mount_accessor data
Activity log entries contain a mount_accessor field.

It can be missing, either because pre-1.10 Vault didn't write it at all, or because of bugs such as that mentioned in #18809. It could also be present but pointing at a deleted mount.

Some parts of the activity log code account for this:

https://github.com/hashicorp/vault/blob/3ded1388cbd838b5a1253af40808c823d6d4336d/vault/activity_log.go#L2341-L2361

Other parts just throw data away if they don't successfully resolve a mount:

https://github.com/hashicorp/vault/blob/3ded1388cbd838b5a1253af40808c823d6d4336d/vault/activity_log.go#L2169-L2173

Which is incredibly confusing for users, when different parts of the JSON returned by Vault tell different stories about actual activity!

### PR DESCRIPTION
**Pull request by miagilepner**
There are two problems this PR fixes:
1. `processClientRecord` creates maps that key by mount accessor, but we later assume that the key is a mount path in `transformActivityLogMounts` 
2. Sometimes a deleted/empty mount record is thrown out (`precomputedQueryWorker`), while other times we keep it (`transformMonthBreakdowns `). This change means that we will always keep the mount record.

Closes #18814, #18812

### CODE REVIEW

File: vault/activity_log.go [hunk 1]
```diff
@@ -2166,13 +2166,8 @@ func (a *ActivityLog) precomputedQueryWorker(ctx context.Context) error {
 		for nsID, entry := range byNamespace {
 			mountRecord := make([]*activity.MountRecord, 0, len(entry.Mounts))
 			for mountAccessor, mountData := range entry.Mounts {
-				valResp := a.core.router.ValidateMountByAccessor(mountAccessor)
-				if valResp == nil {
-					// Only persist valid mounts
-					continue
```
Comment (miagilepner) [inline vault/activity_log.go:2172]: I want to verify that this is the correct behavior - it seems wrong to me that these currently get thrown out, but I definitely might be missing something

Comment (miagilepner) [reply vault/activity_log.go:2172]: and to clarify, deleted mounts were being excluded from the per-mount breakdown of counts. They were still present in the top-level totals.

File: vault/activity_log_test.go [hunk 2]
```diff
@@ -3984,3 +3986,105 @@ func TestActivityLog_partialMonthClientCountUsingHandleQuery(t *testing.T) {
 		}
 	}
 }
+
```
Comment (mpalmi) [inline vault/activity_log_test.go:3989]: Might be useful to have a comment here (and throughout) explaining some of the logic and overall structure of the test.

File: vault/activity_log_test.go [hunk 3]
```diff
@@ -3984,3 +3986,105 @@ func TestActivityLog_partialMonthClientCountUsingHandleQuery(t *testing.T) {
...
+		},
+	}
+	for i, entityRecord := range entityRecords {
+		entityData, err := proto.Marshal(&activity.EntityActivityLog{
+			Clients: []*activity.EntityRecord{entityRecord},
+		})
+		if err != nil {
+			t.Fatalf(err.Error())
+		}
+		WriteToStorage(t, core, ActivityLogPrefix+"entity/"+fmt.Sprint(timeutil.StartOfMonth(now).Unix())+"/"+strconv.Itoa(i), entityData)
```
Comment (mpalmi) [inline vault/activity_log_test.go:4037]: Might be worth splitting the path off into its own var and using `Sprintf` to avoid the need for strconv and all that.

File: vault/activity_log_test.go [hunk 4]
```diff
@@ -3984,3 +3986,105 @@ func TestActivityLog_partialMonthClientCountUsingHandleQuery(t *testing.T) {
...
+
+	clientCountResponse := make([]*ResponseNamespace, 0)
+	err = mapstructure.Decode(byNamespace, &clientCountResponse)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if len(clientCountResponse) != 1 {
+		t.Fatal("incorrect client count responses")
+	}
+	if len(clientCountResponse[0].Mounts) != 3 {
```
Comment (mpalmi) [inline vault/activity_log_test.go:4069]: What do you think about comparing to `len(entityRecords)` instead, in case we change that later on?

File: vault/activity_log_test.go [hunk 5]
```diff
@@ -3984,3 +3986,105 @@ func TestActivityLog_partialMonthClientCountUsingHandleQuery(t *testing.T) {
...
+		t.Fatal("incorrect client mounts")
+	}
+	byPath := make(map[string]int, len(clientCountResponse[0].Mounts))
+	for _, mount := range clientCountResponse[0].Mounts {
+		byPath[mount.MountPath] = byPath[mount.MountPath] + mount.Counts.Clients
+	}
+	expectedPaths := []string{
```
Comment (mpalmi) [inline vault/activity_log_test.go:4076]: Oh this is pretty clever. Correct me if I have this wrong. Since I'm not seeing any deletes, I'm assuming we're simulating the deleted mounts by not actually servicing the requests? Our noop backend has no request handler and we just write directly to storage. Prior to your changes, we wouldn't report on these since they'd not show up in the router, but now we expect them to exist in the activity log since they're in storage and thus have an associated mount accessor?

Might be worth documenting something to this effect, or clarifying for others like me who have missed the point entirely 😂.

File: vault/activity_log_test.go [hunk 6]
```diff
@@ -3984,3 +3986,105 @@ func TestActivityLog_partialMonthClientCountUsingHandleQuery(t *testing.T) {
...
+		t.Fatalf("malformed results. got %v", results)
+	}
+
+	clientCountResponse := make([]*ResponseNamespace, 0)
+	err = mapstructure.Decode(byNamespace, &clientCountResponse)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if len(clientCountResponse) != 1 {
+		t.Fatal("incorrect client count responses")
```
Comment (mpalmi) [inline vault/activity_log_test.go:4067]: Might be good to show the number in this output for easy inspection.

**Review by mpalmi — COMMENTED** [review]
Code looks great! Just a few nits on the tests, mainly relating to clarity. Thanks for including the test with this.

Worth noting: I tested this against your feature branch with the `transformMonthBreakdowns` changes reset and the test you have passes. Does this align with your expectations, or should we iron out that piece of testing a bit more?

File: vault/activity_log_test.go (hunk 5 above)
Comment (miagilepner) [reply vault/activity_log_test.go:4093]: Take a look at the comments I've added in the test, it should hopefully clarify the scenario

**Review by mpalmi — APPROVED** [review]
