### PR TITLE
ldap, okta: fix renewal when login policies are empty

### LINKED ISSUE #8002: Cannot renew token generate by LDAP user login
**Describe the bug**
I have a Vault server that integrated with my LDAP server, it works fine with my LDAP server and every thing goes well with it, but the only thing is I cannot renew the tokens generated by these logins.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `vault login -method=ldap username=myusername -renewable=true` and get the token as following:
```
Password (will be hidden):                                                        
Success! You are now authenticated. The token information displayed below         
is already stored in the token helper. You do NOT need to run "vault login"       
again. Future Vault requests will automatically use this token.                   
                                                                                  
                                                                                  
Key                    Value                                                      
---                    -----                                                      
token                  s.wCQedkMmX61EJszE64HqPzhC                                 
token_accessor         qcxkggK00WxgwmxOC9Ht9vpc                                   
token_duration         24h                                                        
token_renewable        true                                                       
token_policies         ["default"]                                                
identity_policies      []                                                         
policies               ["default"]                                                
token_meta_username    myusername   
```
2. Login as `root` user and Run `vault token lookup s.wCQedkMmX61EJszE64HqPzhC` to check token status and ttl:
```
Key                 Value                                    
---                 -----                                    
accessor            qcxkggK00WxgwmxOC9Ht9vpc                 
creation_time       1576051650                               
creation_ttl        24h                                      
display_name        ldap-myusername                    
entity_id           1fc1f68d-face-f9f1-468f-36b94e10fb3b     
expire_time         2019-12-12T08:07:30.56805754Z            
explicit_max_ttl    0s                                       
id                  s.wCQedkMmX61EJszE64HqPzhC               
issue_time          2019-12-11T08:07:30.568070919Z           
meta                map[username:myusername]           
num_uses            0                                        
orphan              true                                     
path                auth/ldap/login/myusername         
policies            [default]                                
**renewable           true**                                     
ttl                 23h55m5s                                 
type                service      
```
As it is obvious the `renewable` property of the token is `true` and its `type` is `service`, so it can be renewed.
3. Run `vault token renew s.wCQedkMmX61EJszE64HqPzhC ` to renew the token given above.
4. When I look up the token again nothing happened to its `ttl`. Run `vault token lookup s.wCQedkMmX61EJszE64HqPzhC`:
```
Key                 Value                                   
---                 -----                                   
accessor            qcxkggK00WxgwmxOC9Ht9vpc                
creation_time       1576051650                              
creation_ttl        24h                                     
display_name        ldap-myusername                   
entity_id           1fc1f68d-face-f9f1-468f-36b94e10fb3b    
expire_time         2019-12-12T08:07:30.56805754Z           
explicit_max_ttl    0s                                      
id                  s.wCQedkMmX61EJszE64HqPzhC              
issue_time          2019-12-11T08:07:30.568070919Z          
meta                map[username:myusername]          
num_uses            0                                       
orphan              true                                    
path                auth/ldap/login/myusername        
policies            [default]                               
renewable           true                                    
ttl                 23h53m24s                               
type                service                       
```

**Note:** I tried the steps above using API calls and self-renew but the result was same as above.

**Expected behavior**
My expected behaviour was after running `vault token renew s.wCQedkMmX61EJszE64HqPzhC` for a LDAP token as `root` the `ttl` of the token gets back to `creation_ttl` vaule.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
root@ubuntu:~# vault status                         
Key             Value                               
---             -----                               
Seal Type       shamir                              
Initialized     true                                
Sealed          false                               
Total Shares    5                                   
Threshold       3                                   
Version         1.3.0                               
Cluster Name    vault-cluster-11d62d58              
Cluster ID      a9704841-7f1c-1986-a880-a2c252f23ed2
HA Enabled      true                                
HA Cluster      https://10.1.10.1:8201          
HA Mode         active                              

```
* Vault CLI Version (retrieve with `vault version`):
```
root@ubuntu:~# vault version
Vault v1.3.0                
```
* Server Operating System/Architecture:
My OS is Ubuntu 18.04 with this info:
```
root@ubuntu:~# uname -a                                                                               
Linux ubuntu 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
```

Vault server configuration file(s):
```hcl
listener "tcp" {                           
  address          = "0.0.0.0:8200"        
  cluster_address  = "10.1.10.1:8201"  
  tls_disable      = "true"                
}                                          
                                           
storage "consul" {                         
  address = "127.0.0.1:8500"               
  path    = "vault/"                       
}                                          
                                           
ui = true                                  
api_addr = "http://10.1.10.1:8200"     
cluster_addr = "https://10.1.10.1:8201"

```

### PR DESCRIPTION
**Pull request by calvn**
This PR updates the error check from a `b.Login` call during renewal to check for the actual error as opposed to checking for the policy length returned, found in the ldap and okta backends. This similar to what's currently being done in the radius backend. 

To elaborate a bit further on this, we want to cancel renewal when we fail to fetch policies and not rely on the policy length as a check to do so. There could be cases where length of the token policy returned by `Login` could be zero (i.e. user policies/group not specified yet), resulting the failure to renew the token since we're returning early. Even without `token_no_default_policy`, the default policy is not added until further upsteam in the callback and not known to the backend that this point.

Fixes #8002

<details><summary>Repro Steps</summary>
<p>

```
λ ~/hc/vault on master [origin/master]
› vault auth enable ldap
Success! Enabled ldap auth method at: ldap/

λ ~/hc/vault on master [origin/master]
› vault write auth/ldap/config \
    url="ldap://ldap.forumsys.com:389" \
    userdn="uid=tesla,dc=example,dc=com" \
    userattr="uid" \
    groupattr="cn" \
    groupdn="dc=example,dc=com" \
    binddn="uid=tesla,dc=example,dc=com" \
    bindpass='password' \
    starttls=false \
    token_ttl=24h
Success! Data written to: auth/ldap/config

λ ~/hc/vault on master [origin/master]
› vault login -method=ldap username=tesla -renewable=true
Password (will be hidden):
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                    Value
---                    -----
token                  s.SPGFpZPmNBJtD7VeQ6OnuPaD
token_accessor         gzKpQi7ufWrDpHnurtceieYC
token_duration         24h
token_renewable        true
token_policies         ["default"]
identity_policies      []
policies               ["default"]
token_meta_username    tesla

λ ~/hc/vault on master [origin/master]
› vault login root
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                  Value
---                  -----
token                root
token_accessor       Mm76PioEcDujPZXIC5eSUssB
token_duration       ∞
token_renewable      false
token_policies       ["root"]
identity_policies    []
policies             ["root"]

λ ~/hc/vault on master [origin/master]
› vault token lookup s.SPGFpZPmNBJtD7VeQ6OnuPaD
Key                 Value
---                 -----
accessor            gzKpQi7ufWrDpHnurtceieYC
creation_time       1577128393
creation_ttl        24h
display_name        ldap-tesla
entity_id           5d5ba89d-f8b2-1826-a8b6-0adb146257dc
expire_time         2019-12-24T11:13:13.403114-08:00
explicit_max_ttl    0s
id                  s.SPGFpZPmNBJtD7VeQ6OnuPaD
issue_time          2019-12-23T11:13:13.403122-08:00
meta                map[username:tesla]
num_uses            0
orphan              true
path                auth/ldap/login/tesla
policies            [default]
renewable           true
ttl                 23h59m46s
type                service

λ ~/hc/vault on master [origin/master]
› vault token renew s.SPGFpZPmNBJtD7VeQ6OnuPaD

λ ~/hc/vault on master [origin/master]
› vault token lookup s.SPGFpZPmNBJtD7VeQ6OnuPaD
Key                 Value
---                 -----
accessor            gzKpQi7ufWrDpHnurtceieYC
creation_time       1577128393
creation_ttl        24h
display_name        ldap-tesla
entity_id           5d5ba89d-f8b2-1826-a8b6-0adb146257dc
expire_time         2019-12-24T11:13:13.403114-08:00
explicit_max_ttl    0s
id                  s.SPGFpZPmNBJtD7VeQ6OnuPaD
issue_time          2019-12-23T11:13:13.403122-08:00
meta                map[username:tesla]
num_uses            0
orphan              true
path                auth/ldap/login/tesla
policies            [default]
renewable           true
ttl                 23h59m34s
type                service

```
</p>
</details>

### CODE REVIEW

File: vault/external_tests/policy/no_default_test.go [hunk 1]
```diff
@@ -86,4 +84,90 @@ func TestNoDefaultPolicy(t *testing.T) {
...
+	err = client.Sys().EnableAuthWithOptions("ldap", &api.EnableAuthOptions{
+		Type: "ldap",
+	})
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	// Configure LDAP auth backend
+	secret, err := client.Logical().Write("auth/ldap/config", map[string]interface{}{
+		"url":       "ldap://ldap.forumsys.com",
```
Comment (ncabatoff) [inline vault/external_tests/policy/no_default_test.go]: Please don't reintroduce the flaky external LDAP service.  Look at what the other LDAP tests are doing now with docker and follow that model.

File: vault/external_tests/policy/no_default_test.go [hunk 2]
```diff
@@ -86,4 +84,90 @@ func TestNoDefaultPolicy(t *testing.T) {
...
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	if diff := deep.Equal(secret.Data["policies"], []interface{}{"default"}); diff != nil {
+		t.Fatal(diff)
+	}
+
+	// Sleep a bit to let the lease elapse
+	time.Sleep(3 * time.Second)
```
Comment (ncabatoff) [inline vault/external_tests/policy/no_default_test.go]: I'm confused, don't you set token_ttl=24h above?

Comment (ncabatoff) [reply vault/external_tests/policy/no_default_test.go]: Oh nvm, I follow

File: vault/external_tests/policy/no_default_test.go [hunk 3]
```diff
@@ -86,4 +84,90 @@ func TestNoDefaultPolicy(t *testing.T) {
...
+	secret, err = client.Logical().Write("auth/token/renew", map[string]interface{}{
+		"token": token,
+	})
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	// Verify that the lease renewal extended the duration properly. We give it a one
+	// second leeway to prevent test failure in case the response is delayed.
+	if secret.Auth.LeaseDuration <= 86399 {
```
Comment (ncabatoff) [inline vault/external_tests/policy/no_default_test.go]: This seems brittle, since on circleci you can easily encounter longer than 1s pauses.  Can we provide a ttl increment instead to make a bigger delta without needing a big sleep?

File: vault/external_tests/policy/no_default_test.go (hunk 1 above)
Comment (calvn) [reply vault/external_tests/policy/no_default_test.go]: I was main going off with the existing test above, `TestPolicy_NoDefaultPolicy`, with adapted changes specific for this test case. I'll switch both to use the container to test.

Comment (ncabatoff) [reply vault/external_tests/policy/no_default_test.go]: Ah, because the test was commented out it didn't show up when I searched for "forumsys" while removing usages of the external ldap server.  I guess going by the TODO at the top of the file it can now be enabled?

Comment (calvn) [reply vault/external_tests/policy/no_default_test.go]: Yeah, uncommented and ran the existing test -- passes as well. Both tests now uses the docker image.

File: vault/external_tests/policy/no_default_test.go (hunk 3 above)
Comment (calvn) [reply vault/external_tests/policy/no_default_test.go]: Now uses increment to ensure a big enough delta.
