### PR TITLE
Switch reading from S3 to io.Copy from io.ReadFull

### LINKED ISSUE #4222: runtime error: invalid memory address or nil pointer dereference
**Environment:**

* Vault Version: 0.9.5
* Operating System/Architecture: OEL 7.1, 7.2 /  x86_64
 
**Vault Config File:**

storage "s3" {

	access_key = "xxxxxxxxxx"
	secret_key = "xxxxxxxxxxxxxxxxxxxx"
	bucket = "vault-poc"
	s3_force_path_style = "true"
	endpoint = "http://xxxxxx.xxxx.xxxxx"
	disable_ssl = "true"
	region = "xxxxxx"

}

listener "tcp" {
address = "127.0.0.1:8200"
tls_disable = 1
}

**Startup Log Output:**

Vault server configuration:

                 Cgo: disabled
          Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
           Log Level: debug
               Mlock: supported: false, enabled: false
             Storage: s3
             Version: Vault v0.9.5
         Version Sha: 36edb4d42380d89a897e7f633046423240b710d9
==> Vault server started! Log data will stream in below:

2018/03/29 15:53:05.789456 [INFO ] core: security barrier not initialized
2018/03/29 15:53:06.876811 [INFO ] core: security barrier initialized: shares=1 threshold=1
2018-03-29 15:53:07.126404 I | http: panic serving 127.0.0.1:53339: runtime error: invalid memory address or nil pointer dereference
goroutine 60 [running]:
net/http.(*conn).serve.func1(0xc420426640)
/goroot/src/net/http/server.go:1697 +0xd0
panic(0x2b83920, 0x4129f90)
/goroot/src/runtime/panic.go:491 +0x283
github.com/hashicorp/vault/physical/s3.(*S3Backend).Get(0xc420584c90, 0x40c0bc0, 0xc4200140b0, 0x2f59e20, 0xc, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/physical/s3/s3.go:192 +0x2cd
github.com/hashicorp/vault/vault.(*sealUnwrapper).Get(0xc420583500, 0x40c0bc0, 0xc4200140b0, 0x2f59e20, 0xc, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/sealunwrapper.go:66 +0x95
github.com/hashicorp/vault/physical.(*Cache).Get(0xc420185e00, 0x40c0bc0, 0xc4200140b0, 0x2f59e20, 0xc, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/physical/cache.go:110 +0x37f
github.com/hashicorp/vault/vault.(*AESGCMBarrier).Unseal(0xc4205716e0, 0x40c0bc0, 0xc4200140b0, 0xc42067f720, 0x20, 0x20, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:336 +0x14f
github.com/hashicorp/vault/vault.(*Core).Initialize(0xc420564d80, 0x40c0bc0, 0xc4200140b0, 0xc4204f5a38, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/init.go:153 +0xc1d
github.com/hashicorp/vault/http.handleSysInitPut(0xc420564d80, 0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/gopath/src/github.com/hashicorp/vault/http/sys_init.go:105 +0x346
github.com/hashicorp/vault/http.handleSysInit.func1(0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/gopath/src/github.com/hashicorp/vault/http/sys_init.go:20 +0x8f
net/http.HandlerFunc.ServeHTTP(0xc42062a3e0, 0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/goroot/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4205850b0, 0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/goroot/src/net/http/server.go:2254 +0x130
github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/gopath/src/github.com/hashicorp/vault/http/help.go:22 +0x166
net/http.HandlerFunc.ServeHTTP(0xc4205792a0, 0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/goroot/src/net/http/server.go:1918 +0x44
github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/gopath/src/github.com/hashicorp/vault/http/cors.go:32 +0x10a
net/http.HandlerFunc.ServeHTTP(0xc4205792c0, 0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/goroot/src/net/http/server.go:1918 +0x44
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/gopath/src/github.com/hashicorp/vault/http/handler.go:109 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc4205792e0, 0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/goroot/src/net/http/server.go:1918 +0x44
github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/handlers.go:40 +0xcf
net/http.HandlerFunc.ServeHTTP(0xc420579300, 0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/goroot/src/net/http/server.go:1918 +0x44
net/http.serverHandler.ServeHTTP(0xc42057d380, 0x40bf3c0, 0xc42019e0e0, 0xc420176200)
/goroot/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420426640, 0x40c0b80, 0xc4205c7880)
/goroot/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
/goroot/src/net/http/server.go:2720 +0x288

**Expected Behavior:**

The Vault should have generate the Keys normally as it should be.

**Actual Behavior:**

The Vault Application crashed while executing the command "vault operator init"

**Steps to Reproduce:**

Use the above mentioned config.hcl file with the vault 0.9.5 version.

**Important Factoids:**

**References:**

### PR DESCRIPTION
**Pull request by jefferai**
If the Content-Length header wasn't being sent back, the current
behavior could panic. It's unclear when it will not be sent; it appears
to be CORS dependent. But this works around it by not trying to
preallocate a buffer of a specific size and instead just read until EOF.

In addition I noticed that Close wasn't being called.
https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#GetObjectOutput
specifies that Body is an io.ReadCloser so I added a call to Close.

Fixes #4222

### CODE REVIEW

File: physical/s3/s3.go [hunk 1]
```diff
@@ -188,16 +188,17 @@ func (s *S3Backend) Get(ctx context.Context, key string) (*physical.Entry, error
 	if resp == nil {
 		return nil, fmt.Errorf("got nil response from S3 but no error")
 	}
+	defer resp.Body.Close()
 
-	data := make([]byte, *resp.ContentLength)
-	_, err = io.ReadFull(resp.Body, data)
+	data := bytes.NewBuffer(nil)
+	_, err = io.Copy(data, bytes.NewBuffer(resp.Body))
```
Comment (kalafut) [inline physical/s3/s3.go]: I believe this should just be resp.Body w/o the bytes.NewBuffer()

File: physical/s3/s3.go [hunk 2]
```diff
@@ -188,16 +188,17 @@ func (s *S3Backend) Get(ctx context.Context, key string) (*physical.Entry, error
 	if resp == nil {
 		return nil, fmt.Errorf("got nil response from S3 but no error")
 	}
+	defer resp.Body.Close()
 
-	data := make([]byte, *resp.ContentLength)
-	_, err = io.ReadFull(resp.Body, data)
+	data := bytes.NewBuffer(nil)
```
Comment (kalafut) [inline physical/s3/s3.go]: To retain the more efficient pre-allocation when ContentLength is known (presumably the normal case), consider:
```
	var cap int64
	if resp.ContentLength != nil {
		cap = *resp.ContentLength
	}

	data := bytes.NewBuffer(make([]byte, 0, cap))
```

File: physical/s3/s3.go (hunk 1 above)
Comment (jefferai) [reply physical/s3/s3.go]: Oh yeah good point, I did that before looking up whether it was a byte slice or reader and forgot to go back and change it.

File: physical/s3/s3.go (hunk 2 above)
Comment (jefferai) [reply physical/s3/s3.go]: I looked at that as a "efficiency doesn't really matter because network aspects will dominate the total time" but I guess if it's a 20mb object it actually could, so I'll do that.

**Comment by jefferai** [comment]
@kalafut Fixed, can you ✔️ ?

File: physical/s3/s3.go [hunk 3]
```diff
@@ -188,16 +188,20 @@ func (s *S3Backend) Get(ctx context.Context, key string) (*physical.Entry, error
 	if resp == nil {
 		return nil, fmt.Errorf("got nil response from S3 but no error")
 	}
+	defer resp.Body.Close()
```
Comment (tyrannosaurus-becks) [inline physical/s3/s3.go]: Might it be more defensive to do this right before line 178? Something like, `if resp != nil { defer resp.Body.Close() }`? Then there'd be absolutely no way there could be a memory leak if we hit 404's a lot, and if for some reason the AWS client still returned a body. I know for the `http.Client` that doesn't happen, but I don't know if the AWS client maintains the same contract. I can't find anything saying either way in their docs.

Comment (jefferai) [reply physical/s3/s3.go]: That's fair, considering we're thinking of returning data with 404s. I'll update.
