### PR TITLE
plugins/gRPC: fix issues with reserved keywords in response data

### LINKED ISSUE #3873: List operations does not work in external plugins
**Environment:**

* Vault Version: Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')
* Operating System/Architecture: Linux

**Vault Config File:**
```
plugin_directory = "/path/to/my/plugin/directory"
```

**Startup Log Output:**
```
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: trace
                   Mlock: supported: true, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.9.3
             Version Sha: 5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d
```

**Expected Behavior:**
It is possible to do a LIST request on a path that support it.

**Actual Behavior:**
Any LIST request fail with an internal server error and you got these logs from Vault:
```
2018/01/30 23:43:53.168510 [TRACE] plugin.HandleRequest: path=kv/ status=started type=mock-plugin transport=gRPC
2018/01/30 23:43:53.169698 [TRACE] plugin.HandleRequest: path=kv/ status=finished type=mock-plugin transport=gRPC err=<nil> took=1.185434ms
2018/01/30 23:44:01.599923 [TRACE] rollback: attempting rollback: path=auth/token/
2018/01/30 23:44:01.599933 [TRACE] rollback: attempting rollback: path=identity/
2018/01/30 23:44:01.599938 [TRACE] rollback: attempting rollback: path=secret/
2018/01/30 23:44:01.599940 [TRACE] rollback: attempting rollback: path=sys/
2018/01/30 23:44:01.599958 [TRACE] rollback: attempting rollback: path=cubbyhole/
2018/01/30 23:44:01.599945 [TRACE] rollback: attempting rollback: path=mock/
2018/01/30 23:44:01.600441 [TRACE] plugin.HandleRequest: path= status=started type=mock-plugin transport=gRPC
2018/01/30 23:44:01.601123 [TRACE] plugin.HandleRequest: path= status=finished type=mock-plugin transport=gRPC err=unsupported operation took=680.425µs
```

The issue seems to have been introduced with Vault 0.9.2/0.9.3.

**Steps to Reproduce:**
The issue can be reproduced with the mock-plugin.

 1. Build the mock-plugin
 2. Add the mock-plugin to the plugin catalog
 3. Mount the mock-plugin
 4. Add a value into the kv store
 5. Do a LIST request on mock/kv

### PR DESCRIPTION
**Pull request by briankassouf**
fixes #3873

### CODE REVIEW

File: http/logical.go [hunk 1]
```diff
@@ -200,8 +201,14 @@ func respondRaw(w http.ResponseWriter, r *http.Request, resp *logical.Response)
 		retErr(w, "no status code given")
 		return
 	}
-	status, ok := statusRaw.(int)
-	if !ok {
+
```
Comment (jefferai) [inline http/logical.go]: For safety, you should add a `json.Number` check in here too, in case something has already serialized the data for some reason. It would be handled transparently by the JSON encoder for the response but would trip this here.

**Comment by jefferai** [comment]
One comment, other than that LGTM!

**Comment by cypherhat** [comment]
LGTM means Lists Good to Me? Because, list works for my plugin now! Thanks!
