### PR TITLE
Pass headers back when request forwarding

### LINKED ISSUE #1791: Request forwarding mode: Wrong content-type header passed back
With the new request forwarding mode enabled, the standby nodes do not properly pass the Content-type header through.  I put two unsealed nodes in my load balancer with the feature enabled.  Two identical requests, and one returns `Content-Type: application/json`, and the other returns `Content-Type: text/plain; charset=utf-8`.  In both cases, the response body itself is JSON.  The problem goes away when I take the standby node out of the load balancer, so it appears that it's the standby node sending the wrong response header.

This is a critical problem, as some JSON parsing libraries (notably the spray-json one many of my scala apps use) will reject deserializing a response if it comes back with the wrong type.  I can work around it for now by taking the standby nodes back out of the load balancer and turning off clustering.  I would like to take advantage of the new clustering though, so if it's possible to consider a quick 0.6.2 bug fix release for this, that would be very nice.

### PR DESCRIPTION
**Pull request by jefferai**
Fixes #1791

### CODE REVIEW

File: http/handler.go [hunk 1]
```diff
@@ -136,7 +136,7 @@ func handleRequestForwarding(core *vault.Core, handler http.Handler) http.Handle
 		// Attempt forwarding the request. If we cannot forward -- perhaps it's
 		// been disabled on the active node -- this will return with an
 		// ErrCannotForward and we simply fall back
-		statusCode, retBytes, err := core.ForwardRequest(r)
+		statusCode, header, retBytes, err := core.ForwardRequest(r)
```
Comment (vishalnayak) [inline http/handler.go]: I would name this `headers` for the sake of readability.

Comment (jefferai) [inline http/handler.go]: It's named `header` because of the type: https://golang.org/pkg/net/http/#Header

**Comment by vishalnayak** [comment]
LGTM!
