### PR TITLE
Detect and bypass cycles during token revocation

### LINKED ISSUE #4803: Vault Crashes OOM
**Describe the bug**
When a Vault node in cluster of 6 with consul back-end becomes leader, the CPU Load and Memory increases to the point is crashes because of OOM.

**To Reproduce**
Vault node becomes leader and is crashing with:
```fatal error: runtime: out of memory```

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    5
Threshold       3
Version         0.10.1
Cluster Name    vault-cluster-
Cluster ID      
HA Enabled      true
HA Cluster      https://
HA Mode         active

* Server Operating System/Architecture:

Docker version 18.03.1-ce, build 9ee9f40
4.14.48-coreos-r2

Vault server configuration file(s):
```hcl
{"storage": {"consul": {"address": ":8500", "path": "vault", "token": "${consul_token}" }}, "listener": { "tcp": { "address": "0.0.0.0:443", "tls_cert_file": "/vault/certs/tls.crt", "tls_key_file": "/vault/certs/tls.key" }}, "disable_cache": "true", "disable_mlock": "true", "ui": "true"}
```

**Additional context**
Consul back-end : Consul 1.1.0
Crash log:  [vault_crash.log](https://github.com/hashicorp/vault/files/2119290/vault_crash.log)
Prometheus Monitoring Graph: 
vault

### PR DESCRIPTION
**Pull request by kalafut**
Fixes #4803

### CODE REVIEW

**Comment by kalafut** [comment]
This is nearly the same as when it was first committed, but with two changes:

1. Updated to use namespace versions of functions
2. Flipped the `dfs` usage so all of the additions and deletions are done at the end of the slice. This substantially reduces the number of allocations compared to the prepend approach.

File: vault/token_store.go [hunk 1]
```diff
@@ -1464,11 +1481,13 @@ func (ts *TokenStore) revokeTreeInternal(ctx context.Context, id string) error {
 			if l == 1 {
 				return nil
 			}
-			dfs = dfs[1:]
+			dfs = dfs[:len(dfs)-1]
 		} else {
-			// If we make it here, there are children and they must
-			// be prepended.
-			dfs = append(children, dfs...)
+			// If we make it here, there are children and they must be appended.
```
Comment (jefferai) [inline vault/token_store.go]: This appears to change from dfs to bfs, which was specifically what we got away from due to problems customers had with very large token trees. Is there a reason for this change?

Comment (kalafut) [reply vault/token_store.go]: It's not a functional change and is still dfs. The previous version had all operations working at the front of the slice. i.e. pulling from the head (0th element) and prepending the children to the slice. This pattern causes a new allocation and full copy of the dfs slice on every append. I've simply flipped the access pattern to use the end of the slice instead. So the next element is pulled off the end (see 1434), and deletions and child appends are made to the end. This way the underlying dfs array is only reallocated when it grows to a new max capacity.

Before the change I did a micro benchmark of prepending vs. appending and it was a big (260x) difference in speed. Admittedly the macro operation here is likely gated by I/O, but I felt that the reduced GC churn made it worth it.

File: vault/token_store.go [hunk 2]
```diff
@@ -1444,11 +1446,26 @@ func (ts *TokenStore) revokeTreeInternal(ctx context.Context, id string) error {
...
 		}
 
+		// Filter the child list to remove any items that have ever been in the dfs stack.
+		// This is a robustness check, as a parent/child cycle can lead to an OOM crash.
+		children := make([]string, 0, len(childrenRaw))
+		for _, child := range childrenRaw {
+			if _, seen := seenIDs[child]; !seen {
+				children = append(children, child)
+			} else {
+				if err = ts.parentView(saltedNS).Delete(saltedCtx, path+child); err != nil {
```
Comment (calvn) [inline vault/token_store.go]: `ts.revokeInternal` down below should be making this exact `Delete` call on the child token, so I wonder if the cycle is is due to the token not being properly cleaned up in there. IMO `revokeTreeInternal` should be only in charge of tree traversal and delegate deletion to `revokeInternal` to ensure that all related entries are properly removed.

Comment (kalafut) [reply vault/token_store.go]: `ts.revokeInternal` does make this delete for the parent reference in the token, but if we're here, there are extraneous parent references that will never get deleted. e.g. assume the state is:
```
parent/a/c
parent/b/c
```

If `c`'s correct parent is `a`, that info is stored in `c` and will cause `parent/a/c` to be deleted in `revokeInternal`. But nothing would trigger deletion of `parent/b/c`.

A prior version of the PR didn't have the delete step. It worked fine and was resilient to cycles, but @briankassouf noted that it would leave stray parent references.

Comment (calvn) [reply vault/token_store.go]: I don't think it can ever get to that state though right? `c` can only ever have one parent, unless entry creation was borked at some point.

Comment (kalafut) [reply vault/token_store.go]: Root cause for how a cycle could be created is still unknown, but we did see it in user data (see: https://hashicorp.slack.com/archives/C04L34UGZ/p1536860851000100) and if present, the revocation will just consume memory until Vault crashes.

File: vault/token_store.go (hunk 1 above)
Comment (jefferai) [reply vault/token_store.go]: Yep, I see what you did now, looks fine.
