### PR TITLE
Fix entity group associations

### LINKED ISSUE #10084: Identity groups not properly cleaned/merged with identity/entity/merge request
**Describe the bug**
Assume there are two entities, `toEntity` and `fromEntity`. `fromEntity` is a member of `groupA`. If `fromEntity` is merged into `toEntity` a success message is returned. However, there are several problems:

1. `groupA` does not have the `fromEntity` ID removed from `member_entity_ids`. Trying to update `groupA`'s name only results in an error.
1. `toEntity` does not have its `direct_group_ids` updated to include the `groupA` ID of `fromEntity`.

**To Reproduce**
1. Run `vault server -dev`
1. Create `fromEntity` - `fromEntity=$(vault write -field=id identity/entity name=child)`
1. Create `toEntity` - `toEntity=$(vault write -field=id identity/entity name=parent)`
1. Create `groupA` - `groupA=$(vault write -field=id identity/group name=groupA member_entity_ids=$fromEntity)`
1. Merge `fromEntity` into `toEntity` - `vault write identity/entity/merge to_entity_id=$toEntity from_entity_ids=$fromEntity`
1. Update `groupA` name to `updatedGroupA` - `vault write identity/group/id/$groupA name=updatedGroupA`. Observe this results in the following error:
    ```
    Error writing data to identity/group/id/08dabd46-bfa9-8bc1-ce15-1a154e9fa50a: Error making API request.

    URL: PUT http://127.0.0.1:8200/v1/identity/group/id/08dabd46-bfa9-8bc1-ce15-1a154e9fa50a
    Code: 500. Errors:

    * 1 error occurred:
            * invalid entity ID "ff767f9f-aa78-a4c0-98f8-f1bf1548ab66"
    ```
1. Fetch `groupA` member entity ID - `groupA_member_id=$(vault read -field=member_entity_ids -format=json identity/group/id/$groupA | jq -r '.[0]')`
1. Read the member entity ID and observe it does not exist - `vault read identity/entity/id/$groupA_member_id`
1. Read the group IDs linked to `toEntity` and observe that the group IDs are valid - `vault read -field=group_ids identity/entity/id/$toEntity`

**Expected behavior**
The `groupA` `member_entity_ids` should not contain an effectively deleted entity ID and merged entities should have their groups merged into the parent entity.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.4
* Vault CLI Version (retrieve with `vault version`): 1.5.4

**Additional context**
Whether or not groups _should_ get merged into the `toEntity` I'm less sure about because when `identity/entity/merge` is called policies are [not merged](https://github.com/hashicorp/vault/blob/ecf46c578967b9d0ebefa262e8e1417afe1b1bba/vault/identity_store_entities.go#L175). However, it does look like policies maybe [get merged](https://github.com/hashicorp/vault/blob/ecf46c578967b9d0ebefa262e8e1417afe1b1bba/vault/identity_store_util.go#L406) when an implicit entity is created on login.

- [Link to the `mergeEntity` func](https://github.com/mdgreenfield/vault/blob/master/vault/identity_store_entities.go#L608)
- [Related PR](https://github.com/hashicorp/vault/pull/5786)

### PR DESCRIPTION
**Pull request by mdgreenfield**
- When two entities are merged, remove the from entity ID in any
  associated groups.
- When two entities are merged, also merge their associated group
  memberships.

Fixes #10084

### CODE REVIEW

File: vault/identity_store_entities.go [hunk 1]
```diff
@@ -579,7 +579,7 @@ func (i *IdentityStore) handleEntityDeleteCommon(ctx context.Context, txn *memdb
 	// internal and external
 	groups, err := i.MemDBGroupsByMemberEntityIDInTxn(txn, entity.ID, true, false)
 	if err != nil {
-		return nil
+		return err
```
Comment (mdgreenfield) [inline vault/identity_store_entities.go:582]: I'm not sure why this previously returned `nil`

File: vault/identity_store_entities.go [hunk 2]
```diff
@@ -809,6 +810,22 @@ func (i *IdentityStore) mergeEntity(ctx context.Context, txn *memdb.Txn, toEntit
...
+			err = i.UpsertGroupInTxn(ctx, txn, group, persist && !isPerfSecondaryOrStandby)
+			if err != nil {
+				return nil, err
+			}
+
+			fromEntityGroups = append(fromEntityGroups, group)
+		}
+
 		// Delete the entity which we are merging from in MemDB using the same transaction
 		err = i.MemDBDeleteEntityByIDInTxn(txn, fromEntity.ID)
```
Comment (mdgreenfield) [inline vault/identity_store_entities.go:830]: Unfortunately we cannot reuse `IdentityStore#handleEntityDeleteCommon` because that also removes entity aliases on the `fromEntity`. Alternatively, I believe I could do something like this instead:

```go
fromEntity.Aliases = []*Alias{}
err = i.handleEntityDeleteCommon(ctx, txn, fromEntity, persist && !isPerfSecondaryOrStandby)
if err != nil {
	return nil, err
}
```

File: vault/identity_store_entities.go [hunk 3]
```diff
@@ -830,6 +847,14 @@ func (i *IdentityStore) mergeEntity(ctx context.Context, txn *memdb.Txn, toEntit
 		return nil, err
 	}
 
+	for _, group := range fromEntityGroups {
+		group.MemberEntityIDs = append(group.MemberEntityIDs, toEntity.ID)
+		err = i.UpsertGroupInTxn(ctx, txn, group, persist && !isPerfSecondaryOrStandby)
```
Comment (mdgreenfield) [inline vault/identity_store_entities.go:852]: is the usage of `persist && !isPerfSecondaryOrStandby` correct here?

**Comment by GitGarza13** [comment]
Don't want to be subscribe d

**Comment by mdgreenfield** [comment]
Are there any edge cases that need to be handled for "external" groups?

File: vault/identity_store_entities.go (hunk 1 above)
Comment (vishalnayak) [reply vault/identity_store_entities.go:582]: It looks like a typo mistake. Thanks for catching it!

File: vault/identity_store_entities.go (hunk 3 above)
Comment (vishalnayak) [reply vault/identity_store_entities.go:852]: Yep!

**Review by vishalnayak — COMMENTED** [review]
Hey @mdgreenfield. Thanks for catching the bug and for working on a fix. Apologies for getting back late on this. Would you be willing to take this forward?

Assuming you are, would you mind adding this behavior as part of the API docs as well?

**Comment by mdgreenfield** [comment]
Hi @vishalnayak, Not a problem. I can look at getting this PR in order next week.

**Comment by mdgreenfield** [comment]
PR has been rebased. API docs have been updated. Changelog file has been added.

@vishalnayak, very much related to this PR is https://github.com/hashicorp/vault/pull/10101. Does it make sense to get that one in too?

**Review by vishalnayak — APPROVED** [review]

**Comment by hghaf099** [comment]
@mdgreenfield  would you please work on this  #10101 as well. Some tests in there are failing
