### PR TITLE
Fix panic due to metadata being nil

### LINKED ISSUE #4716: Nil-Pointer error on AppRole login
**Describe the bug**
```
2018-06-07 13:55:02.621399 I | http: panic serving 172.18.0.1:41090: assignment to entry in nil map
goroutine 2077 [running]:
net/http.(*conn).serve.func1(0xc420a5f900)
        /goroot/src/net/http/server.go:1726 +0xd0
panic(0x1f14b80, 0x25414d0)
        /goroot/src/runtime/panic.go:502 +0x229
github.com/hashicorp/vault/builtin/credential/approle.(*backend).pathLoginUpdate(0xc42014ad80, 0x255e720, 0xc4205d72c0, 0xc420852ea0, 0xc42094d880, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/builtin/credential/approle/path_login.go:265 +0x6e0
github.com/hashicorp/vault/builtin/credential/approle.(*backend).(github.com/hashicorp/vault/builtin/credential/approle.pathLoginUpdate)-fm(0x255e720, 0xc4205d72c0, 0xc420852ea0, 0xc42094d880, 0xc4206cb8e8, 0x3039302d61396601, 0xc42076f0a8)
        /gopath/src/github.com/hashicorp/vault/builtin/credential/approle/path_login.go:30 +0x52
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc4206cba00, 0x255e720, 0xc4205d72c0, 0xc420852ea0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:223 +0x475
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc4201e6400, 0x255e720, 0xc4205d72c0, 0xc420852ea0, 0x0, 0x0, 0x8000000, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:516 +0x794
github.com/hashicorp/vault/vault.(*Router).Route(0xc4201e6400, 0x255e720, 0xc4205d72c0, 0xc420852ea0, 0xc4203ed530, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:376 +0x4e
github.com/hashicorp/vault/vault.(*Core).handleLoginRequest(0xc420090900, 0x255e720, 0xc4205d72c0, 0xc420852ea0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:664 +0x53b
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc420090900, 0xc420852ea0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:273 +0x35a
github.com/hashicorp/vault/http.request(0xc420090900, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00, 0xc420852ea0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/http/handler.go:408 +0x3c
github.com/hashicorp/vault/http.handleLogical.func1(0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /gopath/src/github.com/hashicorp/vault/http/logical.go:148 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc420024960, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /goroot/src/net/http/server.go:1947 +0x44
github.com/hashicorp/vault/http.handleRequestForwarding.func1(0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /gopath/src/github.com/hashicorp/vault/http/handler.go:360 +0x1ca
net/http.HandlerFunc.ServeHTTP(0xc420024980, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /goroot/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201e9b00, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /goroot/src/net/http/server.go:2337 +0x130
github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /gopath/src/github.com/hashicorp/vault/http/help.go:22 +0x158
net/http.HandlerFunc.ServeHTTP(0xc4200249e0, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /goroot/src/net/http/server.go:1947 +0x44
github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /gopath/src/github.com/hashicorp/vault/http/cors.go:32 +0x10a
net/http.HandlerFunc.ServeHTTP(0xc420024a00, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /goroot/src/net/http/server.go:1947 +0x44
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /gopath/src/github.com/hashicorp/vault/http/handler.go:128 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc420024a20, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /goroot/src/net/http/server.go:1947 +0x44
github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/handlers.go:40 +0xcf
net/http.HandlerFunc.ServeHTTP(0xc420024a40, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /goroot/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc4200af930, 0x255cf20, 0xc420a79ce0, 0xc4201a4f00)
        /goroot/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420a5f900, 0x255e720, 0xc4205d7140)
        /goroot/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /goroot/src/net/http/server.go:2795 +0x27b
```

**Expected behavior**
Successful login as in `v0.10.1` instead of a crash

**Environment:**
* Vault Server Version (retrieve with `vault status`): `v0.10.2`
* Vault CLI Version (retrieve with `vault version`): `n/a`
* Server Operating System/Architecture: `Linux amd64`
* Client library: `hvac==0.2.17`

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #4716

### CODE REVIEW

File: builtin/credential/approle/path_login.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func (b *backend) pathLoginUpdate(ctx context.Context, req *logical.Request, dat
 		return logical.ErrorResponse("invalid role ID"), nil
 	}
 
-	var metadata map[string]string
+	metadata := make(map[string]string)
```
Comment (jefferai) [inline builtin/credential/approle/path_login.go]: In the secret id case, we unilaterally assign to metadata, which means we should still add a nil map check before writing in the role name in case that ever is (or might become with future revisions) nil.

Comment (vishalnayak) [reply builtin/credential/approle/path_login.go]: Secret IDs constructor is initializing the map. So, it is unlikely that metadata is nil. But still, I've added a nil check before assigning the role_name.

Comment (calvn) [reply builtin/credential/approle/path_login.go]: Now that we have the nil check below, allocating the map isn't strictly necessary but I'm good either way :)

**Comment by vishalnayak** [comment]
@calvn I think its a good observation. There really is no reason to have an unnecessary allocation in a hot path. Removed it.

**Comment by jefferai** [comment]
@vishalnayak It's not unnecessary. I'd leave it up above. If it's already allocated the below check will skip, but it provides a measure of safety in case the intervening code modifies it (say, from the bound cidr code) without checking to see if it's nil or not.
