### PR TITLE
token/renewal: return full set of token and identity policies in the …

### LINKED ISSUE #7349: blank page after Renew Token with OIDC auth. renew-self responds policies: null
**Describe the bug**

Token renewal with OIDC auth does not work properly in WebUI. After Token renewal, page reload returns blank page because of invalid data in Browser Local Storage.

**To Reproduce**
1. Login to Vault using OIDC
2. In User Menu click "Renew Token"
3. Reload Page
4. See white blank page

**Expected behavior**

Token renewal should work without side effects.

**Environment:**
* Vault Server Version: 1.2.2
* Vault CLI Version : no cli
* Server Operating System/Architecture: OIDC configured with Keycloak ad IdP

**Additional context**

* Problem not existing with other auth methods (local, ldap, token from ldap)

**Details**
Renew Token creates POST to `/v1/auth/token/renew-self` 
The Response contains auth data with `policies: null`
This policy is saved to the local Storage Key: `vault-token☃1`

REQUEST:

```json
fetch("https://vault.my-domain.ch/v1/auth/token/renew-self", {
    "credentials": "omit",
    "headers": {
        "accept": "*/*",
        "accept-language": "en,de-CH;q=0.9,de;q=0.8,de-DE;q=0.7,en-US;q=0.6,it;q=0.5",
        "cache-control": "no-cache",
        "pragma": "no-cache",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "x-vault-token": "s.REDACTED"
    },
    "referrer": "https://vault.my-domain.ch/ui/vault/secrets",
    "referrerPolicy": "no-referrer-when-downgrade",
    "body": null,
    "method": "POST",
    "mode": "cors"
});
```

RESPONSE

```json
{
    "request_id": "REDACTED",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": null,
    "wrap_info": null,
    "warnings": [
        "TTL of \"768h0m0s\" exceeded the effective max_ttl of \"767h59m50s\"; TTL value is capped accordingly"
    ],
    "auth": {
        "client_token": "s.REDACTED",
        "accessor": "REDACTED",
        "policies": null,
        "token_policies": [
            "default"
        ],
        "metadata": {
            "role": "puzzle"
        },
        "lease_duration": 2764790,
        "renewable": true,
        "entity_id": "REDACTED",
        "token_type": "service",
        "orphan": true
    }
}

```
LOCAL STORAGE DATA:

directly after login: Key: 'vault-token☃1'
```json
{
    "userRootNamespace": "",
    "displayName": "oidc-pgassmann",
    "backend": {
        "type": "token",
        "typeDisplay": "Token",
        "description": "Token authentication.",
        "tokenPath": "id",
        "displayNamePath": "display_name",
        "formAttributes": [
            "token"
        ]
    },
    "token": "s.REDACTED",
    "policies": [
        "default"
    ],
    "renewable": true,
    "entity_id": "REDACTED",
    "ttl": 2764799,
    "tokenExpirationEpoch": 1569251522720
}
```

After "Renew Token"

Key: 'vault-token☃1'
```json
{
    "userRootNamespace": "",
    "displayName": "oidc-pgassmann",
    "backend": {
        "type": "token",
        "typeDisplay": "Token",
        "description": "Token authentication.",
        "tokenPath": "id",
        "displayNamePath": "display_name",
        "formAttributes": [
            "token"
        ]
    },
    "token": "s.REDACTED",
    "policies": null,
    "renewable": true,
    "entity_id": "REDACTED",
    "ttl": 2764681,
    "tokenExpirationEpoch": 1569251523286
}
```

Local Storage with ldap login:

vault-ldap☃1
```json
{
    "userRootNamespace": "",
    "displayName": "pgassmann",
    "backend": {
        "type": "ldap",
        "typeDisplay": "LDAP",
        "description": "LDAP authentication.",
        "tokenPath": "client_token",
        "displayNamePath": "metadata.username",
        "formAttributes": [
            "username",
            "password"
        ]
    },
    "token": "s.REDACTED",
    "policies": [
        "admin",
        "base_admin",
        "base_secret_list",
        "default"
    ],
    "renewable": true,
    "entity_id": "REDACTED",
    "ttl": 2764800,
    "tokenExpirationEpoch": 1569251787173
}
```

Login with Token copied in LDAP Login 

after "Renew Token": 

Response Code is 204 (No Content)

'vault-token☃1':
```
{
    "userRootNamespace": "",
    "displayName": "ldap-pgassmann",
    "backend": {
        "type": "token",
        "typeDisplay": "Token",
        "description": "Token authentication.",
        "tokenPath": "id",
        "displayNamePath": "display_name",
        "formAttributes": [
            "token"
        ]
    },
    "token": "s.REDACTED",
    "policies": [
        "default"
    ],
    "renewable": true,
    "entity_id": "REDACTED",
    "ttl": 2764775,
    "tokenExpirationEpoch": 1569251786578
}
```

### LINKED ISSUE #7385: Error while processing route: vault.index in WebUI
Getting the following Javascript error while trying to access the WebUI in Chrome Version 76.0.3809.100 on OSX.

Vault Version: 1.2.2

Error while processing route: vault.index Cannot read property 'includes' of null TypeError: Cannot read property 'includes' of null

Console image attached. I have restarted the browser and performed a hard reload/clear of the cache. 

Seems to be working fine in Firefox.

Screenshot of Google Chrome (29-8-19, 8-50-02 am)

### PR DESCRIPTION
**Pull request by calvn**
…policies field

Fixes #7385 
Fixes #7349

### CODE REVIEW

File: vault/request_handling.go [hunk 1]
```diff
@@ -868,24 +867,34 @@ func (c *Core) handleRequest(ctx context.Context, req *logical.Request) (retResp
...
-				// a warning but still return as internal error.
-				if err := c.tokenStore.revokeOrphan(ctx, resp.Auth.ClientToken); err != nil {
-					c.logger.Warn("failed to clean up token lease during auth/token/ request", "request_path", req.Path, "error", err)
+		// We skip expiration manager registration for token renewal since it
+		// does not need to be re-registered
+		if strings.HasPrefix(req.Path, "auth/token/renew") {
+			// We build the "policies" list to be returned by starting with
+			// token policies, and add identity policies right after this
+			// conditional
+			resp.Auth.Policies = policyutil.SanitizePolicies(resp.Auth.TokenPolicies, policyutil.DoNotAddDefaultPolicy)
```
Comment (ncabatoff) [inline vault/request_handling.go]: Why do we assign to Policies here instead of TokenPolicies as in the other branch?

Assuming my intuition is correct - that the assignment should be the same regardless of whether or not this is a renewal -  I think the code might be a bit clearer if you do the assignment as a first step, then extend the following switch statement, like:

```
resp.Auth.TokenPolicies = policyutil.SanitizePolicies(resp.Auth.Policies, policyutil.DoNotAddDefaultPolicy)
switch {
case strings.HasPrefix(req.Path, "auth/token/renew"): // do nothing
case resp.Auth.TokenType == logical.TokenTypeBatch: // do nothing
case resp.Auth.TokenType == logical.TokenTypeService: // do registration
}
```

Comment (calvn) [reply vault/request_handling.go]: This doesn't work because `resp.Auth.Policies` returned by a renewal response after routing is empty (the token policies are returned under `resp.Auth.TokenPolicies`), and hence why we need to add them to `resp.Auth.Policies` and not the other way around.

Comment (ncabatoff) [reply vault/request_handling.go]: I wish I understood why it's like that, but my timeboxed foray into the code for answers didn't bear fruit.  Anyway, I don't think this will break anything, and it solves the existing problem, so I'll let it go.

Comment (calvn) [reply vault/request_handling.go]: I dug a bit further to try to understand it a bit more as well. The `Auth` object in `resp.Auth` comes from the associated lease entry in the token, which is assigned in `renewAuthEntry` that we hit during the renewal request flow. It looks like the `policies` field omits the default policy, and thus either 1) does not contain the full set of token policies or 2) stores a `null` object for that field if default is the only policy (as seen by the examples below when reading the lease entry in storage). That inconsistency may or may not need to be addressed separately, but in any case using `token_policies` as the starting set for token policies is the more reliable way to build `resp.Auth.Policies`.

User bob on userpass with no policy attached, just the default:
```
  "auth": {
    "lease": 2764798000000000,
    "max_ttl": 0,
    "renewable": true,
    "internal_data": null,
    "display_name": "userpass-bob",
    "policies": null,
    "token_policies": [
      "default"
    ],
...
```

User bob with "test" policy attached:
```
  "auth": {
    "lease": 2764798000000000,
    "max_ttl": 0,
    "renewable": true,
    "internal_data": null,
    "display_name": "userpass-bob",
    "policies": [
      "test"
    ],
    "token_policies": [
      "default",
      "test"
    ],
```
